### ISSUE TITLE
Error updating to 1.2.0

### ISSUE THREAD

**Issue by codemonkey812** [scalda/Foolcraft_3#100]
![image](https://user-images.githubusercontent.com/38060524/40946674-c5236fce-682c-11e8-85cf-27507a26d263.png)

Help I have updated my server and I cannot get my client to update. Now I cannot connect to my server.

**Comment by Mrbysco** [comment]
Have you tried completely reinstalling it on your client?

**Comment by scalda** [comment]
This is a time out error with the twitch/curse launcher. you will need to keep just trying also you removed the issue template but i am closing this now as it does not relate to a problem within the pack
