### ISSUE TITLE
Unable to remove infinity booster card from wireless crafting terminal

### ISSUE THREAD

**Issue by DrKlicker** [scalda/Foolcraft_3#101]
## Modpack Information
- [ ] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [ ] In single player
     - [x] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
After having added an infinity booster card to my wireless crafting terminal, I am unable to remove it. My plan was to only use it in my crafting terminal temporarily while I waited for 1.3.0 to be released which I was told should resolve the extendedcrafting bug.

## Reproduce Steps
Obtain infinity booster card from ender dragon.
Insert into wireless crafting terminal.
I am unable to remove it.

**Comment by scalda** [comment]
Can you remove it if you break the item it is in?

**Comment by DrKlicker** [comment]
It's in a wireless crafting terminal. Not sure how to "break" it.
