### ISSUE TITLE
Thaumcraft golems unable to place blocks/sapplings

### ISSUE THREAD

**Issue by KBoo96** [scalda/Foolcraft_3#104]
## Modpack Information
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [x] In single player
     - [x] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
Thaumcraft golems are unable to place down blocks/sapplings. The golem gets a place block instruction through the 'use' seal and attempts to place down the block it's carrying. The golem's 'place block' animation plays, however the block doesn't get placed and the server console spits out an error message. At this point the golem keeps trying to place the block and basically gets stuck.

## Reproduce Steps
Get a Thaumcraft golem to take a block from a chest, either through the 'provide' seal or the 'empty' seal. Then have the golem try to place the block with the 'use' seal.

## Additional Information
The server console returns the following whenever a golem tries to place a block:
[https://pastebin.com/zN5ZwXp1](https://pastebin.com/zN5ZwXp1)

**Comment by generrosity** [comment]
I see in there "FTBUtilitiesPermissionHandler.hasPermission" - do you have your chunks claimed and locked down?

**Comment by KBoo96** [comment]
I don't remember claiming any chunks but disabling the chunk claiming in the ftbutilities config did fix it. I'll do some more testing with chunk claiming enabled later on. Thanks for pointing me in the right direction.

**Comment by generrosity** [comment]
Nice! You might be able to give permissions to the fake user that is thaumcraft? But I'd also suggest trying out somewhere outside your base too. 

Do hit the "close" button if you think you've got it sorted

**Comment by KBoo96** [comment]
I can't get it to work with the claiming enabled, I tried with both claimed chunks ([using these team settings](https://imgur.com/a/24v4Ol1)) and unclaimed chunks. I've also tried a few different locations but they generate the same result. 
Since chunk claiming wasn't being used anyway leaving it off is a good workaround for now.

Thanks again for the help.
