### ISSUE TITLE
Ender IO crafter keeps bugging out. Recipes get moved out of the game. Like tiny dry rubber into rubber just doesnt work anymore after using the Ender IO crafter

### ISSUE THREAD

**Issue by LorenzoVermeer** [scalda/Foolcraft_3#105]
## Modpack Information
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [x] In single player
     - [ ] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [x] I am crashing and can provide my crash report(s)
- [x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

**Comment by kpeckett** [comment]
You appear to have left the issue template as it was... was this intentional?
