### ISSUE TITLE
Suggestion: Custom NPC mod

### ISSUE THREAD

**Issue by generrosity** [scalda/Foolcraft_3#106]
## FEATURE REQUEST
- [X] I would like to propose an additional mod.
- [ ] I would like to propose a config change.
- [ ] I would like to propose a custom recipe.
- [ ] I would like to propose another change.

## MOD INFORMATION

Custom NPCs by Noppes - https://minecraft.curseforge.com/projects/custom-npcs/

Varied Commodities by Noppes https://minecraft.curseforge.com/projects/varied-commodities

**Comment by scalda** [comment]
Sadly custom NPCs cause more issues then they are worth in large mod packs, we only like to have custom npcs if we really have to.
