### ISSUE TITLE
52 nether stars when killing the wither

### ISSUE THREAD

**Issue by tomerkenis** [scalda/Foolcraft_3#109]
## Modpack Information
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [x] In single player
     - [ ] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [] I am crashing and can provide my crash report(s)
- [x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

When i kill the wither it gives me 52 'Rib of the Wither' and 52 nether stars

**Comment by kpeckett** [comment]
What weapon did you use to land the final hit on the Wither? What are its stats and enchantments?

**Comment by Mrbysco** [comment]
Are you wearing samurai gear from Mega Loot? Those are known to increase the amount of wither loot A LOT

**Comment by TheonlyTazz** [comment]
its because of the LUCK stat on your helmet
each luck lvl on your helmet increases your netherstar&rib by 1

**Comment by scalda** [comment]
yeah this is to do with the luck aspect of the megaloot armor, so enjoy your stars as this is not a bug thanks for reporting it though
