### ISSUE TITLE
Dupe report!

### ISSUE THREAD

**Issue by smmailik** [scalda/Foolcraft_3#110]
## Modpack Information
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [x] In single player
     - [ ] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
On all the crafting tables from @Extended Crafting but basic one you can "dupe" or get some free items, 
they are legit, they can be placed in the world and they work perfectly. You can take them as many times you want.

## Reproduce Steps
Under the square where you take your crafeted item there is the button with № 16 on it if you press it you can cycle through a bunch of items mostly from @Immersive Ingineering and take them out.. 

## Additional Information
Screens :
1  https://imgur.com/r0oGZcS
2  https://imgur.com/v0VTYfu
3  https://imgur.com/nXKVUkC
4  https://imgur.com/XtQWZro
5  https://imgur.com/d6bNnyV

**Comment by smmailik** [comment]
P.S. Can't also craft the Ultimate ingot, I place everything and nothing, all 40 ingots and the pearl .. cheked everything 5 times .. doesen't start crafting  (Pack Version: 1.2 )

**Comment by scalda** [comment]
I am aware of this and this will be fixed in 1.4 updates when I resort to updating and testing all available mods.

As for the ultimate ingot i am not sure why it isn't working for you as there is nothing special regarding any of the ingots. Can you post a picture of your setup please?

**Comment by smmailik** [comment]
Screens :  
 https://imgur.com/DtSHi1k
 https://imgur.com/wWoW3Fh

**Comment by scalda** [comment]
ok wait for 1.3 to release update and try it out as the mod has updated a few times to fix issues so see if that fixes your issue as i know from my testing and making the recipe it works

**Comment by smmailik** [comment]
OK, when the 1.3 will be relleased?

**Comment by smmailik** [comment]
Hey ,wanted to confirm that the craft started to work in V1.3     :3   ty ))
