### ISSUE TITLE
SHIFT+chatkey not bragging about items

### ISSUE THREAD

**Issue by jeviuss** [scalda/Foolcraft_3#111]
## Modpack Information
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [ ] In single player
     - [x] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
SHIFT+chatkey doesn't brag about items

## Reproduce Steps
press SHIFT+chatkey when hovering over items in inventory, on ground, in hand

## Additional Information
Can you clarify how this is supposed to work for me? I'm probably doing something wrong haha

**Comment by Mrbysco** [comment]
It only works for MegaLoot items

**Comment by scalda** [comment]
What @Mrbysco said
