### ISSUE TITLE
Looking up what items have the thaumcraft aspects causes your game to crash

### ISSUE THREAD

**Issue by theBluebaerry** [scalda/Foolcraft_3#112]
## Modpack Information
- [x ] I am running the latest version of FoolCraft
- [x ] I am running FoolCraft via Curse/Twitch Launcher
- [ x] I can reproduce this issue consistently
     - [ ] In single player
     - [ x] In multiplayer
- [x ] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [x ] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

Looking up thaumcraft aspects in JEI will cause your game to crash if you go to the second tab with the thauminomicon icon.

To reproduce this bug, left click on an aspect (e.g. Auram) and then click on the second tab (Aspect from item stack) in the JEI results window.

Sorry, I couldn't find how to get the crash report but I can get this little piece of information:

https://i.imgur.com/kUZz8Iu.png

**Comment by scalda** [comment]
Crash report?

**Comment by theBluebaerry** [comment]
I don't know how to get it, but give me a minute and I'll try figure it out

**Comment by theBluebaerry** [comment]
[crash-2018-06-08_07.48.33-client.txt](https://github.com/scalda/Foolcraft_3/files/2086461/crash-2018-06-08_07.48.33-client.txt)

**Comment by theBluebaerry** [comment]
Yup it seems to be fixed in 1.4.5, thanks!
