### ISSUE TITLE
Failed to render entity in world (wisp from thaumcraft)

### ISSUE THREAD

**Issue by DrKlicker** [scalda/Foolcraft_3#115]
## Modpack Information
- [ ] I am running the latest version of FoolCraft
- [X] I am running FoolCraft via Curse/Twitch Launcher
- [X] I can reproduce this issue consistently
     - [ ] In single player
     - [X] In multiplayer
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
When player is morphed into a wisp from thaumcraft in the presence of another player, the following exception occurs:
The game crashed whilst rendering entity in world
The game crashed whilst rendering entity in world
Error: java.lang.ClassCastException: thaumcraft.client.renderers.entity.mob.RenderWisp cannot be cast to net.minecraft.client.renderer.entity.RenderLivingBase

## Additional Information
https://pastebin.com/784ZWR1G

**Comment by scalda** [comment]
This is a issue from the hats mod please report to them
