### ISSUE TITLE
Unable to craft player head in Botania's Runic altar.

### ISSUE THREAD

**Issue by scopiplays** [scalda/Foolcraft_3#117]
## Modpack Information
- [x ] I am running the latest version of FoolCraft
- [ x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [x ] In single player
     - [ ] In multiplayer
- [x ] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [x ] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description

Cannot craft player head in Botania runic altar.  Recipe in JEI says: Golden Apple, NameTag, Pixie dust, prismarine shard, and skelly skull.  

## Reproduce Steps

place 5 items on runic alter and provide mana, nothing happens

## Additional Information

installed optifine, twich chat integration and updated Statues mod to latest cuz Sven made me.

**Comment by Necro9227** [comment]
The botania recipe requires a Named nametag, it will give you the player head of the persons name. 
E.g renaming the nametag iskall85 (must be exact and is case sensitive) should result in obtaing Iskalls player skin.

**Comment by scopiplays** [comment]
thank you @Necro9227
