### ISSUE TITLE
[Bug] Disconnecting when changing Area miner

### ISSUE THREAD

**Issue by TheonlyTazz** [scalda/Foolcraft_3#118]
## Modpack Information
- [x] I am running version 1.2.0 of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [ ] In single player
     - [x] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
created a Megaloot Pickaxe and upgraded it, now when changing the size of Area Miner will cause my Client to disconnect from the server after changing the size. meaning, i will need to disconnect 5x to get back to 1x1. This happened before with one pick. an other pick was working fine with Area Miner

## Additional Information
https://i.imgur.com/VWAow6H.png
https://i.imgur.com/Yv3ZRxi.png
https://pastebin.com/anJnfqMN  << as im not crashing, this is basicly all the info that i have... from the game output

**Comment by kpeckett** [comment]
Are you able to contact the server admin to get the server log around the time of the disconnect? If it's one of Iskall85's patron servers, which server is it?

**Comment by TheonlyTazz** [comment]
i tried contacting the server admin and he gave me this after i crashed:
https://pastebin.com/QhV5CUmC
although i doubt there is anything usefull in there
