### ISSUE TITLE
Server crash on startup.

### ISSUE THREAD

**Issue by Wizardon777** [scalda/Foolcraft_3#12]
FoolCraft Version: 1.0.0
Forge Version: forge-1.12-14.21.1.2443
Java Version: 1.8.0_111

Crash report included:
[crash-2018-05-18_22.14.34-server.txt](https://github.com/scalda/Foolcraft_3/files/2018335/crash-2018-05-18_22.14.34-server.txt)

**Comment by KaptainWutax** [comment]
Error comes from Forge when parsing the Chizel and Bits main class : @Mod(version = null)

**Comment by Wizardon777** [comment]
Found the problem, I was using an older version of forge, works fine with the correct version.

Sorry for the trouble, it was my mistake 😝
