### ISSUE TITLE
Mod Request: Akashic Tome

### ISSUE THREAD

**Issue by ChromeMystic** [scalda/Foolcraft_3#123]
## FEATURE REQUEST
- [X] I would like to propose an additional mod.
- [ ] I would like to propose a config change.
- [ ] I would like to propose a custom recipe.
- [ ] I would like to propose another change.

## MOD INFORMATION
https://minecraft.curseforge.com/projects/akashic-tome  Akashic Tome should do the Trick :)

**Comment by smmailik** [comment]
+1 Looks good and functional .. :) :+1:

**Comment by scalda** [comment]
no sorry
