### ISSUE TITLE
Cannot place saplings in Bonsai Pot or Hopping Bonsai Pot

### ISSUE THREAD

**Issue by JRSofty** [scalda/Foolcraft_3#125]
## Modpack Information
- [X] I am running the latest version of FoolCraft
- [X] I am running FoolCraft via Curse/Twitch Launcher
- [X] I can reproduce this issue consistently
     - [X] In single player
     - [ ] In multiplayer
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
With a simple Oak sapling in my primary hand I right click on the Bonsai pot and nothing happens. The sapling is still in my hand and the pot is unchanged. I then made the bonsai pot into a hopping bonsai pot and again right clicked with a single oak sapling in my hand and again nothing happend. 

## Reproduce Steps
1. Create a Bonsai Pot with one normal dirt and 5 bricks.
2. Place the Bonsai Pot on the ground.
3. Take a single Oak Sapling from your inventory and place it in your player's primary hand.
4. Right click the Bonsai Pot. 

If it is working the sapling would no longer be in your player's hand. However, in my game, I still have the sapling, so I have to assume it's not working.

## Additional Information
No crash occurs. 

Using the default Java that comes with the Minecraft installer (Java 1.8_025 64bit) on a Windows 10 using most recent updates.

**Comment by scopiplays** [comment]
make sure you off hand is empty

**Comment by JRSofty** [comment]
Ah, thanks for that. It works now. Maybe it would be nice if someone would put that in the documentation?
