### ISSUE TITLE
Cannot craft ultimate ingot

### ISSUE THREAD

**Issue by jeviuss** [scalda/Foolcraft_3#126]
## Modpack Information
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [ ] In single player
     - [x] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
I cannot craft the ultimate ingot, I have all fourty pedestals with the correct metals on them, with the crafting table in the middle with an infused enderpearl and RF, but it says no recipe found.

## Reproduce Steps
create the setup and watch it not work

## Additional Information
I have tried multiple arrangements of tables, none work

**Comment by oacaptain** [comment]
I am on version 1.4.5 and still can't craft it do we have any news on it??

**Comment by Mrbysco** [comment]
I've heard it's craftable so I dunno what you are doing wrong. May I get a screenshot of your setup?

**Comment by oacaptain** [comment]
Yes I'll sent you right away

**Comment by oacaptain** [comment]
![2018-07-19_20 37 08](https://user-images.githubusercontent.com/34013573/42960201-c7c82ca8-8b93-11e8-9d52-d83d4e9a95b4.png)
![2018-07-19_20 37 18](https://user-images.githubusercontent.com/34013573/42960202-ccbd9b62-8b93-11e8-865b-8cb262a01bd2.png)
![2018-07-19_20 37 49](https://user-images.githubusercontent.com/34013573/42960205-cefd2262-8b93-11e8-93c5-32139b533e41.png)

**Comment by oacaptain** [comment]
Thank you in advance Mrbysco for giving me immediate attention!!!

**Comment by oacaptain** [comment]
Any news Mrbysco on the matter?

**Comment by Mrbysco** [comment]
A friend of mine that used the recipe before says "I think they have an enhanced ender ingot instead of a redstone ingot"

**Comment by oacaptain** [comment]
[Ultimate Ingot recipe.txt](https://github.com/scalda/Foolcraft_3/files/2259326/Ultimate.Ingot.recipe.txt)
Hello Mrbysco if you have the means to inform the community about the recipe this is it, all the correct ingots, thank you for helping and having the time to respond!!

**Comment by scalda** [comment]
see above
