### ISSUE TITLE
Suggestion : Update Immersive Tech

### ISSUE THREAD

**Issue by Frinn38** [scalda/Foolcraft_3#127]
## FEATURE REQUEST
- [ ] I would like to propose an additional mod.
- [ ] I would like to propose a config change.
- [ ] I would like to propose a custom recipe.
- [X ] I would like to propose another change.

## FEATURE INFORMATION
The actual version of immersive tech is 1.12.2-1.3.8, I suggest to update this mod to 1.12.2-1.3.10 (latest version) to make the alternator of the steam turbine compatible with others energy cables than IE ones.

**Comment by generrosity** [comment]
Next update is planned to have updates to all mods - do give it a test and report any problems, but this request is planned.

**Comment by scalda** [comment]
updated in 1.4.3, which will be out soon but i am having a single issue that i have just found and hopefully the mod authors can get back to me
