### ISSUE TITLE
Suggestion: Add Extra Cells 2

### ISSUE THREAD

**Issue by Zaxvert** [scalda/Foolcraft_3#128]
## FEATURE REQUEST
- [x] I would like to propose an additional mod.
- [ ] I would like to propose a config change.
- [ ] I would like to propose a custom recipe.
- [ ] I would like to propose another change.

## MOD INFORMATION
I would like to have the mod Extra Cells 2 added. It's an addon mod for Applied Energistics 2 which allows fluids to be handled and stored in an ME System but also allows for larger normal storage drives. I have added it on my own server and have not ran into any problems.
[Extra Cells 2](https://minecraft.curseforge.com/projects/extracells2)

**Comment by TheonlyTazz** [comment]
Especially because there is an add-on mod for refined storage that add more bigger storage solutions

**Comment by tayacrystals** [comment]
Yes, we ae2 folks would really apprechiate that!

**Comment by Zelda-Swordsman** [comment]
With the most recent update to Foolcraft, AE supports fluid handling internally. Still a bit WIP such as autocrafting with specific fluid amounts, but still very functional. Still, having Extra Cells 2 would still be great for the extra large storage cells:)

**Comment by scalda** [comment]
no sorry
