### ISSUE TITLE
Add Sooty Marble to Chisel

### ISSUE THREAD

**Issue by Protius7331** [scalda/Foolcraft_3#129]
## FEATURE REQUEST
- [ ] I would like to propose an additional mod.
- [x] I would like to propose a config change.
- [x] I would like to propose a custom recipe.
- [ ] I would like to propose another change.

## FEATURE INFORMATION
I would like to suggest adding a Sooty Marble from Astral Sorcery Chisel group. As the normal marble can be chiseled, it would be useful to be able to use the sooty variant instead of crafting it in the Astral table. Also, the sooty variants are only useful for decoration. I have already edited and tested the Chisel script from the pack, here is a Pastebin of the modified script if the change is approved:

https://pastebin.com/VjdkN4wS

Thank you for your consideration.

**Comment by scalda** [comment]
thanks for thsi i will add for 1.5.1
