### ISSUE TITLE
Crafttweaker recipe typo

### ISSUE THREAD

**Issue by Zelda-Swordsman** [scalda/Foolcraft_3#130]
There is a typo in one of the crafttweaker scripts, causing the custom recipes to not load properly, seemingly because of an "invalid expression". 
Version: Release- 1.3.1

![screenshot 9](https://user-images.githubusercontent.com/36285521/41203888-6a9b6592-6cab-11e8-8176-cffa981346ea.png)

**Comment by Zelda-Swordsman** [comment]
![screenshot 10](https://user-images.githubusercontent.com/36285521/41203918-c2770866-6cab-11e8-8d83-d9baa820f54f.png)

**Comment by scalda** [comment]
damn it i see what i did

**Comment by scalda** [comment]
I am fixing and reuploading

**Comment by scalda** [comment]
files have been reuploaded to curse awaiting approvel thanks again

**Comment by Zelda-Swordsman** [comment]
Np

**Comment by scalda** [comment]
this has been fixed in 1.3.1 thanks again
