### ISSUE TITLE
Astral Sorcery Attunement Step Assist not working

### ISSUE THREAD

**Issue by Jaciii** [scalda/Foolcraft_3#131]
## Modpack Information
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [x] In single player
     - [ ] In multiplayer
- [ ] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
I work with the Astral Sorcery mod and attuned myself with Vicio, and a perk you can get is step assist (Hiking Boots), but it doesn't work.

## Reproduce Steps
Attune myself with Vicio and get the step assist perk (Hiking Boots)

**Comment by Yadokingu** [comment]
Are you sure that is a problem with the pack and not jsut an Astral Sorcery bug? It does have quite a few bugs.

**Comment by Jaciii** [comment]
I have tried it before with a different step assist in a different modpack, and there was another mod that was checking if i had that ability from that mod, so it didn't work with the mod I was using.

**Comment by scalda** [comment]
try 1.5 beta and report back please
