### ISSUE TITLE
Immersive Engingierring Tool Dupe

### ISSUE THREAD

**Issue by JTKillien** [scalda/Foolcraft_3#133]
## Modpack Information
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [x] In single player
     - [ ] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
When trying to repair the IE  Hammer with another one in the 2x2 crafting grid it will give a fully repaired hammer while keeping the damaged ones. This can be done as many times as you like.

## Reproduce Steps
Combine the 2 damaged Immersive Engingering Hammers in the 2x2 crafting grid.

**Comment by ChromeMystic** [comment]
I was able to duplicate in the Refined Storage grid doing the same.

**Comment by scalda** [comment]
can you try this in beta 1.5 please and report back
