### ISSUE TITLE
Grid Power from Extra Utilities stops after 240 blocks 

### ISSUE THREAD

**Issue by oacaptain** [scalda/Foolcraft_3#134]
## Modpack Information
- [ x] I am running the latest version of FoolCraft
- [x ] I am running FoolCraft via Curse/Twitch Launcher
- [x ] I can reproduce this issue consistently
     - [ x] In single player
     - [ ] In multiplayer
- [x ] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [x ] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
After crafting the angel ring tried to fly and the grid power stops at around 240 blocks from the water and egg mills. Grid power is 668

## Additional Information
https://imgur.com/UYjHbyQ
https://imgur.com/8wUbVh1
https://imgur.com/TpR5jFI
https://imgur.com/7pUPnpQ

**Comment by kpeckett** [comment]
Did the chunks unload? Are you using a weirding gadget to keep your GP loaded?

**Comment by oacaptain** [comment]
Noooo didn't use a gadget, the chunk loading of FTB doesn't work?

**Comment by oacaptain** [comment]
testing it now with a weirding gadget to see if it persists or not!!

**Comment by oacaptain** [comment]
Yep that was the problem the chunks were unloading, such a Fool I am!!

**Comment by kpeckett** [comment]
FTBUtils Chunk loading is notoriously buggy, hence why it is disabled in the default config of the pack. Chunk claiming is on, but chunkloading is off. The wierding gadget is the recommended chunk loader for FoolCraft, especially on multiplayer servers.

**Comment by oacaptain** [comment]
If you put one in the claimed chunks does it load all of them or only the respective chunk? And thank you for the amazing help!!

**Comment by Mrbysco** [comment]
It only loads the single chunk the weirding gadget is in.

**Comment by oacaptain** [comment]
Thank you everybody for your amazing support!!!!
