### ISSUE TITLE
Enchanting @ anvil crash, logs provided

### ISSUE THREAD

**Issue by CSTufts** [scalda/Foolcraft_3#135]
## Modpack Information
- [x ] I am running the latest version of FoolCraft 
- [ x] I am running FoolCraft via Curse/Twitch Launcher
- [ ] I can reproduce this issue consistently
     - [ ] In single player
     - [ ] In multiplayer
- [ ] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ x] I am crashing and can provide my crash report(s)
- [x ] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
No big issue, but I got a crash log, feel free to just close issue if you feel it necessary. 

## Reproduce Steps
I was simply enchanting my pickaxe and shift clicked the silk touch book into the anvil and a crash occurred, see logs attached

## Additional Information

https://pastebin.com/3q4T9DWn

lmk if you need anything else thanks team!
great work as always

**Comment by Mrbysco** [comment]
Your tool had an enchantment that was removed in one of the updates.

**Comment by Mrbysco** [comment]
I've seen this exact crash when I myself was trying to enchant mine. But only I tried to do it in an auto-enchanter crash-looping a server.

I would say get a new pickaxe even if your pickaxe was great.
There's no way to really get rid of the broken enchants

**Comment by CSTufts** [comment]
that stinks :/ all good though (just a diamond one that I was gonna throw silktouch on... I will just make a new one, got a sweet multitool axe from an epic chest!

thanks for the info!
