### ISSUE TITLE
Client & server mods doesn't match for 1.3.1

### ISSUE THREAD

**Issue by JayJay1989** [scalda/Foolcraft_3#136]
## Modpack Information
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [x] In single player
     - [x] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
Cant connect to server for "mod rejections"

## Reproduce Steps
updated the modpack with Twitch launcher, updated the server with the latest "server files"
Start the client & server, connect

## Additional Information
see this [pastebin](https://pastebin.com/6bfTepM2)

**Comment by scalda** [comment]
I am already aware I am just having dinner and got to reupload.

**Comment by scalda** [comment]
Also sorry for the inconveince, i some how managed to copy my mods folder for my 1.4 version instance instead of the 1.3.1 instance



SO IF YOU HAD ALREADY UPDATED TO THE OLD 1.3.1 FILES YOU ME NEED TO INSTATE A BACKUP OF THE WORLD JUST INCASE SOMETHING IS WRONG.



sorry again

**Comment by scalda** [comment]
correct 1.3.1 is now on curse
