### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by Gludek** [scalda/Foolcraft_3#137]
## Modpack Information
- [X] I am running the latest version of FoolCraft
- [X] I am running FoolCraft via Curse/Twitch Launcher
- [X] I can reproduce this issue consistently
     - [X] In single player
     - [ ] In multiplayer
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
My game crashes when i try to load my save, in crash log it says that there's a problem with ender storage, i suspect problem with enderchest and compacting machines

## Reproduce Steps
Put 3 or 4 different pairs enderchest and from one pair take enderchest into the biggest compacting machine

## Additional Information
https://pastebin.com/ynZEZgir

**Comment by Mrbysco** [comment]
Seems to be related to TheCBProject/EnderStorage#69. Quoting what Covers said "EnderStorage's data wasn't properly saved and is lost, delete the EnderStorage folder in your word and start again."

**Comment by Gludek** [comment]
Thanks, that worked, but now i got different crash report something with SYNC mod https://pastebin.com/gr7NBgmS

**Comment by Mrbysco** [comment]
Going off of the crash log there seems to already be a tileentity where there shouldn't be one. Hmmmm.. weird

**Comment by Gludek** [comment]
Is there anyway to fix it? If not then you can probably close this issue

**Comment by Mrbysco** [comment]
There's a way to remove erroring TileEntities. Edit the forge.cfg file in the config folder and change the following entry to true like this: B:removeErroringTileEntities=true

After doing so launch your game and join your world. The erroring tileentity should be gone.
Then you should set it back to false in the config and reboot your game.

**Comment by Gludek** [comment]
I dit it and when i was joing world it still crashed with the same error

**Comment by Mrbysco** [comment]
Weird. It should remove the erroring tileeentity

**Comment by Gludek** [comment]
Wait, it changed a bit, crashlog is longer https://pastebin.com/Za0DnimC

**Comment by Gludek** [comment]
I removed SYNC blocks with MCEdit, now i have this crashlog https://pastebin.com/0c51sUGh

**Comment by Gludek** [comment]
Anyway this issue can be closed

**Comment by Gludek** [comment]
@Mrbysco hey, i think that after i remove Enderstorage folder when it causes crashes it changes some id so i can't play save, i noticed it when i crashed away from my base, because there was flax floweres instead of vines on walls in RD
