### ISSUE TITLE
Specific mini moos crash when milked

### ISSUE THREAD

**Issue by missatessatessy** [scalda/Foolcraft_3#139]
## Modpack Information
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [ ] In single player
     - [x] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [x] I am crashing and can provide my crash report(s)
- [x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
This is different from the previous crash report:
Specific types of mini moos (for example the life essence mini moo) will crash the server/client when milked in any form, via bucket/mech user/rancher.
When it is caused by milking it with a mech user/rancher the server will repeatedly crash if a player is loading that chunk.
If you milk with a bucket it will only crash the client.

## Reproduce Steps
Milk a life essence mini moo with a bucket.
Put a life essence mini moo in front of a mech user/rancher

## Additional Information
https://pastebin.com/ER3t8hNE
Edit: realised that any moo can cause this

**Comment by Chik3r** [comment]
The crash report says that `com.ricardothecoder.minimoos.library.entities.EntityFluidMoo.testMilking()` is **dividing by zero**
Line 39-46

**Comment by scalda** [comment]
this should all work in 1.5 now and correctly aswell
