### ISSUE TITLE
Ice from void resource miner giving all chisel variants

### ISSUE THREAD

**Issue by Matchyman** [scalda/Foolcraft_3#140]
## Modpack Information
- [ x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x ] I can reproduce this issue consistently
     - [ ] In single player
     - [x ] In multiplayer
- [] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [x ] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
Using the resource miner into ender chest into drawers, gives all chisel varients of ice 

## Additional Information
https://i.imgur.com/wGrP6Sw.png

**Comment by Yadokingu** [comment]
Yep that is a problem. My temporary workaround is to pipe it through an auto-chisel and unchisel it back to normal ice.

**Comment by Matchyman** [comment]
Okay thats the work around i also did, must be a mod issue then :) 
Still a great pack though

**Comment by Mrbysco** [comment]
1.4.4 has been released where this has been fixed.
