### ISSUE TITLE
Missing stuff? Refined Storage.

### ISSUE THREAD

**Issue by Dazzah** [scalda/Foolcraft_3#141]
## Modpack Information
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [x] In single player
     - [ ] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
Upon looking at the wiki for Refined Storage. ([https://refinedstorage.raoulvdberge.com/wiki](https://refinedstorage.raoulvdberge.com/wiki)) I have determined that some blocks are missing, I'm not quite sure if its intentional or not, but neither the network transmitter, nor the receiver are in the game. I cannot even see them in JEI, but I can find evidence of them in the configs. 
Is it a bug? or by design?

## Reproduce Steps
Type in JEI; network receiver, and nothing shows up.

In the config folder, hit ctrl+f and type Network Receiver.

**Comment by Mrbysco** [comment]
By design. The network stuff has caused lag in previous tests.
