### ISSUE TITLE
Request: Add recipe for creative storage upgrade (Storage Drawers)

### ISSUE THREAD

**Issue by Yadokingu** [scalda/Foolcraft_3#142]
## FEATURE REQUEST
- [ ] I would like to propose an additional mod.
- [ ] I would like to propose a config change.
- [X] I would like to propose a custom recipe.
- [ ] I would like to propose another change.

## FEATURE INFORMATION
Not to be confused with the creative vending upgrade, which would give you free stuff, the creative storage upgrade just adds a lot of space to a drawer. So it basically becomes a black hole unit (which are also in this pack), but a bit esiear to manage and more convenient, since you can interact with them through the controller, have compacting drawers, etc.
This could be some late game ultimate crafting, maybe requiring a bunch of emerald tier storage upgrades.

**Comment by XerShade** [comment]
So does a single void upgrade and five or six, whatever fills the rest of the slots, emerald upgrades.

**Comment by Yadokingu** [comment]
That doesn't give nearly enough storage for the hoarder with a top tier void ore miner and good ore processing.

**Comment by kpeckett** [comment]
The number of items per drawer will be more than you ever need though, right?

**Comment by scalda** [comment]
will implement for 1.5.1
