### ISSUE TITLE
Request: Long Fall Boots Mod

### ISSUE THREAD

**Issue by bighagrid** [scalda/Foolcraft_3#144]
## FEATURE REQUEST
- [ X] I would like to propose an additional mod.
- [ ] I would like to propose a config change.
- [ ] I would like to propose a custom recipe.
- [ ] I would like to propose another change.

## MOD INFORMATION
Mod Adds Long Fall Boots to the game that prevent fall damage. This item used to appear in older versions of Portal Gun.

https://minecraft.curseforge.com/projects/long-fall-boots

**Comment by Gludek** [comment]
These boots are also in portalgun mod i think

**Comment by bighagrid** [comment]
they are not in the version of portalgun mod that's in this modpack.

**Comment by scalda** [comment]
sorry won't be adding this
