### ISSUE TITLE
IDs in world changing after fixing crash with EnderStorage data

### ISSUE THREAD

**Issue by Gludek** [scalda/Foolcraft_3#145]
## Modpack Information
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [x] In single player
     - [ ] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [x] I am crashing and can provide my crash report(s)
- [x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
I got crash that was related to EnderStorage data incoretly loaded, @Mrbysco helped me, but i wasn't able to still load the world, after restoring backup and getting crash away from home, i removed enderstorage folder and after loading i noticed that blocks changed for example, vines turned into flax seeds etc.

## Reproduce Steps
Getting Enderstorage related crash, and being in my base

## Additional Information
Previously opened issue related to this https://github.com/scalda/Foolcraft_3/issues/137

**Comment by Darkstone158** [comment]
How did you fix the ender storage crash im having the same or similar problem with it

**Comment by Gludek** [comment]
@Darkstone158 remove ender storage folder from world folder, i recommend backuping whole world because you may encouter same problem

**Comment by scalda** [comment]
i would just restore to an older backup
