### ISSUE TITLE
Opening ExtraUtils2 manual crashes the game

### ISSUE THREAD

**Issue by CDArena** [scalda/Foolcraft_3#146]
## Modpack Information
- [ ] I am running the latest version of FoolCraft
- [x ] I am running FoolCraft via Curse/Twitch Launcher
- [x ] I can reproduce this issue consistently
     - [x ] In single player
     - [ ] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ x] I am crashing and can provide my crash report(s)
- [x ] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
I crafted the Extra Utils 2 manual, then tried to open it. Game froze and crashed. I updated my twitch launcher's version of java (from the default 1.8_25) and tried again - another crash.  Game plays normally otherwise.

## Reproduce Steps
step 1 - Craft an extra utils 2 manual (book+gold ingot+obsidian)
step 2 - Right click to open the book

## Additional Information
crash report: 
https://pastebin.com/G1PJT2Wg

**Comment by ClaudiusMinimus** [comment]
This bug continues. I crafted the manual and twice I attempted to open it and both times the client immediately crashed
https://paste.ee/p/dYSfp

**Comment by MizzBlondie** [comment]
I have the same issue!
Crafting or using an already existing Extra Utils Manual makes a crash. 
Here is the Crash Report! 
[Crash Report.txt](https://github.com/scalda/Foolcraft_3/files/2267048/Crash.Report.txt)
Mvh MissBlondie

**Comment by scalda** [comment]
been reported her https://github.com/rwtema/extrautilities_old_issues/issues/1786
