### ISSUE TITLE
Extended Crafting 

### ISSUE THREAD

**Issue by EmeraldCleaver77** [scalda/Foolcraft_3#147]
## FEATURE REQUEST
- [ ] I would like to propose an additional mod.
- [x] I would like to propose a config change.
- [x] I would like to propose a custom recipe.
- [ ] I would like to propose another change.

## FEATURE INFORMATION
so lately a lot of people has been complaining about the combination crafting recipes,  some work and some not. so i would like to suggest that we get rid of the combination crafting and use the table crafting form the Extended Crafting mod, maybe switch recipes to the ultimate crafting table to make it more stable and doable
ty for all you r doing for us !! , lov u <3

**Comment by Mrbysco** [comment]
I quite like the current system that is in place.

**Comment by missatessatessy** [comment]
The current system in which people can't craft half the things?

**Comment by Mrbysco** [comment]
That was only due to the mod itself having a bug or one of the items he chose being ungettable.
It's not his fault that Ghast Statues weren't gettable. I didn't even know until I double checked it.

**Comment by xGarionx** [comment]
I wonder whos fault it was

**Comment by EmeraldCleaver77** [comment]
no ones fault , errors happen
