### ISSUE TITLE
nano beacon breaking

### ISSUE THREAD

**Issue by chevr057** [scalda/Foolcraft_3#148]
## Modpack Information
- [ ] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [x] In single player
     - [x] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
tier 4 and 5 nano beacons break instantly with empty hand in both single player and multiplayer server
does not give beacon back

## Reproduce Steps
place beacon on ground and left click to destroy

**Comment by scalda** [comment]
please update to 1.5 as there has been a lot of fixes in mods
