### ISSUE TITLE
Suggestion mod

### ISSUE THREAD

**Issue by flamingram** [scalda/Foolcraft_3#15]
hye there big fan of the the packs and was just wondering how about iron backpacks mod for a way to transport more stuff inventory
https://minecraft.curseforge.com/projects/iron-backpacks

**Comment by Mrbysco** [comment]
Couldn't you use the Themal Expansion Satchels? They're pretty muchs portable bags.

**Comment by flamingram** [comment]
yea but the iron backpacks are less buggy and have the ability to upgrade and retain there storage

**Comment by scalda** [comment]
We originally had this in the pack but with the satchel from TE, the ender pouch from ender storage, the golden bag of holding, and the alchemical bags from ProjectE we excluded the mod as it was just adding something that other mods provided
