### ISSUE TITLE
MegaLoot Axe on IE blocks

### ISSUE THREAD

**Issue by GamerXD8991** [scalda/Foolcraft_3#150]
when I try to break the immersive engeneering storgae crate or the threated planks WAILA shows "axe" in green but it takes the same time to break as if I'm using the hand. The Axe has mining speed 18.88 and Eff. V enchantment and works on Vanilla, BoP, Thaumcraft logs and planks just fine.

I'm using "Foolcraft 1.3.1 - reupload"

**Comment by scalda** [comment]
Sorry but 1 i can't reproduce this 2 you didn't fill out the form correctly
