### ISSUE TITLE
Recipe for crafting stone buttons back to block

### ISSUE THREAD

**Issue by Mntldisorder** [scalda/Foolcraft_3#151]
## FEATURE REQUEST
- [ ] I would like to propose an additional mod.
- [ ] I would like to propose a config change.
- [x] I would like to propose a custom recipe.
- [ ] I would like to propose another change.

So when crafting the Xtone tile in refined storage (or AE2) i end up crafting 2 or 3 stacks of stone buttons when i run out of slabs. It would be very handy to be able to craft those back to something, (cobble or gravel makes sense to me) because then i can at least use them if i want to. 

Thank you for building a awesome pack :)

**Comment by generrosity** [comment]
What are the steps to reproduce what you are doing?

**Comment by Mntldisorder** [comment]
well the recipe for the xtone tile needs smooth stone and smooth stone slabs to be made, and when you click to many times using RS or AE2 you end up crafting a bunch of stone buttons once you run of the slabs since stone buttons are made from stone blocks. another way would be to only make buttons out of andesite instead of smoothstone.

**Comment by scalda** [comment]
I'm not going to make a recipe to combat this sorry
