### ISSUE TITLE
Getting the wrong block when using the iron exchanger

### ISSUE THREAD

**Issue by Mntldisorder** [scalda/Foolcraft_3#152]
## Modpack Information
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [x] In single player
     - [ ] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
So when using the iron Exchanger on BoP overgrown stone and netherrack i get spectral moss, that i then can place and break with a pick to get endstone. Not the biggest issue perhaps but if nothing else it's annoying to not get the block i'm changing when they can't be crafted. 

## Reproduce Steps
Use the iron exchanger on overgrown stone or overgrown netherrack.

**Comment by scalda** [comment]
I have just tested this and all is fine, i can't duplicate what you are finding

**Comment by UltimateHM22** [comment]
I get this same issue
