### ISSUE TITLE
Extra Utilities 2 Manual Crashes The Game

### ISSUE THREAD

**Issue by piggyman156** [scalda/Foolcraft_3#153]
## Modpack Information
- [Yes ] I am running the latest version of FoolCraft
- [Yes ] I am running FoolCraft via Curse/Twitch Launcher
- [Yes ] I can reproduce this issue consistently
     - [Yes ] In single player
     - [ ] In multiplayer
- [It has been recently reported ] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [No] I am crashing and can provide my crash report(s)
- [I Have Not ] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
I crafted the book, and when I try to open it, the game crashes

**Comment by scalda** [comment]
Please report to relevant Mod Author
