### ISSUE TITLE
Flux Plug issued versio, Extreme Crafting broke again and extrem Spreading Pams Gardens gg

### ISSUE THREAD

**Issue by xGarionx** [scalda/Foolcraft_3#154]
## Modpack Information
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [x] In single player
     - [x] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [x] I am crashing and can provide my crash report(s)
- [x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
- Ghast Statues don't drop ,that makes the condenser Uncraftable again
- The increased growth rate let pam's garden reproduce like crazy to a speed amount that it basicly becomes and e-function and breaks any world in only a few hours with an amount of tile entities that no machine is able to hold up to it
- Flux Networks is outdated and constantly looses connection 

## Reproduce Steps
-play and test your modpack and version for once before you upload it...

**Comment by xGarionx** [comment]
Its simple really i wont search through 100+ issues on bad implementation that shouldnt have been there in the first place with the basic level of testing ,at least for something like end game recipes,  a problem that occured in one way or another in every version up until now. Its good you are testing things for once and overall i like the modpack, but be aware you screwed it up several times so angry reaction will be incomming. That beeing said i hope you find the root of the problems and the modpack gets the level of quality it deserves since it is really fun to play... .
Have a nice day.

**Comment by scalda** [comment]
All these issues have been fixed in 1.4 thanks for the issue

**Comment by xGarionx** [comment]
ok new issue : version 1.4 seems to be invisible...

**Comment by scalda** [comment]
That's because it's not released yet I had to ad 3 new mods today so it
needs testing
