### ISSUE TITLE
[ProjectE] Klein Star Drei recipe not working

### ISSUE THREAD

**Issue by Racerman2001** [scalda/Foolcraft_3#155]
## Modpack Information
- [x] I am running the latest version of FoolCraft
- [ ] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [x] In single player
     - [ ] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
When attempting to craft four Klein Star Zweis together to produce a Klein Star Drei, the recipe does not register 99% of the time.  I am using both standard crafting tables, the 2x2 crafting grid in the inventory, and EnderIO crafters, and only the Drei recipe seems to have issues.

## Reproduce Steps
1. get four Klein Star Zweis
2. attempt to combine them in any crafting interface in the recipe for a Drei.
## Additional Information
Imgur album displaying the issue: https://imgur.com/a/qjdg56r

**Comment by ExZha1337** [comment]
Hmm thats intresting. I've already made the gem armor. But when i crafted the klein stars i always use the bottom rights four crafting slots in a Refined Storage Crafting Grid. No clue if this is the reason it worked for me :/. Oh well, hopefully you get a response from the Scalda or smth :)

**Comment by scalda** [comment]
works fine in any slots 
![image](https://user-images.githubusercontent.com/1837979/42088829-d9e752c6-7b92-11e8-999b-6da9e166f211.png)
