### ISSUE TITLE
Multiplayer duping bug

### ISSUE THREAD

**Issue by Dazzah** [scalda/Foolcraft_3#156]
## Modpack Information
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [ ] In single player
     - [x] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
I was playing on my server with a friend, and he tried crafting at the bench I was using and after I crafted my item, the recipe disappeared but the item was still there. I did verify they were actual items.
From testing myself, when I accessed the table he was using, I could grab what he was crafting in the same sense. It appears tho that it doesn't change the recipe as he crafts.
For example, he was crafting something that involved iron, he started off with 2 pieces that make a pressure plate when I opened the table. The recipe didn't update as he crafted, so it only gave me the pressure plates.

The dupe will stop once the duped item is placed in your inventory, but you can keep duping if you click it out to throw it, or spam q

## Reproduce Steps
On multiplayer, get someone to craft something, and access the table while they have a valid recipe.
Only works w/o shift clicking

**Comment by scalda** [comment]
I am not sure on how to stop this, as i have not been able to reproduce it. It may be something to do with your server

**Comment by theBluebaerry** [comment]
We have been able to replicate this on our server also, I think it is something to do with the bench holding items. I will try to explain it a little better perhaps...
So if player one puts say 9 coal nuggets in the crafting table to get the crafting result of 1 coal, and  player two accesses that same table and takes out the 9 coal nuggets, then player one will still be able to see the 1 coal crafting result despite there being no coal nuggets in the crafting table to craft with. Player one can then hover over that one coal result and press Q resulting in coal being 'crafted' and spat out, without actually using items to craft them. 
I hope that makes sense :/
