### ISSUE TITLE
[AdvancedGenerators] Golden Turbines can't be crafted

### ISSUE THREAD

**Issue by MasterYinan** [scalda/Foolcraft_3#157]
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [x] In single player
     - [ ] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
Currently, you can'T craft Golden Turbines. Problem seems to be the Turbine fans which do appear in JEI but don't seem to have a crafting recipe, which means that you can't craft them.

**Comment by scalda** [comment]
This is due to there being no golden turbine blade in the mod. Please report it to the mod author.
