### ISSUE TITLE
Industrial Foregoing Rancher producing infinite milk

### ISSUE THREAD

**Issue by Chik3r** [scalda/Foolcraft_3#159]
## Modpack Information
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [ ] In single player
     - [x] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
I'm using the rancher from Industrial Foregoing and every second it milks every cow in its radius. I currently have 100,000 buckets of milk just from the rancher.

## Reproduce Steps
Place a Rancher and some cows in front, it will milk them every second. Also, provide energy to the rancher.

## Additional Information
My rancher has a tier 3 Range upgrade, and it's storing the milk in a Black Hole Tank
I'm playing on a localhost server, alone.

**Comment by kpeckett** [comment]
Vanilla cows are infinitely milkable with a bucket, it's only mini moos that have a cooldown - is the rancher supposed to add a cooldown to milking vanilla cows?

**Comment by Chik3r** [comment]
Ahh, I didn't know that vanilla cows were infinitely milkable
