### ISSUE TITLE
Blood Magic Mimic Blocks not mimicking Chisel Blocks correctly and Sentient Mimics not dropping correct Chisel block variant

### ISSUE THREAD

**Issue by Zelda-Swordsman** [scalda/Foolcraft_3#160]
## Modpack Information
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [x] In single player
     - [ ] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
When trying to disguise the Blood Magic mimic blocks using blocks from Chisel and Unlimited Chisel works, the block turns transparent, instead of taking on the texture.  The sentient mimic block does this before it comes alive. Once alive, it displays the texture with no issues, but drops a different chiseled variant of the block it was disguised as. Ex. I disguise a sentient mimic as factory block massive hexagonal plating, and receive when killed factory block rusty scaffold (transparent). The other mimic blocks have the correct drops.

## Reproduce Steps
Place a mimic block in the world and right click it with a block from Chisel or Unlimited Chisel Works. For the sentient, do the same step as above, wait for it to come alive then kill it.

## Additional Information
Seems to not effect blocks from other mods. Have not done a lot of testing on that front though.
https://imgur.com/a/1VoAkCw

**Comment by scalda** [comment]
have you reported this to the relevant mod authors?

**Comment by Zelda-Swordsman** [comment]
A bug report has been submitted to the blood magic issues page. Sorry for the late reply, life got in the way.
