### ISSUE TITLE
diamond nugget does not work with translocator

### ISSUE THREAD

**Issue by OldDragon2A** [scalda/Foolcraft_3#161]
## Modpack Information
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [x] In single player
     - [ ] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
Looks like extended crafting replaced the diamond nugget from translocators but the translocators configuration does not recognize it/use oredict. 

## Reproduce Steps
Right click a translocator with a diamond nugget.

## Additional Information
Looks like they ran into this issue with SevTech Ages as well back in May and updated the translocators configuration to recognize the extended crafting diamond nugget.

**Comment by scalda** [comment]
Please use the button shown in the image below to cycle through the different outputs of nuggets please

![image](https://user-images.githubusercontent.com/1837979/42088381-33b9e7de-7b91-11e8-94e1-e68aaeb627cd.png)

**Comment by OldDragon2A** [comment]
I had wondered what that button was for but I stopped paying attention to it since it seemed to always be disabled.  Thank you @scalda
