### ISSUE TITLE
Crash when entering a world

### ISSUE THREAD

**Issue by Ammolite** [scalda/Foolcraft_3#162]
## Modpack Information
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [x] In single player
     - [ ] In multiplayer
- [ ] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [x] I am crashing and can provide my crash report(s)
- [x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

Everytime i load a world it crashes, it didn't happen before i downloaded this mod

[crash-2017-07-23_20.00.53-client.txt](https://github.com/scalda/Foolcraft_3/files/2141523/crash-2017-07-23_20.00.53-client.txt)

**Comment by Mrbysco** [comment]
Foolcraft is not a mod. Also this issue has nothing to do with foolcraft

**Comment by Ammolite** [comment]
Oh, alright then, thanks!
