### ISSUE TITLE
Sever Is Fine With One Person, However When two or more are online, its unplayably laggy

### ISSUE THREAD

**Issue by ReWinD1** [scalda/Foolcraft_3#163]
## Modpack Information
- [x] I am running the latest version of FoolCraft
- [ ] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [ ] In single player
     - [x] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

**Comment by Mrbysco** [comment]
Please fill in the form

**Comment by ReWinD1** [comment]
Done

**Comment by generrosity** [comment]
Hey @ReWinD1 - you need to fill in the "details" of this. Provide some logs, how someone else can replicate it. Otherwise, it does sound like you have local server issues that is unrelated to the pack (such as RAM settings, cpu overloaded).

**Comment by scalda** [comment]
older then 2 months with no response from the OP so closeing
