### ISSUE TITLE
MegaLoot and Good o’ currency crash

### ISSUE THREAD

**Issue by Solousia** [scalda/Foolcraft_3#165]
## Modpack Information
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [x] In single player
     - [x] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [x] I am crashing and can provide my crash report(s)
- [x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
Place any mega loot item inside good o’ currency wallet crash client.

## Reproduce Steps
1. Get any mega loot item
2. Craft wallet from good o’ currency
3. Attempt to place the item inside the wallet

## Additional Information
Crash log:
https://pastebin.com/PLNuds5K

**Comment by scalda** [comment]
Please report to the mod authors so this can be fixed
