### ISSUE TITLE
Spongforge and veinminer

### ISSUE THREAD

**Issue by yamy19** [scalda/Foolcraft_3#166]
Yes I was just wondering if there was a way to disable xp orb drops from mining via veinminer since sponge and veinminer don't like to corroborate with each other.

We are on the latest version of both Foolcraft 3 and sponge forge

**Comment by Mrbysco** [comment]
Please don't remove the issue template.

**Comment by yamy19** [comment]
It never poped up

**Comment by yamy19** [comment]
And this is a question not an issue or request

**Comment by yamy19** [comment]
Scalda said to post commits here

**Comment by yamy19** [comment]
When you post via your phone there is no template

**Comment by Foolcraft3NZ** [comment]
I'm also interested in disabling xp orbs as I have the same issue. Thanks!

**Comment by scalda** [comment]
You would have to go and ask on the spongeforge forums as it is nothing that we have used/tested so this is at you own risk
