### ISSUE TITLE
[Crash on Client] net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Thermal Expansion (thermalexpansion)

### ISSUE THREAD

**Issue by digennnj** [scalda/Foolcraft_3#168]
## Modpack Information
- [x] I am running the latest version of FoolCraft
- [ x] I am running FoolCraft via Curse/Twitch Launcher
- [ x] I can reproduce this issue consistently
     - [ ] In single player
     - [x ] In multiplayer
- [ x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ x] I am crashing and can provide my crash report(s)
- [ x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
I'm trying to run a dedicated FoolCraft server on my ubuntu 18.04 Desktop. I downloaded the server files on to my windows desktop and transferred them over to the Ubuntu desktop. The server fires up just fine, and detects my client joining, but the client side crashes immediately after signing into the server giving the error...

_Internal Exception:
com.google.common.util.concurrent.UncheckedExecutionException:
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Thermal Expansion (thermalexpansion)_

To narrow down the possible problems, my dedicated server does work for a vanilla Minecraft server. In other words, I have successfully port forwarded the server through my hardware so there is not an issue there. Also, the server download matches the version information (Forge 2705 and FoolCraft 1.3.1 reupload) for the FoolCraft version I'm launching through Twitch app.

## Reproduce Steps
This can be reproduced by:
-Starting server on Ubuntu 18.04 Desktop
-Launching FoolCraft 3 on the Twitch app
-Attempting a direct connect to the server.

## Additional Information

Latest Log Data: https://pastebin.com/AzdP6DxX 
Debug Log Data Part 1: https://pastebin.com/4SZ01K3x
Debug Log Data Part 2: https://pastebin.com/HLf2EXQx
(At the end of Debug Log Part 2 , you can see where I successfully connect, but then disconnect for seemingly no reason because there are no errors on the server side. My MC username is NickBigD35 lol.)

**Comment by generrosity** [comment]
Doesn't sound like a server problem (you could confirm by connecting to an open FC3 server on the internet). Those logs are for the server only? Do you have the logs for the client instead? Initial suggestion would be a fresh install of a Curse profile for FC3

**Comment by digennnj** [comment]
I think I've narrowed it down to Forge not properly installing on Ubuntu. Is there a bug tracker I can report on for Forge?

**Comment by generrosity** [comment]
Yes, I would suggest searching for it via Google as there might be a few already logged for very similar things you are having issues with (although the two I looked at didn't mention Linux)

**Comment by digennnj** [comment]
Yeah I've looked and not much is reported on for Linux errors, that's why I came here. But thanks for your response! I'll keep looking and I'll try and post those client logs to see if those can tell you anything

**Comment by scalda** [comment]
hi sorry for your problems, when i run on linux i am normally using a game panel of some sort for it. sorry we couldn't help you more
