### ISSUE TITLE
[ModSugestion] Custom Discord RPC

### ISSUE THREAD

**Issue by jaideepheer** [scalda/Foolcraft_3#169]
## FEATURE REQUEST
- [x] I would like to propose an additional mod.
- [ ] I would like to propose a config change.
- [ ] I would like to propose a custom recipe.
- [ ] I would like to propose another change.

## MOD INFORMATION

I have a simple mod.

It allows you to have custom Discord Rich Presence behavior and is configurable using a JSON file in the config folder.

You can have fully customized text and images(using your custom `Discord APP ID`).

Not just this, it uses a profile system that allows you to define different profiles which are triggered by game events like `PRE_INIT`, `SERVER_STARTING`, `MAIN_MENU_REACHED` etc.

~~Also, I have been working on providing custom JS execution before each Rich Presence update to allow using dynamic data like PlayerName, DeathCount, WorldName, etc. I'll probably get it done in 2days.~~ 

Its done. 😎 There is javascript support.

## Config/Script Details
* Link: [Custom DiscordRPC GitHub Page](https://github.com/jaideepheer/MinecraftForge-custom_discordRPC/tree/master#custom-discordrpc) (with documentation)

## Mod Details
* Name: Custom Discord RPC
* CurseForge Link: [https://minecraft.curseforge.com/projects/custom-discordrpc](https://minecraft.curseforge.com/projects/custom-discordrpc)

**Comment by scalda** [comment]
this would be great but iskall hasn't gone for it sorry
