### ISSUE TITLE
Mini Moos

### ISSUE THREAD

**Issue by WyvernTime** [scalda/Foolcraft_3#17]
While exploring in Survival, the only "fluid" producing mini moos i can find are water mini moos, the rest are costume moos and those type. In a birch forest, there was a lot of mini moos, only water mini moos though.

**Comment by Mrbysco** [comment]
That's because Mini Moo's changed massively. You now convert the base moo "Water Moo" into other fluids by feeding them a liquid bucket but be careful as it doesn't have a 100% success rate

**Comment by scalda** [comment]
go see here https://www.reddit.com/r/Foolcraft/comments/8kvll5/foolcraft_3_minimoo_reference_guide/
