### ISSUE TITLE
Refined Avaritia...but no Avaritia?

### ISSUE THREAD

**Issue by notWaterGuy12** [scalda/Foolcraft_3#170]
## FEATURE REQUEST
- [x] I would like to propose an additional mod.
- [ ] I would like to propose a config change.
- [ ] I would like to propose a custom recipe.
- [ ] I would like to propose another change.

## MOD INFORMATION
Avaritia https://minecraft.curseforge.com/projects/avaritia

**Comment by kpeckett** [comment]
Refined Avaritia works with Extended Crafting, which is why it is still in the pack after the developers replaced Avaritia with EC.

**Comment by scalda** [comment]
what @itskieranp said
