### ISSUE TITLE
Game Crashes to launcher after typing '@' into any refined storage grid or even the wireless grid. (Creates no crash reports)

### ISSUE THREAD

**Issue by Ceyphe** [scalda/Foolcraft_3#174]
## Modpack Information
- [x ] I am running the latest version of FoolCraft
- [ x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [x ] In single player
     - [ ] In multiplayer
- [ x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description

When I enter the world and attempt to type '@' into any refined storage grid or the wireless grids, it simply freezes and eventually crashes. It started doing this today, but i have had no issues before now.

## Reproduce Steps

1. Enter world.
2. type in '@' into any refined storage Grid or the wireless gird.
3. Game freezes.
4. Eventually, the Game crashes, yielding no crash reports.

**Comment by kpeckett** [comment]
Are you able to send a pastebin link of the game log from Foolcraft 3 Folder > "logs" > "latest.log"?

**Comment by MrTreo77** [comment]
I have the exact same issue. This seems to happen when there are a lot of items going in and out of the refined storage system (3 tier 6 void miners working with full speed upgrades). Don't remember having this issue before the last update.

**Comment by scalda** [comment]
update to Beat 1.5 and test, Please report back and close the issue if it's solved. i will close in 7 days if not responded to or not closed before hand
