### ISSUE TITLE
starmetal ore not crafting 

### ISSUE THREAD

**Issue by sreekrishna5** [scalda/Foolcraft_3#175]
## Modpack Information
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [ ] I can reproduce this issue consistently
     - [x] In single player
     - [ ] In multiplayer
- [ ] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

**Comment by sreekrishna5** [comment]
![2018-07-06_23 06 11](https://user-images.githubusercontent.com/40898266/42392714-5c43a86c-8171-11e8-8523-d7125cb5449a.png)

**Comment by Solousia** [comment]
Need sky light access
