### ISSUE TITLE
Multiple CTD with in 24 hrs w/ Report (SSP)

### ISSUE THREAD

**Issue by JTKillien** [scalda/Foolcraft_3#176]
## Modpack Information
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [x] In single player
     - [ ] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [x] I am crashing and can provide my crash report(s)
- [ ] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
Since yesterday evening I have experienced 3 complete crash to desktop with the same crash report/log. After playing for about an hour the game suddenly hits a lag spike then stops responding, after a screen flashes as if the game is working again it closes and opens the launcher with crash report.

## Reproduce Steps
The crash in my game occurs by simply playing for and hour or more. (Edited)

## Additional Information
Crash Report https://pastebin.com/WexxBSNz
I have disabled Better Folliage, and added JEHC and Optifine. Aside from that the modpack is unaltered. Any help with this issue would be appreciated. Thank you.

**Comment by JTKillien** [comment]
4th Crash second published report. https://pastebin.com/58sqUCwS

**Comment by Solousia** [comment]
What I notice is my game start to crash after I add Optifine, probably something to do with it. Try use the betterFPS mod rather than optifine.

**Comment by Mrbysco** [comment]
I don't think Optifine would touch sound but try without or try updating optifine to the latest release.

**Comment by JTKillien** [comment]
Okay, not sure if this has anything to do with the same issue, but after updating the Modpack to 1.4 and removing/updating (tried both) Optifine the client now crashes upon loading the world. Crash log can be found  here https://pastebin.com/QGepgEZp

**Comment by JTKillien** [comment]
I am removing my updated comment and posting to its own thread as I have found it to be a separate issue.

**Comment by JTKillien** [comment]
The Sound Handler crash seems to have been resolved either by reinstalling Java or updating Optifine, both I have done since last evening. With that I am going to close the issue and bid thanks for the help.
