### ISSUE TITLE
Items losing Thaumcraft Aspects

### ISSUE THREAD

**Issue by gloomyMoron** [scalda/Foolcraft_3#177]
## Modpack Information
~~- [x] I am running the latest version of FoolCraft~~
~~- [x] I am running FoolCraft via Curse/Twitch Launcher~~
~~- [x] I can reproduce this issue consistently~~
     ~~- [x] In single player~~
     ~~- [ ] In multiplayer~~
~~- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.~~
~~- [ ] I am crashing and can provide my crash report(s)~~
~~- [ ] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]~~

## Issue Description
~~After updating to 1.4.4, Coal no longer has any Thaumcraft Aspects tied to it (presumably other items were affected as well).~~

## Reproduce Steps
~~Update to 1.4.4 from 1.3.1~~
~~Load world~~
~~Aspects go missing from items~~

## Additional Information
~~After updating to 1.4.4 and loading up my world, I noticed that coal has lost its thaumcraft aspects. I believe other items have been affected as well (such as Alchemical Coal, which I could have sworn had aspects previously). Interestingly enough, Coal Ore still have their aspects but Coal and Coal Blocks do not.~~

~~I have added mods to the pack, but these were all added in 1.3.1 and coal still had its aspect then and they shouldn't really interfere with recipes. ~~

~~I have added Hooked (and its required library, Librarian), Schematica (and its required library, LunatriusCore), and Just Enough HarvestCraft (to integrate HarvestCraft presser, market, grinder, and shipping bin into JEI).~~

~~Images:~~
~~https://imgur.com/a/ohkEJ2O~~

**EDIT:** I think I'm just an idiot. I think coal never had any aspects in 1.3.1 either, which I assume was intentional or known.

**Comment by scalda** [comment]
no response in a month so closing
