### ISSUE TITLE
Game Crash and Corrupted World Save From Placing Adjacent Redstone Torches!!!

### ISSUE THREAD

**Issue by Draqings** [scalda/Foolcraft_3#178]
## Modpack Information
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [x] In single player
     - [ ] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [x] I am crashing and can provide my crash report(s)
- [x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
If you place two redstone torches on two adjacent blocks (both walls of a corner), I'm not sure what mod allows this behavior, they disappear. Then if you break either block the torches were on the game crashes and will crash every time you start the world.

## Reproduce Steps
1 Create New World
2 Place two blocks diagonally from each other touching corners.
3 On the first block placed put a redstone torch on the face above the block that both blocks share.
4 Place a torch on the other block on the same face over the shared block.
5 Notice the disappearing torches.
6 Break either block that was placed.
Tadaa game over
7 Try to relaunch world
Crash again

## Additional Information
[Crash Log One](https://pastebin.com/edjPjzre)
[Crash Log Two](https://pastebin.com/jBKDjEwM)
Both from the same session. I'm not sure why there's two reports.

If there is any way to recover a file after this please let me know.

**Comment by scalda** [comment]
this is an issue with translocators and forge multipart best thing to do is to disable them both reload the world and then re add them

**Comment by Draqings** [comment]
How do I disable these mods?

**Comment by scalda** [comment]
update to Beat 1.5 and test, Please report back and close the issue if it's solved. i will close in 7 days if not responded to or not closed before hand
