### ISSUE TITLE
Game Crash when Foundry alloy furnace placed in range of Botania exoflame

### ISSUE THREAD

**Issue by squidfeatures** [scalda/Foolcraft_3#179]
## Modpack Information
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [x] In single player
     - [ ] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [x] I am crashing and can provide my crash report(s)
- [x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
Placing an Foundry alloy furnace within the effective range of a Botania exoflame flower crashes the game.

## Reproduce Steps
1. Place down exoflame (on dirt or grass). Does not need mana pool.
2. Place down alloy furnace within 5 blocks of exoflame.
Order doesn't matter, you can place alloy furnace first, then exoflame, crash still occurs

## Additional Information
Crash Report: https://pastebin.com/7S9P5FMA
I installed optifine, but otherwise the modpack is unchanged.

**Comment by Solousia** [comment]
I think it relate to botania, why don’t you also post it to botania github

**Comment by scalda** [comment]
update to Beat 1.5 and test, Please report back and close the issue if it's solved. i will close in 7 days if not responded to or not closed before hand

**Comment by squidfeatures** [comment]
I was able to reproduce using the steps above on Beta 1.5

**Comment by scalda** [comment]
https://github.com/Vazkii/Botania/issues/2699

https://github.com/Shadows-of-Fire/Foundry/issues/34

**Comment by scalda** [comment]
ok i have reported to both mod authors
