### ISSUE TITLE
astral sorcery horoligum ritual not working

### ISSUE THREAD

**Issue by sreekrishna5** [scalda/Foolcraft_3#180]
## Modpack Information
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [ ] I can reproduce this issue consistently
     - [x] In single player
     - [ ] In multiplayer
- [ ] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

**Comment by sreekrishna5** [comment]
![2018-07-07_23 49 37](https://user-images.githubusercontent.com/40898266/42413548-7e6c127e-8240-11e8-95e8-74629ee9f948.png)
![Uploading 2018-07-07_23.49.49.png…]()

**Comment by scalda** [comment]
update to Beat 1.5 and test, Please report back and close the issue if it's solved. i will close in 7 days if not responded to or not closed before hand
