### ISSUE TITLE
Shulkerbox Duplication Bug

### ISSUE THREAD

**Issue by SgtPhyko** [scalda/Foolcraft_3#183]
## Modpack Information
- [x] I am running the latest version of FoolCraft, Herkules Server
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [ ] In single player
     - [x] In multiplayer
- [1] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

When using a Autobreaker(AA) to break the shulker box it will collect a shulkerbox (without content - so no NBT) and drop the actual shulkerbox (with NBT) somewhere around on the floor - looping this with any autoplacer will make a very fast shulkerbox duplicator.

autobreacker facing up shulkerbox ontop - pretty simple

## Additional Information
https://imgur.com/a/gietr7L

**Comment by scalda** [comment]
Looks like a issue that needs report to the mod author so please repor this to actually additions mod author and reference this page.
