### ISSUE TITLE
Hat Trading Not Working ?

### ISSUE THREAD

**Issue by thewismit** [scalda/Foolcraft_3#184]
## Modpack Information
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [ ] In single player
     - [x] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
My son and I are unable to trade single or multiple hats because we cannot toggle the "Not ready to trade" buttons. We've tried getting as close to each other as possible.

## Reproduce Steps
I'm not sure other than to do what I described in the issue description

## Additional Information
Thank you!

**Comment by scalda** [comment]
I am not sure what to suggest sort it's not a function i know much about. i would go and see if anything has been posted in regards to this on the hats issue page
