### ISSUE TITLE
Mob Mashers Sometimes Freezing the Game

### ISSUE THREAD

**Issue by nightstick24** [scalda/Foolcraft_3#185]
## Modpack Information
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [ ] I can reproduce this issue consistently
     - [ ] In single player
     - [ ] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
Mobs freeze, inventories don't open, blocks break but don't drop, and game doesn't save. But animated blocks still move and WAILA updates. Appears to be from the Mob Masher, from mob grinding utils.

## Reproduce Steps
Use some mob mashers to kill mobs, something happens eventually and your game will freeze up like mentioned above.

## Additional Information
Once your game freezes due to this once, it'll freeze you every time you try to load up your world as soon as the world loads. Deleting the mob mashers via something like McEdit seems to be the only way to fix it.

I'm not sure what exactly causes it, as I've used them for a couple days without issue then all of a sudden it happens two or three times in a row. There's no crash log or logs relating to it, that I can find. Every time it happens there's been mobs on the mashers getting killed. I suspect it's something to do with loading/unloading the chunk at bad times, or saving the game at bad times, or something like that.

I'm reporting this over at mob grinding utils as well, just wanted to drop this here so people who have the issue can know how to fix it!

**Comment by scalda** [comment]
update to Beat 1.5 and test, Please report back and close the issue if it's solved. i will close in 7 days if not responded to or not closed before hand

**Comment by scalda** [comment]
closing as no response so assume all is good
