### ISSUE TITLE
Can't craft Marimorphosis from Botania

### ISSUE THREAD

**Issue by nouille07** [scalda/Foolcraft_3#186]
## Modpack Information
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [x] In single player
     - [x] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
I cannot craft the marimorphosis following the recipe given by the lexica botania and JEI returns no recipe, I tried the recipe with just the same version of botania installed and it works fine.

## Reproduce Steps
one could say that the problem is a lack of step, put the correct items in the petal apothecary and nothing happen.

## Additional Information
plz fix give me my ugly green blocks back ♥

**Comment by scalda** [comment]
this recipe is disabled as it causes world crashes there are custom recipes for the blocks
