### ISSUE TITLE
Crashing when having chiseled reinforced stone in my inventory.

### ISSUE THREAD

**Issue by UltimateHM22** [scalda/Foolcraft_3#188]
## Modpack Information
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [ ] In single player
     - [x] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [x] I am crashing and can provide my crash report(s)
- [x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
When ever I put any type of chiseled reinforced stone into my inventory, whether it is painted onto a block or the actual block, my game will crash and will not give a reason.

## Reproduce Steps
Put any type of chiseled reinforced stone into your inventory.

## Additional Information
I am an operator on a multiplayer server using Minecraft-hosting.pro

**Comment by scalda** [comment]
update to Beat 1.5 and test, Please report back and close the issue if it's solved. i will close in 7 days if not responded to or not closed before hand
