### ISSUE TITLE
Old project E recipes

### ISSUE THREAD

**Issue by liampearson96** [scalda/Foolcraft_3#189]
## Modpack Information

Spongeforge 
a few other none recipe conflicting plugins 

## Issue Description
Server files use old recipes to craft project e Items

## Reproduce Steps
by using the old recipes to create the items

https://imgur.com/2WgP7jo

**Comment by Mrbysco** [comment]
Please fill in the modpack version. 
![afbeelding](https://user-images.githubusercontent.com/9308260/42528251-2f81a4d4-847b-11e8-9d48-60714de279e9.png)

**Comment by Mrbysco** [comment]
Also we are not responsible if SpongeForge is breaking things.
Have you tried out the server files in normal forge server and tested the same recipes?

**Comment by liampearson96** [comment]
I have just tried without sponge, this is indeed the problem and i apologise. If any, do you have any advice or ways to fix this? thank you

**Comment by Mrbysco** [comment]
Not really. If Sponge breaks CraftTweaker there's not much we can do.

**Comment by yamy19** [comment]
i can verify that sponge does not break crafttweaker

**Comment by nzminecraftDOTcom** [comment]
Hi, I run a server, haven't updated yet and won't be updating until someone who is an official (Mrbysco you seem official on here) can prove it is functioning as it should do, with the extended crafting recipe. Thanks. Can't have people making millions of condensers for next to nothing in terms of effort.

**Comment by nzminecraftDOTcom** [comment]
Can confirm the recipe works just fine in multiplayer WITH spongeforge running.
