### ISSUE TITLE
Transmutation table recipe

### ISSUE THREAD

**Issue by foxanthony1** [scalda/Foolcraft_3#19]
The recipe for the ProjectE transmutation table is far too easy.

There's clearly some confusion about how ProjectE works:

The energy condensers are mostly used for collecting EMC, e.g. piping a cobblestone generator into it. The transmutation table is really the primary item in the mod - it's what most people use on a day to day basis and is usually the first item people try to get in the mod.

If you really want to gate the mod both the energy condenser and the transmutation table recipes need to be changed - not just the energy condenser.

That being said, there are other ways of implementing the mod instead of "the last item you make before you quit the pack". It could be configured to only work with certain items, like building blocks, or food, or... whatever.

**Comment by Yadokingu** [comment]
The transmutation table requires an energy condenser in its recipe.

**Comment by foxanthony1** [comment]
The recipe hasn't been changed in the released version.

**Comment by scalda** [comment]
@foxanthony1 your pack must not be installed correctly as ProjectE is gated with a combination crafting recipe that requires some mid/top tier items from a bunch of mods in the pack along with 50M RF

![image](https://user-images.githubusercontent.com/1837979/40474058-e09bba22-5f35-11e8-88fd-dba0b661d6fd.png)

That is just 1 of 4 recipes

**Comment by foxanthony1** [comment]
Sorry. I removed chance cubes and the currency mod and that broke recipes.zs.
