### ISSUE TITLE
Killing GoldenMoo with MrCrayfish pistol/splash potion of death = Game crash

### ISSUE THREAD

**Issue by SirDizarm** [scalda/Foolcraft_3#190]
## Issue Description
Spawn in goldenmoo with spawnegg, give player pistol from MrCrayfish mod. Kill moo with it result in game crash (crash to desktop). 
Killing the golden moo with instant potion of death result in game crash. 

Tried to kill with sword with no crash.

## Reproduce Steps
Same as above

## Additional Information
https://pastebin.com/tRLe9U0Q with pistol
https://pastebin.com/ChMxR2rV with splash potion of instant death

**Comment by Mrbysco** [comment]
Please fill in the pack version.
Also try obtaining the crash log and putting it on Pastebin.

**Comment by SirDizarm** [comment]
I spawned in all other Moo cows with nothing happening, only the Golden Moo result in gamecrash.

**Comment by Mrbysco** [comment]
This issue points to Extra Utilities being the culprit

**Comment by SirDizarm** [comment]
Oh how strange

**Comment by scalda** [comment]
update to Beat 1.5 and test, Please report back and close the issue if it's solved. i will close in 7 days if not responded to or not closed before hand
