### ISSUE TITLE
Crash because of loading chucks

### ISSUE THREAD

**Issue by ghost** [scalda/Foolcraft_3#191]
## Issue Description
The game crashed whilst batching chunks
Error: java.lang.OutOfMemoryError: Direct buffer memory

## Reproduce Steps
Play in a general area for relatively long then move to somewhere else and occasionally the game will freeze for about 3 seconds and then crash

## Additional Information
https://pastebin.com/jp1Qe5qm

**Comment by Flummi** [comment]
>Memory: 1061290096 bytes (1012 MB) / 2829582336 bytes (2698 MB) up to 2863661056 bytes (2731 MB)

you need at least 6gb Ram to play fc3 properly.
https://www.curseforge.com/minecraft/modpacks/foolcraft-3

**Comment by ghost** [comment]
You're right! I thought I changed it to 6gb, I don't know why it defaults to 3gb.
