### ISSUE TITLE
[server] Equivalent Energistics (existing items cause instant hard crash)

### ISSUE THREAD

**Issue by nzminecraftDOTcom** [scalda/Foolcraft_3#193]
## Issue Description
Server instantly crashes when a chunk is loaded with some item from Equivalent energistics. Removing this mod stops the crashes, and players can still play as if there was no change (no client modification necessary)

## Reproduce Steps
N/A

 https://pastebin.com/jA5kU88S

## Additional Information
Modified server files to make it more "efficient"
Server is running spongeforge-1.12.2-2705-7.1.0-BETA-3206 (Not related to crashes)
FC3 V1.4.5

**Comment by itskdog** [comment]
Which pack version is this?
What specific modifications were made?
Does it work on a regular forge server?

**Comment by nzminecraftDOTcom** [comment]
Version 1.4.5 (This should be a requirement in the "form" thing above)
General config changes from the original pack "modifications" 
The crash is not sponge related, as i have already stated above. 
The crash is caused by an item being in game from previous versions of the world before the update was carried out. The items conflict somewhere along the line when a player logs in and the server dies.

**Comment by itskdog** [comment]
(I'll leave the rest up to Scalda and the team, but just wanted to note that the form does ask for the version number)

**Comment by nzminecraftDOTcom** [comment]
Sorry, missed that one. So many things in there that are not related to the text you actually want to see making it very jumbled for easy filling out.

**Comment by nzminecraftDOTcom** [comment]
Reverted back to 1.3.1 where this crash didn't occur. Will return to 1.4.5 when bugs are ironed out.

Edit: Woops, this comment is for another issue, thought i was commenting on that one. Ignore this.

**Comment by scalda** [comment]
I am already aware of this disabling the mod and loading up the world fixes the issue then you can readd the mod

**Comment by scalda** [comment]
update to Beat 1.5 and test, Please report back and close the issue if it's solved. i will close in 7 days if not responded to or not closed before hand
