### ISSUE TITLE
Server stalls 

### ISSUE THREAD

**Issue by liampearson96** [scalda/Foolcraft_3#194]
## Issue Description
Our server randomly stalls and times everyone out who was on the server for no apparent reason (to me anyway i may be wrong)

## Reproduce Steps
The server randomly does it

 

## Additional Information

https://imgur.com/b1Ia7Kg
https://pastebin.com/2fhnFyWE
Any help is welcomed
Thank you

**Comment by avidgamer5918** [comment]
i am having the same issue since we upgraded to 1.4.5

**Comment by nzminecraftDOTcom** [comment]
Are you running anything other than the server pack that is provided? 

I have this issue with Veinminer and Spongeforge, where someone will veinmine a large chunk of coal or redstone and the XP orbs duplicate ten fold and end up hanging the server. Turning off veinminer has solved this hang issue.

**Comment by liampearson96** [comment]
We’ve had it stall because of two things, veinminer like you’ve said and because of mob_grinding_utils mob mashers. We have spongeforge installed and a few other plugins

**Comment by nzminecraftDOTcom** [comment]
Set veinminer configs:
Blocklimit = 0
Radius = 0
per_tick = 0

See if that solves it
You can do it ingame without having to reboot the server
/veinminer should bring up a list of options and those i said above should be in there. (need to be OP or have veinminer.* permissions if using a permissions plugin)

**Comment by liampearson96** [comment]
nzminecraft i have tried removing certain blocks from the blocklist for example redstone ore, coal ore ect and it just defaults to the original config and sets them back to active unless im doing it wrong. I ran this command /veinminer blocklist pickaxe remove minecraft:coal_ore

**Comment by yamy19** [comment]
Yes the block blacklist does not work on veinminer

**Comment by yamy19** [comment]
This is the reason we requested to have it replaced with ore excavator but scalda denied it even though it would fix an issue that he is having as well

**Comment by yamy19** [comment]
I am the Dev for nzmincraft's server

**Comment by nzminecraftDOTcom** [comment]
Yeah, as yamy said, veinminer has no BLACKlist, it has a BLOCKlist which says what blocks a tool is able to "veinmine" e.g an axe shouldn't be able to mine OR veinmine coal ore, but if you add coal_ore to the blocklist under "axe" tools, it should (however don't quote me on this i think it still reverts back to default config) 

Try as I said with the commands and do it from in game, it should turn veinminer off.
