### ISSUE TITLE
Waystone inventory  and dropped item texture not rendering

### ISSUE THREAD

**Issue by benhavo** [scalda/Foolcraft_3#195]
## Issue Description
When I break a waystone, the dropped item has a shadow, but no rendered texture. There is no texture rendered in JEI for the waystone.

## Additional Information
I am on a Mac OSX 10.13.4, and in the past, some mods have had issues rendering on Macs. This has always been solved, in my experience, with a texture reload (F3+T) after loading the world. This has not solved my issue thus far. I do use Optifine, but I uninstalled to see if the issue was solved, and it was not.

**Comment by itskdog** [comment]
You see to have missed the pack version in your report. Which version of Foolcraft are you using?

**Comment by benhavo** [comment]
it is occurring on both 1.4.4 and 1.4.5. It was working fine in 1.0, 1.1 and 1.3.1, but when I updated to 1.4.4 (download via twitch launcher and copy folder to MiltiMC instance) the issue started. I updated to 1.4.5 and the issue persists

**Comment by benhavo** [comment]
I reinstalled version 1.4.5 and the texture is now rendering properly.
