### ISSUE TITLE
Unknown cause for crash upon entering world.

### ISSUE THREAD

**Issue by Ceyphe** [scalda/Foolcraft_3#196]
## Issue Description

I was just playing and building (using basalt if that helps) and suddenly I crashed, and now ehenebver i enter the world it instantly crashes.

## Reproduce Steps

1. enter world
2,crash

https://pastebin.com/AxuHjRn5

**Comment by itskdog** [comment]
Please can you fill in the pack version. Also, as you stated that you have altered the modpack, what things have you changed?

**Comment by Ceyphe** [comment]
Sorry, i must have missed those two fields. I have not altered the Pack in any way.

**Comment by nzminecraftDOTcom** [comment]
Check your client crash report. It might tell you if there is a "ticking player" issue, and it might give you coords of a block that you can use a world editor to remove. If multiplayer, you can get a server admin to use world edit or the likes to set that block to air.

Edit: Just saw pastebin

Your problem is at (-1017,70,96) in your world, delete that block and it should fix your issue.

**Comment by Ceyphe** [comment]
I've been trying for the past hour or so to use MCedit 2.0 to remove the block, but i can't figure out how to select the block and then delete it. When I select the block the delete button is greyed out, so I can't delete it... as if I haven't actually selected it? Does anyone know how MCedit 2.0 Works? Thanks!

**Comment by nzminecraftDOTcom** [comment]
You can use a program called NBTExplorer to edit the map manually.
https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-tools/1262665-nbtexplorer-nbt-editor-for-windows-and-mac

Close Minecraft first
You want to go into the world save file, find the regions folder, and find region r.-2.0.mca
Use the above program to open up the file (drag it ontop of it's icon on your desktop when installed)
Navigate to chunk (-64, 6)
Expand that section.
Sub-sections should appear. Start at the bottom of those, and expand them until you see one where the block location is at -1017 70 96
Delete that expanded entry. 
Save
Try start your game.

**Comment by Ceyphe** [comment]
I've followed your instructions, but when i come to the file containing the entries for the different tile entities, there is no entry with those coordinates. Are you sure it is this exact location? because there is an entry for -1019 77 98 or --1019 77 96 etc, but none of that exact coordinate. Any ideas? Thank you all for the help btw. 🙇

**Comment by nzminecraftDOTcom** [comment]
Would you be able to upload the region file to dropbox etc and post the link here?

**Comment by Ceyphe** [comment]
[https://drive.google.com/open?id=1Dc2lDXp7GNistzYVl5xCQLPRgBfGLaQC](url)

**Comment by nzminecraftDOTcom** [comment]
That is odd. Perhaps your playing around in MCEdit removed it. You could try creating a copy of the region file and deleting the -64,6 chunk and placing that edited region file back in your game (You will lose whatever is in that chunk, hence the backup) see if that fixes it.

**Comment by Ceyphe** [comment]
It worked! Now all I have to do is full in the missing chunk of my base. Thank you so much for the help!!!
