### ISSUE TITLE
Equivalent Energistics / AE2 / ProjectE wonky integration.

### ISSUE THREAD

**Issue by leon-strong** [scalda/Foolcraft_3#197]
## Modpack Information

After upgrading from a previous version, 1.3.1 to 1.4.5 i get a server crash.

https://pastebin.com/acQxvBP2

## Reproduce Steps
1) Upgrade Server files
2) Start Server

## Additional Information
I had enabled ftbutils chunkloading on 1.3.1

**Comment by leon-strong** [comment]
Logging mostly to let you know, it may be EE that's the cause : https://github.com/Mordenkainen/EquivalentEnergistics/issues/98 seems to point that way.

**Comment by nzminecraftDOTcom** [comment]
I removed that mod, server runs fine without it.

**Comment by scalda** [comment]
yeah looks to be that project e and AE2 have both updated and EE is still behind the times. I have been removing the mod reloading the world to clear it from the world and then readding it

**Comment by scalda** [comment]
update to Beat 1.5 and test, Please report back and close the issue if it's solved. i will close in 7 days if not responded to or not closed before hand

**Comment by yamy19** [comment]
how can we update to 1.5 when ther is no server pack out
