### ISSUE TITLE
Game will not load

### ISSUE THREAD

**Issue by ggosaokirito** [scalda/Foolcraft_3#198]
## Additional Information

when I was in the end fighting the end dragon and after I killed him I got his stuff then I saw a chance cube so I went to open it and after I did the game just crash and now it will not load foolcaft at all it say the game crashes every time load my world

The game version is14.23.4.2705

[19xzPKKc.txt](https://github.com/scalda/Foolcraft_3/files/2193615/19xzPKKc.txt)

**Comment by Mrbysco** [comment]
You forgot to fill in the current pack version.
![afbeelding](https://user-images.githubusercontent.com/9308260/42704785-79aa62f0-86d1-11e8-8326-8c01e6a71640.png)

also could you supply us with a crashlog. Preferably in the form of a pastebin link.

**Comment by ggosaokirito** [comment]
ok I put the game version in the crash long too

**Comment by Mrbysco** [comment]
InventoryPets seem to be crashing you

**Comment by ggosaokirito** [comment]
ok so how do I fix it

**Comment by ggosaokirito** [comment]
thx for the help I just took inventorypets out of the game and now it wok fine

**Comment by scalda** [comment]
update to Beat 1.5 and test, Please report back and close the issue if it's solved. i will close in 7 days if not responded to or not closed before hand
