### ISSUE TITLE
[Suggestion/Request] VanillaFix

### ISSUE THREAD

**Issue by ZombieHDGaming** [scalda/Foolcraft_3#199]
## FEATURE REQUEST
- [x] I would like to propose an additional mod.
- [ ] I would like to propose a config change.
- [ ] I would like to propose a custom recipe.
- [ ] I would like to propose another change.

## FEATURE INFORMATION
The mod called VanillaFix offers many improvements for many vanilla bugs and offers optimizations that can lead to huge FPS increases and (in the next update) huge RAM usage decreases. I have not personally tested it in Foolcraft 3, but I do feel what it offers would be a great addition to the modpack.

## MOD INFORMATION
VanillaFix
CurseForge: https://minecraft.curseforge.com/projects/vanillafix
GitHub: https://github.com/DimensionalDevelopment/VanillaFix
Discord (Should you have questions that the CF page doesn't answer): https://discord.gg/f27hdrM

P.S. This may seem like shameless advertising since I work on the mod, but it is a great mod and would definitely be helpful to anyone that uses it.
P.P.S. You guys need to change a line in the suggestion format, it seems the line above feature information doesn't have an ending tag and cuts off that section if it's not added.

**Comment by nzminecraftDOTcom** [comment]
Is this mod capable of being used server-side only? I am interested.

**Comment by ZombieHDGaming** [comment]
Should be, but it doesn't really do many fixes on the server side of things. Its more recommended for clients among other things, but yes, it should work server side only.

**Comment by nzminecraftDOTcom** [comment]
Darn. I'm having an issue with EnderIO conduits of types and the server crashes an hour after start-up every time and the crash report points to them, was hoping this may be able to solve some issues.

**Comment by icesmurf** [comment]
I've been using this client side on my laptop for a while, helps alot no issues.

**Comment by TheMajesticPickle** [comment]
VanillaFix actually makes load time slower and what tends to happen when you join a singleplayer world is if you don't join immediately after the game loads, you'll "time out." at least, that's what it tells you. better to run without.

**Comment by ZombieHDGaming** [comment]
@TheMajesticPickle Can you give a little more detail on this? Because no one has ever had that kind of issue reported it to us (GitHub, CurseForge, Discord, etc.) and seems like it may be an issue with your computer based on what you're saying.

**Comment by scalda** [comment]
interesting i may give this a look at for the next pack version thanks
