### ISSUE TITLE
[Suggestion] Add Computronics

### ISSUE THREAD

**Issue by arketec** [scalda/Foolcraft_3#200]
## FEATURE REQUEST
- [x] I would like to propose an additional mod.
- [ ] I would like to propose a config change.
- [ ] I would like to propose a custom recipe.
- [ ] I would like to propose another change.

## MOD INFORMATION
Computronics:
https://github.com/Vexatos/Computronics

**Comment by arketec** [comment]
It's not 1.12.2 yet, but once it is updated, it would be cool to have it added

**Comment by scalda** [comment]
still not updated sorry
