### ISSUE TITLE
Client-side error causing crash after connecting to server

### ISSUE THREAD

**Issue by SloppyGiuseppe** [scalda/Foolcraft_3#201]
## Issue Description
A few minutes after joining the server I crash with a light blue screen.

There are no errors in the server console just that I lost connection.

benrose123 lost connection: Internal Exception: io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer

## Reproduce Steps
Probably can't easily reproduce...

I have joined the server repeatedly and have continued to crash.

## Additional Information
Crash log:
https://pastebin.com/fxfGAiED

Thanks.

**Comment by nzminecraftDOTcom** [comment]
You haven't gone into a morph while wearing a hat in F5 mode have you? Those cause crashes on occasion. That or there is a block in your view that you can't render and it's causing issues. Try reset your location in the worlds data and see if that fixes it.

**Comment by Mrbysco** [comment]
The crash states something about a property of a block not being what it expected. Something to do with mob grinding utils.
There's also 1 line that mentions optifine

**Comment by SloppyGiuseppe** [comment]
Thanks for your comments.
I do have some mob grinding utils objects near me, I guess the crashes could be caused by looking in their general direction. Do you have any ideas how I can remove the objects? As I assume going near them will just crash my game again.

**Comment by SloppyGiuseppe** [comment]
I was able to remove all mob grinding utils objects, although when I broke the mob fan from grinding utils I crashed. So that may have been the issue.
I have played for around 10 minutes without a crash.

Thanks again for your help.

**Comment by scalda** [comment]
update to Beat 1.5 and test, Please report back and close the issue if it's solved. i will close in 7 days if not responded to or not closed before hand
