### ISSUE TITLE
Repellent Enchantmen

### ISSUE THREAD

**Issue by RikkudoSennin** [scalda/Foolcraft_3#202]
This enchantment from Enderio is literally annoying and tilting to play with, the chances are most likely 80%-90% to be teleported away, it makes clearing dungeon really painful. Hope there'll be a config to disable the enchanment from mobs or lower the chance of it!

## FEATURE REQUEST
- [ ] I would like to propose an additional mod.
- [x] I would like to propose a config change.
- [ ] I would like to propose a custom recipe.
- [x] I would like to propose another change.

<!-- FEATURE INFORMATION - Please explain what you want changed/added and why.

**Comment by Krutontar** [comment]
And if you attack that mob with a fake player it can crash the server.

**Comment by scalda** [comment]
I am aware of this but until enderio updates I can't push out a fix
