### ISSUE TITLE
The game crashed whilst unexpected error [1.4.5]

### ISSUE THREAD

**Issue by Emaru2** [scalda/Foolcraft_3#203]
Version: 1.4.5

I can't reproduce it, well not on purpose.

Singleplayer world

Crash message: The game crashed whilst unexpected error
Error: java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[down, up, north, south, west, east]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}

Issue: I had updated my singleplayer world to 1.4.5 from 1.3.1 and continued to work on projects. I crashed twice since the update while I've never crashed in previous versions. First crash I was working on a build and just reloaded FC3 but the 2nd time I thought this was happening too much in a short amount of time (about an hour apart) and the 2nd crash I was just clearly trees from an area. The error message was copy & pasted from the 2nd crash and I'm unsure if the first crash would have had a similar message as I didn't check at the time.

**Comment by Emaru2** [comment]
Just happened again 2 minutes after loading the world and working on builds. Placed 6 stairs and 4 cobblestone down then crashed. The screen goes completely white before each crash. Will be returning to 1.3.1

3rd Crash message:
The game crashed whilst unexpected error
Error: java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[down, up, north, south, west, east]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}

**Comment by itskdog** [comment]
Are you able to send a paste in link to the full crash log? You should be able to find them in FoolCraft 3 folder -> “logs”

**Comment by NateChambers** [comment]
I also get this same error every time I go over to where my crafting grid and a few other machines are. Started happening with this new 1.4.5 version of the game.

Here is 1 of my crash log files if it helps any.

[crash-2018-07-14_04.10.13-client.txt](https://github.com/scalda/Foolcraft_3/files/2194782/crash-2018-07-14_04.10.13-client.txt)


I am basically unable to use my current storage and crafting area until this crashing stops. :/

**Comment by Mrbysco** [comment]
Mob grinding utils fans are crashing. Another person had this issue aswell

**Comment by Mrbysco** [comment]
You'll have to figure out where the fan is and remove it

**Comment by NateChambers** [comment]
I am not sure that is the problem Mrbysco. The mob farm I have with fans is about 1000 blocks away. AND I can actually go to it with zero crashes. So that shouldn't be effected the 20 chunk or so area where the game always crashes.

**Comment by Mrbysco** [comment]
The tileentity of that block is causing some issues 
![afbeelding](https://user-images.githubusercontent.com/9308260/42728913-dbfc1584-87c6-11e8-8592-5a1943aa4af0.png)

**Comment by NateChambers** [comment]
Got ya! Very strange it doesn't crash near it but far away from it. Maybe it's from unloading that chunk?

**Comment by Emaru2** [comment]
I had removed my mob mashers and didn't get any crashes until a moment ago.

[latest.log](https://github.com/scalda/Foolcraft_3/files/2197484/latest.log)

I reloaded the game and didn't load the world until [22:00:25] which is around the middle of the file. Just before the crash I had set up autocrafting for thankful dinners and then went to work on a project which was when the crash happened.

**Comment by scalda** [comment]
this is now fixed in pack version 1.5 beta sorry for the delay

**Comment by itsmeow** [comment]
Hi, I'm having a related issue with my mod. Can I get help with a fix? https://github.com/itsmeow/betteranimalsplus/issues/28

**Comment by KetchupxD** [comment]
just happened to me in hypixel anyone alive here anymore? lol
