### ISSUE TITLE
Chissel and Bits - Replace function doesnt work

### ISSUE THREAD

**Issue by SgtPhyko** [scalda/Foolcraft_3#204]
## Modpack Information

The Chissel and Bits function to replace bits doesnt work - i can remove and place bits without problem but cant replace bits. Tested with multiple chissels in inventory and hotbar also tested with other servermembers trying.

Edit: Intrestingly replacing the material with a chisseldesign works fine

Edit2: ~~its seems using a new chisselbag fixxed the issue~~ (Edit 3: the bug resurfaced no Idea when or how , new bags wont change it back -> definitly need of some bugfixing, its kinda gamebreaking for heavy chisselers like me)

Welll - take some bits and try to replace any blocks bits (not remove and place but replace)

## Additional Information
Currently playing on Iskalls Herkules Server

**Comment by scalda** [comment]
i see what you mean i have found that it works on some blocks but not all, i will have to see if there is a update for the mod

**Comment by SgtPhyko** [comment]
it seems to not recognizing the chissel in ur inventory ("not harvestable" is showing in the tolltip on blocks that cant do the replace function) not sure if that helps

**workaround:** make a negative of the block - remove material u want to replace - fill block with the material u want to switch to - use the negative design on the block -> material is replaced

**Comment by scalda** [comment]
update to Beat 1.5 and test, Please report back and close the issue if it's solved. i will close in 7 days if not responded to or not closed before hand
