### ISSUE TITLE
Thaum robes upgrade for EnderIO 'Ender' armor not applying vis discount

### ISSUE THREAD

**Issue by jestesared** [scalda/Foolcraft_3#205]
The Dark armor and Ender armor from EnderIO both have the option of applying thaumaturge robes, leggings, and boots respectively, offering a vis discount. But this is not working, with the upgrade applied and the armor worn, no discount is granted.

**Comment by Mrbysco** [comment]
Please report this to the EnderIO devs.

**Comment by jestesared** [comment]
https://github.com/SleepyTrousers/EnderIO/issues/4775

**Comment by scalda** [comment]
update to Beat 1.5 and test, Please report back and close the issue if it's solved. i will close in 7 days if not responded to or not closed before hand
