### ISSUE TITLE
Foundry Ore Glitch

### ISSUE THREAD

**Issue by JamesHiegel** [scalda/Foolcraft_3#208]
## Issue Description
Before the 1.4.5 update, I Was using foundry to double my ores. Now, one ore turns into one Milibucket of the material, instead of the usual 228.

## Reproduce Steps
Put any ore into the foundry mod melter and it turns into one Milibucket of the material, instead of the usual 228.

## Additional Information
https://www.reddit.com/r/Foolcraft/comments/8z24fw/foundry_ore_glitch/

**Comment by scalda** [comment]
see here for the answer https://github.com/scalda/Foolcraft_3/issues/213
