### ISSUE TITLE
Refined Storage Network Transmitter and Receiver Blocks Missing

### ISSUE THREAD

**Issue by OpsKern** [scalda/Foolcraft_3#209]
## FEATURE REQUEST
- [ ] I would like to propose an additional mod.
- [ ] I would like to propose a config change.
- [ ] I would like to propose a custom recipe.
- [X] I would like to propose another change.

## FEATURE INFORMATION
I'm assuming it was taken out on purpose but if you could let me know why the Refined Storage Network Transmitter and Receiver blocks aren't in the modpack and if they will be at any point, that'd be great.

## MOD INFORMATION
Details here: https://refinedstorage.raoulvdberge.com/wiki/networks-over-long-distances

**Comment by Mrbysco** [comment]
They were taken out because they were a huge lag source on servers

**Comment by OpsKern** [comment]
Thanks @Mrbysco any alternatives then?

**Comment by scalda** [comment]
what @Mrbysco said, you can use the quantum rings in AE2 for the same function

**Comment by OpsKern** [comment]
thanks @scalda :)
