### ISSUE TITLE
Petrified Fuel Generator Nerfed? 

### ISSUE THREAD

**Issue by Seegras** [scalda/Foolcraft_3#21]
## SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

The Petrified Fuel Generator from Industrial Foregoing produces just 2 RF/tick on Coal. This is rather ridiculous; and was done via specific config-change for FoolCraft. Do you really think this is "fun"? 

## Reproduce Steps
Put coal into Petrified Fuel Generator

**Comment by Seegras** [comment]
It burns fuel so quickly, you can't probably sustain that, unless you have some kind of very fast coal generator. And wood et. al. doesn't work, because it's dependent on the overall burn time. The best block would be coal/coke with 32000, followed by coal or charcoal blocks with 16000, but then, all the rest is 1600 for coal and charcoal, 300 for wood and 100 for sticks.

With the defaults this means 80RF/Ticks for coal, but for 80 seconds. Can you sustain even that? Unless you have a way of generating massive amounts of coal, it's not feasible. 

I understand you'd want to cut it back, but then a factor of 4, which would still give decent 20 RF/t for coal, but 200RF/t for coal blocks would be more in line with other generators. And still give the a reason to make the 
petrified generator: if you need a lot of power real quick, but not for a long time.

Compare by the way to the thermal expansion dynamos. They can do something like 960RF/t with all the upgrades.

**Comment by scalda** [comment]
This has been altered for the next release of the pack.
