### ISSUE TITLE
AE2 Wireless Crafting Terminal (@wct) texture missing

### ISSUE THREAD

**Issue by arketec** [scalda/Foolcraft_3#210]
## Issue Description
The texture is missing for the Wireless Crafting Terminal for AE2 from the Wireless Crafting Terminal 2 mod (@wct) since the pack 1.4.5 update

It still works, it just looks like an empty inventory slot when fully charged

It still shows the energy bar when it's drained, but no texture

## Reproduce Steps
No steps to reproduce, this happens from launch even in a new SSP world.

## Additional Information

screenshot:
https://imgur.com/a/JACT28K

**Comment by scalda** [comment]
They work fine for me you may have a corrupted file, and a clean profile install would help you

**Comment by arketec** [comment]
ok I re-downloaded the profile and the texture came back. Thanks scalda!
