### ISSUE TITLE
[Suggestion mod] InGame Info XML

### ISSUE THREAD

**Issue by galsol** [scalda/Foolcraft_3#211]
---
name: "💡 Feature Request"
about: Suggest a mod or other changes to the modpack.
---

## FEATURE REQUEST
- [x] I would like to propose an additional mod.
- [ ] I would like to propose a config change.
- [ ] I would like to propose a custom recipe.
- [ ] I would like to propose another change.

## MOD INFORMATION
InGame Info XML
https://minecraft.curseforge.com/projects/ingame-info-xml
I think it's a pretty good client-sided mod, that allows for a lot of creativity.
Perhaps make the default XML configuration to be a simplistic one that only shows a couple of information lines.

**Comment by scalda** [comment]
This isn't something i feel is needed in foolcraft, thanks for the suggestion though
