### ISSUE TITLE
BonsaiTree Mod not working for vanilla trees

### ISSUE THREAD

**Issue by AMrWhiteGuy** [scalda/Foolcraft_3#212]
I just started using the bonsaitree mod and set up a nice tree farm with them only to find out that vanilla trees wont place on the hopper. All the biomes o' plenty trees seem to be working just fine with it however....

(I don't know if this is any help but all of the vanilla trees i am using i got from the "I see you bought the sapling DLC" drop from a chance cube)

**Comment by jlipscomb** [comment]
Perhaps there are metadata issues with the saplings from the chance cube. I am unsure if this is the correct avenue, however, as I am not familiar with the code of Chance Cubes and Bonsai Tree. 

Can you please try other vanilla based tree saplings that you have obtained from a tree? I have been able to use Dark Oak saplings in the Bonsai Tree Mod. 

Foolcraft 3 Version: 1.4.5
Bonsai Trees Version: 1.0.5-b77

**Comment by AMrWhiteGuy** [comment]
I was trying that not long after I posted the issue. Sadly i still have had no luck

**Comment by galsol** [comment]
Make sure your off-hand is clear ^^

**Comment by Mrbysco** [comment]
Have you tried placing the saplings themselves on dirt and breaking them again? that should reset their metadata if that were to be the issue

**Comment by AMrWhiteGuy** [comment]
Bulubl-akabulbul is that a factor? cause i had placed biomes o' plenty saps just fine with something in my off-hand. However i will try it later.

Mrbysco i will also try that as well. i didn't think to do that

**Comment by galsol** [comment]
Yes indeed.
From my testing in singleplayer creative,
I could place BOP saplings with stuff in my off-hand but couldn't with normal saplings.
I've encountered the same issue in my playthrough as well ^^

**Comment by AMrWhiteGuy** [comment]
Thank you so much to everyone that gave suggestions. The off-hand removal did the trick. You guys were awesome
