### ISSUE TITLE
Foundry melting crucible

### ISSUE THREAD

**Issue by Tipperty** [scalda/Foolcraft_3#213]
## Issue Description 

Foundry melting crucible costing too much ore to make single ingots.

## Reproduce Steps

Setup the melting crucible, with a burning heater below. An ingot casting table infront of the heater, with a refactory spout connected to the crucible, facing towards the casting table. Insert a usable ore and see how many are needed before being able to cast a single ingot.

## Additional Information

I recorded a video for easy viewing :)

https://www.youtube.com/watch?v=qGa9Jmt4LhY

**Comment by itskdog** [comment]
Can you please tick the boxes in the issue template by replacing the space with an "X" as instructed.

**Comment by galsol** [comment]
I've had the same issue... Seems like ore yields only 1 mb (instead of 288).
You can use ingots if you want to create alloys.

**Comment by Tipperty** [comment]
Sorry itskieranp, I haven't filled in many of these and almost none on this site.

**Comment by scalda** [comment]
i have just found the fix, you need to change this line in the foundry config file to the same as i have put

`    # The value, in mB, of an ore.  Set to 0 to use default values. [range: 1 ~ 2147483647, default: 0]
    I:"Fluid Ore Value"=228`

**Comment by Tipperty** [comment]
Thanks for the quick turn around :)

**Comment by Tipperty** [comment]
Hi Scalda, just a quick question, doesn't the melting crucible by defualt double ingot production from a single ore block and so shouldn't 114 be the correct value instead of 228?

**Comment by scalda** [comment]
114 is a single ingot so 248 allows the crucible to double

**Comment by Tipperty** [comment]
Yeah I am an idiot, I calculated it the wrong way. Sorry

**Comment by scalda** [comment]
fixed in beta 1.5 please update your pack
