### ISSUE TITLE
MR crayfish washing machine missing reci

### ISSUE THREAD

**Issue by ImTheStigHonest** [scalda/Foolcraft_3#214]
## Issue Description
Mr Crayfish washing machine does not accept dark armor from ender iO

## Reproduce Steps
unable to place dark armor pieces in the washing machine

## Additional Information
normal armor is accepted . I haven't tried it with mega loot armor

**Comment by itskdog** [comment]
Please fill in the pack version.

**Comment by ImTheStigHonest** [comment]
sorry done

**Comment by scalda** [comment]
sadly i don't think you can put dark armor in, if i remember correctly you weren't able to in the older versions either
