### ISSUE TITLE
[Bug] Megaloot tools with Area Miner disconnects Client when changing size

### ISSUE THREAD

**Issue by TheonlyTazz** [scalda/Foolcraft_3#215]
## Issue Description

When creating a Megaloot Tool (Epic) that (probably) has a to long of an NBT tag, it will crash you out of the server whenever you switch Mining modes.
https://i.imgur.com/nTMNFu7.png

it was working when i had 1 upgrade left, after i added the last upgrade it broke.
maybe the UUID of the tool will help?
https://i.imgur.com/XB7K0Ml.png

## Reproduce Steps

happens to alot of megaloot epic tools that are fully upgraded with area miner

**Comment by itskdog** [comment]
Please update the report with the pack version at the top. Thanks.

**Comment by TheonlyTazz** [comment]
woops, missed that one xD
although this bug happened in older versions aswell

**Comment by TheonlyTazz** [comment]
i wonder if @scalda knows anything about this?

**Comment by scalda** [comment]
waiting to hear back from winter grave regarding this

**Comment by WinterGrave** [comment]
Could we get some sor of log with info about this so I can have a better understanding of how it happens? Thanks!
