### ISSUE TITLE
original profile won't update

### ISSUE THREAD

**Issue by hexangle** [scalda/Foolcraft_3#217]
So I tried updating my FC3 but it gets the error: files are already in use... but I am not using them and it happens with every new download. Any  idea how to fix it because every time I have to update to a new profile and than I have to change my controls again.

**Comment by nzminecraftDOTcom** [comment]
If you don't want to mess with running processes, try rebooting your computer before updating. Minecraft may not be properly shutting down for you, a reboot of your computer should start it fresh. Try updating your profile after that.

**Comment by scalda** [comment]
twitch launcher issue not the pack
