### ISSUE TITLE
Open to LAN crash

### ISSUE THREAD

**Issue by galsol** [scalda/Foolcraft_3#218]
## Issue Description
When I open my save to LAN and then try to quit the save, the game freezes and then crashes.

## Reproduce Steps
Open the save to LAN.
Quit the save

## Additional Information
I've added the mod InGame Info XML.
I've only tried that when allowing cheats,
and only in my play-through save.

**Comment by Mrbysco** [comment]
Could I see the Crash report and the last log file?

**Comment by Mrbysco** [comment]
(preferably using Pastebin to not make this issue giant)

**Comment by galsol** [comment]
https://pastebin.com/hGXV1mKL this is the latest log.
This doesn't seem to create a crash report.

I've opened the LAN world at 00:51:45,
walked around a bit and then quit and crash.
Just opening to LAN doesn't seem to do the trick and I have to move a bit before quitting.

**Comment by Revvilo** [comment]
I've never seen it actually crash before, but I'm thinking it might be this vanilla bug;
https://bugs.mojang.com/browse/MC-72943
Unfortunately, it's only fixed in 1.13 from what I can tell... but it's good to see that ancient bug finally gone.

**Comment by scalda** [comment]
Yeah i would agree with @Revvilo that this is a vanilla bug as i can not reproduce it
