### ISSUE TITLE
AE2 disabled?

### ISSUE THREAD

**Issue by ajdjyt** [scalda/Foolcraft_3#22]
## SUGGESTION/HELP
- [X] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
is ae2 in the modpack just for its crafting components? because there is no recipe for sky stone (the type which is used in the controller recipe)

**Comment by kpeckett** [comment]
Sky Stone can be found naturally generated in the world, at the meteorite structures.

**Comment by ajdjyt** [comment]
"i appreciate your help"
![image](https://user-images.githubusercontent.com/26516505/40358842-41a803ba-5dde-11e8-9b95-f6f0556bc4cf.png)
![image](https://user-images.githubusercontent.com/26516505/40358849-4a75dfe4-5dde-11e8-9f02-cd38277868a0.png)

**Comment by aolsen96** [comment]
you need to smelt the skystone

**Comment by ajdjyt** [comment]
i cant

**Comment by ajdjyt** [comment]
it wont work.play the freaking pack then answer, please i am not "brand new" ok i have played and made a storage system with ae2 multiple times .

**Comment by ajdjyt** [comment]
WT in the world ,are you playing foolcraft 3?
