### ISSUE TITLE
Reinforced Glass with Red Matter Pickaxe

### ISSUE THREAD

**Issue by galsol** [scalda/Foolcraft_3#220]
## Issue Description
Red Matter Pickaxe from ProjectE can't effectively mine Reinforced Glass from Tiny Progressions,
and WAILA doesn't say it counts as a pickaxe.

## Reproduce Steps
Try to mine a Reinforced Glass with a Red Matter Pickaxe with any charge level and mode of the pickaxe.

## Additional Information
It can mine the Reinforced Obsidian (Which has a higher mining level, don't know if it affects anything).
Any other pickaxes and drills can mine it effectively.

**Comment by scalda** [comment]
i would say it's a bad mod interaction try 1.5 beta and report back if not will close in 7 days
