### ISSUE TITLE
java.lang.OutOfMemoryError: Direct buffer memory

### ISSUE THREAD

**Issue by MunkeePlayz1** [scalda/Foolcraft_3#221]
I am having an issue with the memory buffer in Foolcraft 3, I have set me allocated memory manually in the minecraft launcher and through Twitch launcher to 6144, I have also tried lowering and raising the amount of RAM
## Modpack Information
 Foolcraft 3 1.4.5

Start Foolcraft 3, let load, join game, minutes later, crash.

<!-- ADDITIONAL INFORMATION
https://pastebin.com/9LmzFN2c

**Comment by Mrbysco** [comment]
Can I see a screenshot of the memory allocation?

**Comment by MunkeePlayz1** [comment]
You sure can!
 
Here is my Twitch launcher setting for RAM allocation
![twitch settings](https://user-images.githubusercontent.com/41401636/42975289-f310deae-8b80-11e8-89c5-8264b7629e05.png)

Here is the Minecraft launcher settings.
![mc launcher](https://user-images.githubusercontent.com/41401636/42975301-02e5b8cc-8b81-11e8-9225-e6a17f69395c.png)

I also have a screen shot of my task manager while I am loading all the mods and when I am in a single player world. If you would like to see that mess.

**Comment by Mrbysco** [comment]
What java do you have installed? 32 or 64bit (because 32 bit goes up to 4 gb max)
Also I see you got the minecraft launcher supplying you with their java which is outdated and can cause crashes with Immersive Engineering

https://www.iskall85.com/forum/m/37727173/viewthread/32016029-immersive-engineering-java-fix/page/1 shows you how to set the java used by the Twitch launcher.

**Comment by MunkeePlayz1** [comment]
I have Java 64bit, I have tried letting twitch supply Java. I am still having the issue. I tried playing another pack, the Direwolf20 1.12 v2.1 and it plays just fine. What I think I am going to do is start removing mods until I stop having the issue. Then I will add them in one at a time. Or I might say F*** it and just put a different pack on my server.

**Comment by scalda** [comment]
Any response on this if not i will close in 7 days

**Comment by flann** [comment]
I'm also having this issue. I set the java version using the iskall85.com link shown above. I'm on 64-bit JRE 1.8.0_181 on Windows 10. I'm using the jar launcher from twitch and I've got over 8G allocated.
[Crash Log](https://pastebin.com/efnHdhSX)
