### ISSUE TITLE
Ultimate Crafting recipe for Crystal Cluster requires Efficiency Rune which has no recipe

### ISSUE THREAD

**Issue by Chalmes** [scalda/Foolcraft_3#222]
## Modpack Information

Efficiency Rune has no recipe, so can't be used to make crystal clusters via the ultimate crafting recipe.  Crystal Clusters are required to get the tier 6 blood altar

**Comment by scalda** [comment]
Whoops my bad ill sort that for the hotfix I'm planning this week as soon as ender io updates

**Comment by scalda** [comment]
will fix in 1.5.1
