### ISSUE TITLE
Extra Utilities Book

### ISSUE THREAD

**Issue by VerneGeer** [scalda/Foolcraft_3#223]
## Issue Description
When using extra utilities i cant open guide book. Crash the game.

## Reproduce Steps
Try opening book -> crashes

**Comment by galsol** [comment]
Can confirm I am having this issue as well.
I tried launching an instance with only Extra Utilities 2 (same version as pack) and the same FML version,
and not crash while opening the book.

**Comment by Mrbysco** [comment]
Log please

**Comment by galsol** [comment]
Would my crash report and log help?

**Comment by Mrbysco** [comment]
Yes

**Comment by galsol** [comment]
crash report - https://pastebin.com/mYenFMvF
log - https://pastebin.com/BxftCSjL
Sorry for the delay ^^
Thanks!

**Comment by ScottDWebster** [comment]
I get the same result when attempting to open the book.

**Comment by Mrbysco** [comment]
Duplicate of https://github.com/scalda/Foolcraft_3/issues/146

**Comment by scalda** [comment]
been reported her https://github.com/rwtema/extrautilities_old_issues/issues/1786
