### ISSUE TITLE
Chiseled Armor scales wrong in 1.4.5

### ISSUE THREAD

**Issue by Lizard-Of-Oz** [scalda/Foolcraft_3#224]
## Issue Description
Chiseled Armor from Extra Bit Manipulations have wrong scaling. When it supposed to be 1:1 and fit character, its actual position is somewhere in a legs, and its size is not correct.
In FC3 1.3.0 this bug is not presented, but version of the mod is the same on both versions of the pack.
This bug affects both new armor and pre-existing one from older versions.

## Reproduce Steps
Make a Chiseled Armor -> get it wrong scaled.

## Additional Information
Screenshots side-by-side two versions: https://i.imgur.com/TYhusS7.png

**Comment by Phylogeny** [comment]
This should be fixed as of [v3.3.0](https://minecraft.curseforge.com/projects/extra-bit-manipulation/files/2599912). Let me know if you run into any problems.

**Comment by scalda** [comment]
update to Beta 1.5 and test, Please report back and close the issue if it's solved. i will close in 7 days if not responded to or not closed before hand

**Comment by Phylogeny** [comment]
As far as I've tested just now, it's fixed in Beta 1.5. Please confirm that it's fixed for you too, DaNetNavern0.

**Comment by Lizard-Of-Oz** [comment]
Yep, works very fine. Good job!
