### ISSUE TITLE
Botania - Pinkinator does not drop

### ISSUE THREAD

**Issue by Plutosion** [scalda/Foolcraft_3#225]
## Issue Description

After killing the hard mode version of the Gaia Guardian at least 20 times, the pinkinator has not dropped even though it's supposedly a 20% chance.

## Reproduce Steps

Kill the Gaia Guardian in hard mode (summon using Gaia spirit) and pinkinator will not drop

**Comment by Mrbysco** [comment]
Gaia Guardian 1 or 2?

**Comment by Kaisdf** [comment]
I have 7 or 8 kills on the gaia guardian (2), with no drops. Could just be bad luck, idk.
(N.B. I am using v 1.1.1, so slightly outdated)

**Comment by Chalmes** [comment]
It definitely drops.  I've had two drop in my time, but easily 40 kills of the Gaia Guardian 2 to get them.

**Comment by Kaisdf** [comment]
Correction: I got it next kill (I think the 8th kill).

**Comment by Mrbysco** [comment]
The issue can be closed as it has been confirmed to drop.
