### ISSUE TITLE
Hover boots from open computer do not seem to charge

### ISSUE THREAD

**Issue by MrTimoth** [scalda/Foolcraft_3#226]
## Issue Description
After crafting the Hover Boots from Open computers I can't seem to get them to charge. I have tried the open computers charger, thermal expansion charger, and have flux network wireless charging working in my base. Other powered devices seem to work fine.

Have these boots been disabled? They seem like they would be some pretty fun if I could get them working.
Thanks.

## Reproduce Steps
Step 1: Craft the Hover Boots and get all excited about being resistant to fall damage and having faster run speed and jump boost! (according to their advertisement text)
Step 2: Pop it into a charger! 
Step 3:  Witness it not charging and be disappointed.  

## Additional Information
Love the foolcraft packs. Thanks for all your good work.

**Comment by scalda** [comment]
Hi i'm sorry but i'm not sure how to replicate this as i have no idea how to use open computers
