### ISSUE TITLE
Server tick loop Error: ModCrash: EnderStorage

### ISSUE THREAD

**Issue by Yofreaky** [scalda/Foolcraft_3#228]
So it will no longer allow me to play on my single player world, it crashes when it tries to load up and returns me to the launcher with his crash report:
"The game crashed whilst exception in server tick loop
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from EnderStorage (enderstorage)"
I'm not sure if anyone else has this issue, I don't know if it's the ender chests causing issues or what. I hope there's a simple fix to it. As far as I'm aware this is a new issue, I didn't see anything like it while scrolling through the list, hope you can help!

**Comment by nzminecraftDOTcom** [comment]
Are you able to post a crash report that was generated at the same time?

C:/users/[yournamehere]/documents/curse/Minecraft/instances/foolcraft3

**Comment by itskdog** [comment]
Preferably via PasteBin, please!

**Comment by Yofreaky** [comment]
Sure! Here it is: https://pastebin.com/PecQ5kAD

**Comment by Yofreaky** [comment]
Sure! Here it is: https://pastebin.com/PecQ5kAD
Sorry for the delay and the repost of this comment.

**Comment by Mrbysco** [comment]
https://github.com/TheCBProject/EnderStorage/issues/69

**Comment by Yofreaky** [comment]
That's unfortunate that Ender Storage's data requires to be deleted, I had stored my void miner's crystals in one and I had left it running over night because of how long it took to get them, but it's much better than having to delete the world all together, thanks for the help guys!
https://github.com/TheCBProject/EnderStorage/issues/69
Solution ^ @nzminecraftDOTcom @Mrbysco

**Comment by scalda** [comment]
hi thanks for the issue but looks like it's just a bad situation of corruption sorry for the inconvenience it caused
