### ISSUE TITLE
a couple of mods

### ISSUE THREAD

**Issue by closeshot** [scalda/Foolcraft_3#229]
## FEATURE REQUEST
- [X ] I would like to propose an additional mod.
- [ ] I would like to propose a config change.
- [ ] I would like to propose a custom recipe.
- [ ] I would like to propose another change.

 the dank null mod 
https://minecraft.curseforge.com/projects/dank-null
Building Gadgets
https://minecraft.curseforge.com/projects/building-gadgets
## MOD INFORMATION
The dank null is a nullifier that lets you hold stacks of blocks until full and deletes the items once slot is full.
Building gadgets is an exchanger and builder mod like building wands made by direwolf20

**Comment by Mrbysco** [comment]
The item the "Dank Null" is based on is called the "Dev null" and is part of openblocks which is in the pack

**Comment by Ravalli03** [comment]
I do agree with adding dank null, it has many more options then open block Dev null.

**Comment by scalda** [comment]
this has been asked before and it won't happen
