### ISSUE TITLE
Angel Crystal / Mini Moos 

### ISSUE THREAD

**Issue by xGarionx** [scalda/Foolcraft_3#230]
## FEATURE REQUEST
- [ ] I would like to propose an additional mod.
- [x] I would like to propose a config change.
- [ ] I would like to propose a custom recipe.
- [ ] I would like to propose another change.

<!-- FEATURE INFORMATION - Please explain what you want changed/added and why.
## FEATURE INFORMATION

The mini Moo mod is already pretty limited due to config changes, with the angel crystal removed from the drop table its almost impossible to get certain mini moos and if there is a emphatize in this mod pack on random chance (megaloot, chance cubes ,roguelike drops), i would suggest to re-enable them again . 
Regards

**Comment by xGarionx** [comment]
For some odd reason this part isnt showing (probably own stupidity) : 
The mini Moo mod is already pretty limited due to config changes, with the angel crystal removed from the drop table its almost impossible to get certain mini moos and if there is a emphatize in this mod pack on random chance (megaloot, chance cubes ,roguelike drops), i would suggest to re-enable them again . 
Regards

**Comment by Mrbysco** [comment]
It can be found in dungeon loot. Especially as it's required in the Mooing Star recipe

**Comment by xGarionx** [comment]
it doesnt , i checked enough chest and run a infinite mana pool powered loonium farm (that has stupidity levels of magnitude) to be very certain that the drop chance is so low that it doesnt drop in dungen loot ,since compareable rare item ...like Double and Triple Unstable Impossible Capacitors show up fairly regular.

**Comment by Mrbysco** [comment]
It's confirmed to drop so I don't know what's going wrong on your side.

**Comment by xGarionx** [comment]
Allright thanks for the information i'll check with the admins and mods this might be a config error that translated over from beta versio or some other funny buisness

**Comment by Mrbysco** [comment]
Just so you know. It's added to dungeon loot through the script files

**Comment by Mrbysco** [comment]
![afbeelding](https://user-images.githubusercontent.com/9308260/43143290-bb96ed82-8f5a-11e8-93a8-bd34affca5e2.png)
This is a pic of a chest of a friend of mine that's on 1.4.5 and using the loonium

**Comment by xGarionx** [comment]
Thanks for the  information, i'll guess something got missmatched when the server updated and some scripts or configs didnt carry over (or our admins did it itentional or one of them that wasnt online not sure)
