### ISSUE TITLE
Ender IO redstone conduit not working

### ISSUE THREAD

**Issue by pinkcat13** [scalda/Foolcraft_3#232]
After I updated to the newest version of the modpack (release 1.4.5), my redstone conduits stopped working.  I tried picking up/replacing and also creating new ones, but nothing helps.

**Comment by burturt** [comment]
Did you check the colors? If you left the conduit on default iirc the default output changed from red to green so any conduits left untouched had this change happen. Also noticed a thing where output input would swap/get mixed up.

**Comment by itskdog** [comment]
Please use one of the issue templates (bug report or feature request) and fill in the form. If you’re on the mobile site, try using the “request desktop version” option in your browser.

**Comment by scalda** [comment]
this is an issue with the update of ender io that they changed so you need to check all conduits

**Comment by Celophy** [comment]
i have the same problem!!
