### ISSUE TITLE
Client server crash when placing RF TOOLS screen

### ISSUE THREAD

**Issue by ImTheStigHonest** [scalda/Foolcraft_3#233]
## Issue Description
Client side server shut down/crash when placing rf tools screen

## Reproduce Steps
rf tools screen right click on surface. client side server shut down 
game can be restarted normally afterwards

**Comment by itskdog** [comment]
Are you able to provide a copy of the game log & crash log via pastebin?

________________________________

**Comment by ImTheStigHonest** [comment]
it didn't crash the game just shut down the client side server.no crash reports are in the folder for that date

**Comment by itskdog** [comment]
What about the game log with all the game events in it? Should be in <Foolcraft 3 folder> -> "logs" -> "latest.log"

**Comment by ImTheStigHonest** [comment]
[2018-07-22-1.log.gz](https://github.com/scalda/Foolcraft_3/files/2224571/2018-07-22-1.log.gz)
this is the log at the approx time. couldn't past bin as it is to big

**Comment by scalda** [comment]
Hi can you please test this issue with the new beta version 1.5 as this problem is fixed in both ender io and mob grinding utils and please report back
