### ISSUE TITLE
viewing painting machine recipes for thermal expansion ducts breaks the world

### ISSUE THREAD

**Issue by TheMajesticPickle** [scalda/Foolcraft_3#234]
## Issue Description
When viewing recipes for thermal expansion pipes in the painting machine, the game will crash and you will not be able to rejoin your world.

## Reproduce Steps
1. in jei, search for "duct." any of the thermal expansion ducts will do.
2. right click/press U on any of the ducts.
3. press the painting machine recipe

https://pastebin.com/MQdF0sPJ

## Additional Information
I have not tested it yet however if this happens to anyone, a world backup is not necessary! just reinstall forge (aka just pressing "repair Minecraft") and you're probably good to go! the error is not within the world itself but within java/forge/Minecraft.

I have not modified the pack at all aside from adding optifine (which may be part of it, but I cant run the pack without it.) and disabling Better Foliage via the config. I have also changed some biome settings in Biomes O plenty, but that's irrelevant

**Comment by galsol** [comment]
I've had this happen to me with other items when I look at the painting machine recipe,
including stuff from not thermal-expansion.
I don't have optifine installed so thats not the issue.

**Comment by scalda** [comment]
mod authors are aware of this issue see the tagged link above

**Comment by tyler489** [comment]
You dont even need to repair minecraft just relaunch
