### ISSUE TITLE
Metamorphic Rock is too expensive to craft

### ISSUE THREAD

**Issue by plunginghornets** [scalda/Foolcraft_3#235]
## Modpack Information

Marimorphus is disabled. While I don't understand that decision, it's whatever.
The alternative recipe for metamorphic rock is (I hope) coded wrong. Right now the recipe consumes a Rod of the Shifting Crust and Biome Marker for every 8 stone made. That's 2 diamonds, 4 iron, and a LOT of mana for a decorative block.
I'm assuming the recipe is supposed to be set so it does not consume the rod or the biome marker. As this would make the cost of the blocks 6 stone and one mana powder for 8 metamorphic rock. Which is far more reasonable.

Craft metamorphic rock in Foolcraft 3 ver. 1.4.5

**Comment by theBluebaerry** [comment]
I agree, especially when the energy condenser is super late game it kinda sucks that these blocks are so expensive to craft right now :/

**Comment by Larkal92** [comment]
This should be a simple fix; the Marimorphus crash issue was fixed a while ago (unless this is a new one), so just re-enable the old recipe and remove the placeholder recipe.

**Comment by scalda** [comment]
@plunginghornets hhmmm interesting as it is supposed to do what you are saying, by giving back those items, I'll look into this for the upcoming micro update

**Comment by plunginghornets** [comment]
@Larkal92
I'm playing on a server, so I can't make the change. But they did promise to keep it updated, so an official fix will work.

@scalda
If the Marimorphus is indeed fixed (from what I hear the issue was way back in 1.10) would you consider allowing the flower itself to be crafted?

**Comment by scalda** [comment]
i will sort the recipes out along with enabling the flower for 1.5.1
