### ISSUE TITLE
Problematic EMC holding Items, Game Breaking EMC holding Items, ChanceCube/Ore Dict related crash

### ISSUE THREAD

**Issue by xGarionx** [scalda/Foolcraft_3#236]
## Issue Description

Game Breaking issues / Chance CUBE):
Due to incorparating of Essence (fluid) into the Fluid Chance cube while unifiying it with Essence of Knowledge and Liquid XP, chunks gets corrupted since all fluids are fundamentally are different (only essence can be place inthe world), but are handled the same by chance cubes that try to place it and break the chunks in the process (for future generations to come)

Game Breaking issues / ASTRAL SOCERY + EMC 
While copying Rock Crystals is fine ,copying Lens and Prism Lense isnt. I suspect the actual crafting process to add nbt data or call other functions that are left out when a lense or Prism Lense are copied by transmutation table .
The placement of the lenses crashes the game, the connection of the lense to the altar corrupts the chunk completly 

Major Issues (no game crash, but possible complete item loss) /Applied Energetics 2, Equivalent Exchange, Reborn Storage, Refined Storage:
All of these mods have storage parts and crafted cells both have emc while the parts contain no issue, the coping of actual cells/disk corrupts the disk itsself since NBT data is added while crafted and that is skipped when copying the following list contains all problematic items:

Refined Storage/Reborn Storage:
- 1k storage disk
- 4k storage disk
- 16k storage disk
- 64k storage disk
- 256k storage disk
- 1024k storage disk
- 4096k storage disk
- 16384k storage disk

- 1k fluid storage disk
- 4k fluid storage disk
- 16k fluid storage disk
- 64k  fluid storage disk
- 256k fluid storage disk
- 1024k fluid storage disk
- 4096k fluid storage disk
- 16384k fluid storage disk

Applied Energetics :

- 1k ME storage cell
- 4k ME storage cell
- 16k ME storage cell
- 64k ME storage cell
- 1k ME Fluid storage cell
- 4k ME Fluid storage cell
- 16k ME Fluid storage cell
- 64k ME Fluid storage cell
-2³ spatial Storage Cell
- 16³ Spatial Storage Cell
-128³ Spatial Storage Cell

Equivalent Exchange :
- Tier 1 Emc Storage Cell
- Tier 2 Emc Storage Cell
- Tier 3 Emc Storage Cell
- Tier 4 Emc Storage Cell
- Tier 5 Emc Storage Cell
- Tier 6 Emc Storage Cell
- Tier 7 Emc Storage Cell
- Tier 8 Emc Storage Cell

## Reproduce Steps

Astral Socery : 
- copy Lense or Prism Lense with EMC and place them on an alter to crash the game
- connect these corrupted items to the altar to permantly (until the items gets removed) damage the containing chunks 

Chance Cube:
Open up a chance cube that contains the fluid behavior to permantly corrupt the chunk  when Essence corresponding fluids are placed (Fluid XP and Essence of knowledge

EE,RS,RS,AE2 : 
copy a fully crafted storage cell from any of these mods and put them in thier respective system, sometimes it crashes the games, sometimes nothing happens ,sometimes it deletes the entire storage.

**Comment by scalda** [comment]
thanks for this i will sort out for 1.5.1
