### ISSUE TITLE
Breaking mob Fans somethimes makes me crash in Multiplayer (have not tried in singleplayer)

### ISSUE THREAD

**Issue by TheMurlocMaster** [scalda/Foolcraft_3#237]
## Issue Description
Breaking Mob fans somethimes makes the game crash. I am hosting in multiplayer. Everything turns blue whenever this happends.

## Reproduce Steps
Place and break a couple of mob fans. My coplayer was the one breaking them, though i doubt this will change whether it crashes or not

## Additional Information
Playing multiplayer LAN in Norway, very consistant crashing, screen turns blue upon crash. This is my first report, so i have probably done something wrong. please respond if i missed anything

**Comment by itskdog** [comment]
Can you provide the crash log, preferably via a pastebin link?

**Comment by MultipleMean150** [comment]
We've found that breaking mob fans will cause a crash.  If you need to break them, I suggest you do it in creative.

**Comment by scalda** [comment]
update to Beta 1.5 and test, Please report back and close the issue if it's solved. i will close in 7 days if not responded to or not closed before hand
