### ISSUE TITLE
Immersive Engineering Fluid pipe crash

### ISSUE THREAD

**Issue by Jopocalypse** [scalda/Foolcraft_3#238]
## Issue Description
I connected a Immersive engineering pipe to an Ender IO pipe

## Reproduce Steps
I was making a power system and I wanted to switch to Immersive engineering fluid pipes instead of using ender IO pipes. When I connected the pipes the game crashed and wont let me join back in. the ender IO pipe was connected to three magma generators

 The game crashed whilst unexpected error
The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Unexpected error

**Comment by scalda** [comment]
Yes there is a render issue with IE when fluid pipes connect to an ender io pipe we have had this happen quite abit latly

**Comment by Jopocalypse** [comment]
I fixed my server by rolling it back but it really messed up my game. Is
there anyway to put like an alert so other people don't do it?

**Comment by nzminecraftDOTcom** [comment]
if you want to save your players effort for having to roll back, you can manually delete the block causing the issue by reading the crash report, and seeing what the location of the offending block is, going to https://dinnerbone.com/minecraft/tools/coordinates/ and entering the coords in there, locating the chunk that those coords match to, opening the regions file for your world and navigating to the region those chunks are in (shows this at the bottom of the web link when coords are entered) open that region file in an NBT editor, and edit the chunk manually. Takes a bit of time but saves you having to roll-back to previous working versions and everybody losing their stuff. Saved me a few times when that sort of crash has been happening.

Alternatively you can install world edit, //pos1 [x,y,z] //pos2 [x,y,z] and set that block to air. IF you can load the world. (say you were at the spawn point and could still get in without it crashing)

**Comment by scalda** [comment]
update to Beat 1.5 and test, Please report back and close the issue if it's solved. i will close in 7 days if not responded to or not closed beforehand

**Comment by scalda** [comment]
this is now working fine in 1.5
