### ISSUE TITLE
Energy Cells from Thermal Expansion, Crafting Recipe Not Showing.

### ISSUE THREAD

**Issue by ghost** [scalda/Foolcraft_3#240]
## Modpack Information

In JEI, while trying to view the crafting recipes for the Energy Cells Basic, Reinforced, and Resonant (essentially all three energy cell blocks), the crafting recipe to make them does not register. Clicking the keybind to "Show Recipe" does not show the recipe needed to make the cell. No error is thrown into the output log, the game does not freeze, nor any other noticeable effects; it simply doesn't show the recipe.

To reproduce, try and view the recipe for any energy cell from Thermal Expansion in JEI.

## Additional Information
Using latest release version of Foolcraft 3 Release-1.4.5

**Comment by nzminecraftDOTcom** [comment]
You must use an upgrade kit or a conversion kit to upgrade to the next level of energy cell, similar to how you would a redstone furnace from basic to hardened/resonant etc.

**Comment by scalda** [comment]
what @nzminecraftDOTcom said
