### ISSUE TITLE
Carpenter's slopes not placing upside down

### ISSUE THREAD

**Issue by joshschriger** [scalda/Foolcraft_3#241]
## FEATURE REQUEST
- [ ] I would like to propose an additional mod.
- [ ] I would like to propose a config change.
- [ ] I would like to propose a custom recipe.
- [x] I would like to propose another change.

<!-- FEATURE INFORMATION - Please explain what you want changed/added and why.

**Comment by joshschriger** [comment]
[https://gyazo.com/37be00d3cf7073590d0dc824c77bfce3](url)
found this in the mod list

**Comment by scalda** [comment]
the mod is still alpha version so somethings may not work with them
