### ISSUE TITLE
Stoneburnt

### ISSUE THREAD

**Issue by Kensuga** [scalda/Foolcraft_3#242]
## Description:
Viewing the crafting recipes that can be crafted with stoneburnt, on the attempt to open the 4th page, the game will crash.

## Steps:
1. Search Stoneburnt
2. View Crafting Recipes
3. Navigate to the 4th page.

 

## Additional Information
Crash Report: 
https://pastebin.com/6770jGVv

**Comment by Mrbysco** [comment]
Please fill in the current version of foolcraft 3 that you are playing and maybe supply a crash report

**Comment by Kensuga** [comment]
Updated post with the version and a pastebin with the crash report

**Comment by scalda** [comment]
update to Beat 1.5 and test, Please report back and close the issue if it's solved. i will close in 7 days if not responded to or not closed before hand

**Comment by Kensuga** [comment]
I cant check cause of a bug im experiencing, which I reported on another post

**Comment by scalda** [comment]
this issue will be fixed in 1.5.1 due to mod updates
