### ISSUE TITLE
Chisel and Bits Config Change

### ISSUE THREAD

**Issue by theBluebaerry** [scalda/Foolcraft_3#243]
## FEATURE REQUEST
- [ ] I would like to propose an additional mod.
- [x ] I would like to propose a config change.
- [ ] I would like to propose a custom recipe.
- [ ] I would like to propose another change.

## FEATURE INFORMATION

Having just updated from 1.3.1 to 1.4.5 I have noticed that I can no longer remove bits using a bit, I have to scroll to a chisel in order to break incorrectly placed bits. I was just wondering if this is an intended change and if so would it be possible to change it back, or could you please let me know the config options that I need to edit in order to have it the way it was before. 
As someone who uses chisel and bits a LOT (It's pretty much all I do in this modpack) it is very frustrating and time consuming not being able to break bits with bits, seeing as its very easy to misplace bits. Thanks!

**Comment by theBluebaerry** [comment]
Also just FYI you have a "-->" missing from your template. Spent ages trying to figure out why my text wasn't appearing, was worried some smartie was going to comment "please fill out the template properly" before I could fix your template...

**Comment by scalda** [comment]
This is a bug in the current release of chisel and bits it has already been reported but thanka

**Comment by theBluebaerry** [comment]
Ah thank you, I did look for it but couldn't find anything. Sorry for the duplicate :)
