### ISSUE TITLE
Crash when opening any inventory

### ISSUE THREAD

**Issue by ScottDWebster** [scalda/Foolcraft_3#244]
## Issue Description

I am running Foolcraft 3 1.4.5 via MultiMC on Linux.
This is the second time where the game gets into a weird state where opening any inventory / item gui crashes the game.  The problem persists even after restarting the game.

## Reproduce Steps
Open any inventory or gui in game.

## Additional Information
Crash data: https://pastebin.com/x0ZGFMwx

**Comment by sebi2306** [comment]
Looks to be some shenanigans occurring between Carpenter's Blocks and JEI. For now, adding the mod to JEI's Blacklist seems to fix it.
`S:itemBlacklist < carpentersblocks >`
The Blacklist is located at [install folder]\config\jei\itemBlacklist.cfg

**Comment by scalda** [comment]
update to Beat 1.5 and test, Please report back and close the issue if it's solved. i will close in 7 days if not responded to or not closed before hand
