### ISSUE TITLE
Items not going to hotbar when picked up

### ISSUE THREAD

**Issue by NickTwoPointOh** [scalda/Foolcraft_3#246]
## Issue Description
**Items picked up go into back of inventory when there is space for them to be put on the hotbar.** 

## Reproduce Steps
**I can relog, restart, even re download the pack and the issue continues. I have created test worlds normal worlds and same issue with items not going into hot bar. I have looked around into the configs of inventory tweaks but I’m not the most tech savvy and I did not find any option under my description to change.** 

## Additional Information
**Sorry if this was a dumb post but it is killing my enjoyment of the game. This only happens on my singleplayer world so switching from my server to my single player game really messes up the game for me. **

**Comment by Revvilo** [comment]
Check to see if you have `Sort on pickup` enabled for Inventory Tweaks (the litte `...` in the corner of your inventory then under `more options`)
My game turned this on randomly, too, and it caused the same thing... although when I turn it on now it doesn't do anything, but hopefully this'll help.

**Comment by NickTwoPointOh** [comment]
It worked thanks man.
