### ISSUE TITLE
My game keeps crashing on launch.

### ISSUE THREAD

**Issue by Cethannel** [scalda/Foolcraft_3#247]
## Issue Description
Every time I launch the game it crashes shortly into the start process.

## Reproduce Steps
Cannot be replicated off my computer, but happens every time I launch the pack.

## Additional Information
I installed optifine, but even when I deleted it I had the same problem.

Crash report : https://pastebin.com/yarPJMdk

**Comment by Mrbysco** [comment]
Try reinstalling the pack

**Comment by Mrbysco** [comment]
something messed up in codechickencores config and caused it to be corrupt causing it to crash. Must've been a faulty download

**Comment by Cethannel** [comment]
Thank you I will try that and get back to you

**Comment by Cethannel** [comment]
It worked thank you very much.

**Comment by Mrbysco** [comment]
No problem :)
