### ISSUE TITLE
Alteration of terrain generation

### ISSUE THREAD

**Issue by Sn3akr** [scalda/Foolcraft_3#249]
## FEATURE REQUEST
- [ ] I would like to propose an additional mod.
- [x] I would like to propose a config change.
- [ ] I would like to propose a custom recipe.
- [ ] I would like to propose another change.

<!-- FEATURE INFORMATION - Please explain what you want changed/added and why.

**Comment by Sn3akr** [comment]
I just started a world yesterday on the newest release 1.4.5 and after a full day of mining and setting up shop i was prepared to move up the tech tree.. That was until i went looking for sand.. I had to travel more than 2500 blocks to locate a beach, other than that i only found small patches of sand containing 30-40 block of sand at most, and for my long travel i only saw, plains, forest, magical forest, taiga and extreme hills, all repeated several times during the trip. Either i got EXTREMELY unlucky with my seed (-76274265178007719756) or the mod responsible for world gen needs a bit of tweaking unless your supposed to produce everything from cobble and dirt (didn't take this as a "skyblock" pack. ) Will try a new world, but i'll have to preload to figure if it's the same boring repetitive pattern befor i start actual playing.
Did a 2nd world and flew in circles spiraling out til i hit the first larger patch of sand... 2467 blocks from spawn! Looks like if you don't get a lucky spawn (seed) then HUUUGE continents can make simple resources in short supply and make for VERY tedious exploring for even simple things.. OR.. Go the skyblock route and create everything yourself, which kinda makes the point of terrain generation seem stoopid.

EDIT:  With the 4th world i got a playable world where i didn't spawn in the middle of a several 1000 blocks wide continent of repeating woods/plains. but still annoying having to spend hours pregenerating to not get the most boring/annoying world gen.

**Comment by scalda** [comment]
I am sorry to hear that you have had bad luck for finding sand. but since this is the only issue I am seeing in regards to this i can't see me spending the time redoing the biome weighting as that is a very long and very tedious process. i am sorry for the in convenience
