### ISSUE TITLE
Extra Utilities 2 Chunk Loading Ward no craftable

### ISSUE THREAD

**Issue by melbellrocks** [scalda/Foolcraft_3#25]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

Running the latest version of FoolCraft 3 on a server and I am unable to craft the Chunk Loading Ward from Extra Utilities 2.  I have also tried it in an single player world and it doesn't work there either.  The recipe doesn't show up when I click on the item in JEI in either multiplayer or singleplayer.

I ran a single player world with ONLY Extra Utilities 2 and JEI and was able to both see the recipe and craft it successfully.

And yes I'm using a villager that was signed to a contract.

EDIT:  Our config option is set to B:ChunkLoader=true

https://imgur.com/SSk0WpE

**Comment by lemonyslash** [comment]
Hi there. 

FC3 makes use of the Weirding Gadget for loading chunks for server friendly chunk loading:

https://minecraft.curseforge.com/projects/the-weirding-gadget
