### ISSUE TITLE
Crashing on starting up

### ISSUE THREAD

**Issue by PGamerMC** [scalda/Foolcraft_3#250]
## Issue Description
I haven't played FoolCraft 3 ever. I install it via Twitch Launcher and when I press the "PLAY" button  the Minecraft Launcher opens I press play and in the second phase of loading it crashes.

## Reproduce Steps
I don't know if it's possible to reproduce it from another computer beacause maybe it's my fault, but anyway what I do is the usual, install and play

## Additional Information

https://pastebin.com/SdSTjirH

I use a HP laptop with intel i3 core, total 12GB Ram and 6GB allocated and a Samsung Solid State Drive.
I use the latest version of the pack.
Sorry for bad English.
I tried deleting the mods that seem to have a problem, but I don't want to delete half the pack :P 
I tried installing again and again as well as restarting the computer.
I had the exact same problem (with other mods)  in other modpacks, if that helps.
If you have any question, I will be happy to answer.

**Comment by scalda** [comment]
update to Beat 1.5 and test, Please report back and close the issue if it's solved. i will close in 7 days if not responded to or not closed before hand

**Comment by PGamerMC** [comment]
I will check in a couple of days and I will answer immidiately

**Comment by scalda** [comment]
thanks

**Comment by PGamerMC** [comment]
Problem Was not fixed I updated to 1.5 and it still crashes on AE2 stuff

**Comment by scalda** [comment]
@PGamerMC have you tried a clean install of the pack,

According to your crash report, you are only using 3GB Ram instead of the 6GB you stated to be using. Also, Try updating your Java version
also try updating your GPU drivers as well
and make sure that Minecraft is using the dedicated graphics in your computer instead of the intel CPU ones

**Comment by PGamerMC** [comment]
I kinda solved it. I just deleted ae2 stuff and advanced generators. I can  play at least.

**Comment by scalda** [comment]
ok then i will close the issue
