### ISSUE TITLE
[LAUNCHING] Error given while launching

### ISSUE THREAD

**Issue by peakcardinal6** [scalda/Foolcraft_3#251]
## Modpack Information
<!-->
* Current Pack Version: Release-1.4.5
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [x] In single player
     - [x] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
There isn't much to say other than upon pressing "play" on the minecraft launcher it gives the error of "The game directory is invalid or inaccessible.
Error details: The system cannot find the file specified
Filename on disk: .
Path: C:\Users\user\My Documents\Curse\Minecraft\Instances\FoolCraft 3\
Exists: directory"
 I'm not sure what it is looking for, and this happened ever since I downloaded it.

## Reproduce Steps:
 Press "play" on twitch launcher to open minecraft launcher, and then press "play"

## Additional Information
Does it with all versions of foolcraft, so im not sure if it is just something with my installing with twitch.

**Comment by nzminecraftDOTcom** [comment]
Check that the directory you mentioned above in the description exists, all the way to the Foolcraft3 folder, if it doesn't, try running the curse launcher as administrator and installing Foolcraft 3 again.

**Comment by peakcardinal6** [comment]
https://gyazo.com/3fb05bc84498bda737eb9baad3e2dddd
Its all there

**Comment by nzminecraftDOTcom** [comment]
Check your launch options for the FC3 instance
When you go to click play the 2nd time, instead click "Launch Options" at the top, find the Foolcraft 3 one, click that. Check the game directory matches what you have above. If not, make sure it's using that directory.

**Comment by peakcardinal6** [comment]
It does. I've even set it to that before and gotten the same thing

**Comment by peakcardinal6** [comment]
IF, you make it so you cant change game dictionary it tries going to C:\Users\user\My Documents\Curse\Minecraft\Install with the error message of "The game directory is invalid or inaccessible.
Error details: The system cannot find the file specified
Filename on disk: Install
Path: C:\Users\user\My Documents\Curse\Minecraft\Install
Exists: directory

**Comment by nzminecraftDOTcom** [comment]
C:\Users\user\Documents\Curse\Minecraft\Instances\FoolCraft 3\

Try that directory.

**Comment by peakcardinal6** [comment]
Unable to locate the Java runtime.
Error details: The system cannot find the file specified
Filename on disk: javaw.exe
Path: C:\Users\user\My Documents\Curse\Minecraft\Install\runtime\jre-x64\1.8.0_51\bin\javaw.exe
Exists: file

Now getting that error

**Comment by peakcardinal6** [comment]
I can show you my screen on discord or something if you need it

**Comment by nzminecraftDOTcom** [comment]
What are the JVM arguments in the launch options where you just set the game directory? I may reply a little late as I have to be at work shortly.

**Comment by peakcardinal6** [comment]
-Xmx3072m -Xms256m -XX:PermSize=256m -Dminecraft.applet.TargetDirectory="C:\Users\user\My Documents\Curse\Minecraft\Instances\FoolCraft 3" -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -Duser.language=en -Duser.country=US

**Comment by peakcardinal6** [comment]
Anyone know how to fix the problem?

**Comment by peakcardinal6** [comment]
Anyone know how to fix the problem?

**Comment by nzminecraftDOTcom** [comment]
Do you have java installed?
Check that.

**Comment by Mrbysco** [comment]
Try following this tutorial on using the Jar launcher because then you're able to specify what java you wanna use (assuming you actually have java installed)
(This also fixes the a Immersive Engineering crash due to it depending on newer java features)

https://www.iskall85.com/forum/m/37727173/viewthread/32016029-immersive-engineering-java-fix/page/1

**Comment by peakcardinal6** [comment]
By the way, I do have the latest java installed. (did that a couple days ago)

**Comment by nzminecraftDOTcom** [comment]
Java or java runtime environment?

**Comment by peakcardinal6** [comment]
Sorry for not responding, I havent been active much recently. And to answer your question I do not know. I had a thing asking to update to newest java, so i did. Not sure how to check.

**Comment by nzminecraftDOTcom** [comment]
Best way to check is just install it. Go to http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html select the Java version that best suits your computer x64 64bit or x86 32bit. Try again after installing it and restarting your computer.

**Comment by peakcardinal6** [comment]
Is it needed, if I was able to run foolcraft the way Mrbysco did? The only problem was it would freeze at "finishing up (6/7)"

**Comment by nzminecraftDOTcom** [comment]
You don't have to if it works his way. Make sure you've allocated enough memory (RAM) in the launcher settings. 6gb minimum is their recommendation. 8gb will see you playing quite comfortably

**Comment by peakcardinal6** [comment]
I had about 6 gb allocated but ill do more later today. Not sure if it will help, but im putting in another hardrive for more space soon because I only have about 4gbs of space on my computer

**Comment by nzminecraftDOTcom** [comment]
Try clearing some space and then starting the game again. That may be the cause.

**Comment by scalda** [comment]
i will close in 7 days if not responded to or not closed beforehand
