### ISSUE TITLE
Advanced coil recipe broken 1.3.1

### ISSUE THREAD

**Issue by nzminecraftDOTcom** [scalda/Foolcraft_3#252]
## Issue Description
Advanced coil recipe from Actually Additions fails to give item. Item displays but can not be taken.

## Reproduce Steps
8 Gold nuggets surrounding a Basic Coil from actually additions in a crafting table of any kind. Try take the item you are wanting to craft.

**Comment by scalda** [comment]
Hi this is working fine for me 

update to Beta 1.5 and test, Please report back and close the issue if it's solved. i will close in 7 days if not responded to or not closed before hand
