### ISSUE TITLE
Adding galacticraft

### ISSUE THREAD

**Issue by NadosCS** [scalda/Foolcraft_3#255]
## FEATURE REQUEST
- [ X] I would like to propose an additional mod.
- [ ] I would like to propose a config change.
- [ ] I would like to propose a custom recipe.
- [ ] I would like to propose another change.

## MOD INFORMATION
Galacticraft https://micdoodle8.com/mods/galacticraft

**Comment by TheMajesticPickle** [comment]
Bad idea, galacticraft and its addons are very resource intensive, and most of galacticraft is a very grindy process which would take away from the idea of the pack

**Comment by scalda** [comment]
yeah this won't be added sorry
