### ISSUE TITLE
My absence of late with foolcraft and other minecraft based content.

### ISSUE THREAD

**Issue by scalda** [scalda/Foolcraft_3#256]
To all that reads this,  The reason for me being so inactive atm is due to the high heat we have had/is in the UK the last couple weeks which makes it unbearable for me to sit in my bedroom at the computer. Thursday it reached 41c according to my weather station before it dropped off for these last couple of cool days around the 20c mark but with that, I have had to do stuff around the house and garden. So sorry things are taking longer than expected. 

I am also in the plans of converting a caravan to an office to help mitigate these issues I am having which is preventing me from dedicating as much time to the community I manage and also my youtube/Twitch channels that people support me for, once my office is complete things will change and things may move very quickly as I will have the time to sit and plan then implement the ideas I have across the board. 

Well thanks for ready and please enjoy the rest of your day

Regards

Scalda

**Comment by xGarionx** [comment]
Understandable reasons (thx in general for the information btw).
Still have to ask, is there another version of the modpack comming that removes the current issues, or is the break and the absence of content from the hermits of this modpack /1.13 version of minecraft an early death to the update circle/modpack ?

**Comment by scalda** [comment]
I have a beta version ready for release I just need to package it

**Comment by xGarionx** [comment]
Looking forward to it in special for the ultimate emc condenser, i really need that 10M dirt (ok honestly i just need an excuse to use stupid amounts of emc cells thats all)

**Comment by scalda** [comment]
@xGarionx 1.5 beta is availible

**Comment by scalda** [comment]
The start to my new office if anyone is interested in seeing this. I thought i'd post it here since i work on foolcraft and have been absent of late and i wanted to show you all the start to my future plans to better that

This will allow me to be more productive 1 with foolcraft and 2 with everything else i have my hands in

https://t.co/P2nPpDY8Bd

**Comment by scalda** [comment]
Update i started a Gofundme to get my new office completed faster to allow me to work better on things including foolcraft https://www.gofundme.com/the-carastudio
