### ISSUE TITLE
Crash with Long error, Not sure what is actively crashing my game.

### ISSUE THREAD

**Issue by jorblax** [scalda/Foolcraft_3#257]
## Issue Description
After loading into the server, anywhere between five and ten minutes my game crashes with this error.
"The game crashed whilst unexpected error
Error: java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[down, up, north, south, west, east]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}"

## Reproduce Steps
I can't actively reproduce it, But I have crashed 8 or 9 times today, However I can supply a crash report.

## Additional Information

https://pastebin.com/dRY9ksqH

**Comment by Mrbysco** [comment]
It's the mob grinding utils fan. this has been reported already

**Comment by Mrbysco** [comment]
https://github.com/scalda/Foolcraft_3/issues/201

**Comment by jorblax** [comment]
Oh, my bad. I couldn't find reference anywhere, I'm just a noob. Ty.
