### ISSUE TITLE
ThermalFoundation Error

### ISSUE THREAD

**Issue by 3OL** [scalda/Foolcraft_3#258]
## Issue Description
 So i just started Foolcraft 3 regulary on the twitch launcher. Then i started it and crashed and this error log showed upp: 
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Thermal Foundation (thermalfoundation)

**Comment by scalda** [comment]
update to Beat 1.5 and test, Please report back and close the issue if it's solved. i will close in 7 days if not responded to or not closed before hand
