### ISSUE TITLE
CPU hungry resulting in lag spikes

### ISSUE THREAD

**Issue by Wanjiaa** [scalda/Foolcraft_3#259]
## Issue Description

I'm playing the game on singleplayer, something with open LAN both has the same problem.
I've come to the conclusion that for some reason the client will use little by little more CPU memory until it hits 97% it will give me a lag spike and drop down to ~68% on lowest settings and ~72% on normal settings. - still happens when foolcraft 3 is the only process running -
I allowed foolcraft 3 to use up to 8g ram as I have had issues with low ram with other modpacks but doesn't seem to fix the problem as it only uses a steady 4g RAM.

In my few years of hosting servers for friends with my PC, I can say this is the first time I've ever had any modpack being CPU hungry.

## Reproduce Steps

Wait in the world until the memory is close to full.
Looking around a lot will cause it faster

## Additional Information

In-game memory at the time of giving a lag spike
http://prntscr.com/ke1pyx

Doing nothing in the world CPU screen
http://prntscr.com/ke1vwd

**Comment by nzminecraftDOTcom** [comment]
Just to clarify, that is not "CPU memory" It's CPU utilization, a CPU will not store information. 
Second, have you got anything running in the background, have you got chunkloaded areas of your map that have intensive machines running in them, or have you got machines at your main base that are processing lots.

**Comment by scalda** [comment]
that is your ram client side you need to increase it to at least 6GB to run foolcraft. you are only running 3GB

**Comment by scalda** [comment]
will close in 7 days

**Comment by Wanjiaa** [comment]
Fresh startup from windows only opening the modpack seemed to fix it and now it runs with other things open. I already said that I allocated 8GB, not 3. Could it be possible it didn't give 8GB until windows restart?

**Comment by Mrbysco** [comment]
Your screenshot says it's 3gb allocated 
![afbeelding](https://user-images.githubusercontent.com/9308260/44031378-1b938e30-9f04-11e8-8de3-5574661da0f3.png)
As you can see a max of 2929 which is closer to 3gb then it is to 8.

**Comment by Wanjiaa** [comment]
I didn't figure that was ram since I allocated 8GB and that's why I posted this thinking it was cpu
