### ISSUE TITLE
Not getting diamonds from builder quarry

### ISSUE THREAD

**Issue by lemonyslash** [scalda/Foolcraft_3#26]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

I've run my Builder quarry on two different 8 chunk areas, but haven't seen a single glimpse of diamonds. I tried running a Builder in Single player at it worked fine. I got around 30 diamonds.

Run a Builder quarry, with a normal shape card, on the FC3 Emerald server.

**Comment by scalda** [comment]
you may just be unlucky or someone had already gone through underground and cleared the area

**Comment by lemonyslash** [comment]
Not plausible.

There should be 1 diamond ore vein per chunk (I mined 8). I'm pretty far from spawn and tried a second time 100 chunks away (another 8). If I mine by hand I do find diamonds. I just don't get them with the builder. 

I'll just find some other way to quarry, but still weird. xD Of course, it would be better if someone could test and corroborate the issue.
