### ISSUE TITLE
Pressing Tab to Autofill Commands and Names in Chat Unequips Jet Packs

### ISSUE THREAD

**Issue by ckenward** [scalda/Foolcraft_3#261]
## Issue Description
While in the chat window, pressing tab unequips and upon consequential presses equips any Simply Jet packs Jet pack. 
If left in the pseudo unequipped state, the jet pack throws itself on the ground upon opening any sort of inventory other than your own.
Upon opening the players inventory the jetpack appears to have been picked up by the cursor and can be manipulated.

## Reproduce Steps
1. Have a Simply Jetpacks Jetpack Equipped
2. Open chat window
3. Begin to enter a command or username (or enter nothing at all)
4. Press tab to autofill a command or username
5. Repeat to toggle equipped to unequipped back and forth

## Additional Information
If the autofill is unsuccessful (like when using a command or name that doesnt exist) the jetpack will not unequip itself.
The problem may be dependent on hover mode as it does not happen sometimes when hover is not enabled.
The problem does not seem to be dependent on whether the user is flying or not.

**Comment by scalda** [comment]
you need to check your key binds if this is happening to you, please respond or close.

I will close this in 7 days if no response is recived
