### ISSUE TITLE
The pack will not launch

### ISSUE THREAD

**Issue by HunterMeredith** [scalda/Foolcraft_3#262]
## Issue Description
I haven't played the pack before. I download it from the twitch launcher and it immediately crashes as soon as I click play in the minecraft launcher

## Reproduce Steps
all I did to produce this issue was download and attempt to launch the pack. I have a dell g7 laptop with 16 gigs of ram, 10 are allocated to minecraft.

**Comment by nzminecraftDOTcom** [comment]
Can you post a crash report since it's crashing?

**Comment by HunterMeredith** [comment]
Couldn't get hash for org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar from https://modloaders.forgecdn.net/647622546/maven/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar.sha1: HTTP 403: Forbidden
--
15:28:34 | launcher | main | warn | Have local file C:/Users\hunte\Documents\Curse\Minecraft\Install\libraries\org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar but don't know what size or hash it should be. Have to assume it's good.
15:28:34 | launcher | main | warn | Have local file C:/Users\hunte\Documents\Curse\Minecraft\Install\libraries\org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar but don't know what size or hash it should be. Have to assume it's good.
15:28:34 | launcher | main | warn | Couldn't get hash for org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar from https://modloaders.forgecdn.net/647622546/maven/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar.sha1: HTTP 403: Forbidden
15:28:34 | launcher | main | warn | Have local file C:/Users\hunte\Documents\Curse\Minecraft\Install\libraries\org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar but don't know what size or hash it should be. Have to assume it's good.
15:28:34 | launcher | main | warn | Couldn't get hash for org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar from https://modloaders.forgecdn.net/647622546/maven/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar.sha1: HTTP 403: Forbidden
15:28:34 | launcher | main | warn | Have local file C:/Users\hunte\Documents\Curse\Minecraft\Install\libraries\org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar but don't know what size or hash it should be. Have to assume it's good.
15:28:34 | launcher | main | warn | Couldn't get hash for org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar from https://modloaders.forgecdn.net/647622546/maven/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar.sha1: HTTP 403: Forbidden
15:28:34 | launcher | main | warn | Couldn't get hash for org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar from https://modloaders.forgecdn.net/647622546/maven/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar.sha1: HTTP 403: Forbidden
15:28:34 | launcher | main | warn | Have local file C:/Users\hunte\Documents\Curse\Minecraft\Install\libraries\org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar but don't know what size or hash it should be. Have to assume it's good.
15:28:34 | launcher | main | warn | Have local file C:/Users\hunte\Documents\Curse\Minecraft\Install\libraries\org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar but don't know what size or hash it should be. Have to assume it's good.
15:28:34 | launcher | main | warn | Couldn't get hash for org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar from https://modloaders.forgecdn.net/647622546/maven/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar.sha1: HTTP 403: Forbidden
15:28:34 | launcher | main | warn | Have local file C:/Users\hunte\Documents\Curse\Minecraft\Install\libraries\org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar but don't know what size or hash it should be. Have to assume it's good.
15:28:34 | launcher | main | warn | Couldn't get hash for 1.12.2 jar from https://s3.amazonaws.com/Minecraft.Download/versions/1.12.2/1.12.2.jar.sha1: HTTP 403: Forbidden
15:28:34 | launcher | main | warn | Have local file C:/Users\hunte\Documents\Curse\Minecraft\Install\versions\1.12.2/1.12.2.jar but don't know what size or hash it should be. Have to assume it's good.
15:28:35 | launcher | main | info | Checking installations.
15:28:35 | launcher | main | info | Minecraft client forge-14.23.4.2705 is ready to start.
15:28:35 | launcher | main | info | Starting!
15:28:35 | launcher | main | info | Using default game log configuration client-1.12.xml (outputs XML)
11:28:36 | game |   | error | 2018-08-07 15:28:36,457 main WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream   <log4j:Event logger="LaunchWrapper" timestamp="1533670116530" level="INFO" thread="main">     <log4j:Message><![CDATA[Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker]]></log4j:Message>   </log4j:Event>
11:28:36 | monitor | Process Monitor | error | expected <
15:28:36 | LaunchWrapper | main | info | Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
15:28:36 | LaunchWrapper | main | info | Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
15:28:36 | FML | main | info | Forge Mod Loader version 14.23.4.2705 for Minecraft 1.12.2 loading
15:28:36 | FML | main | info | Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at C:\Users\hunte\Documents\Curse\Minecraft\Install\runtime\jre-x64\1.8.0_51
15:28:36 | FML | main | info | Searching C:\Users\hunte\Documents\Curse\Minecraft\Instances\FoolCraft 3 (1)\mods for mods
11:28:36 | game |   | error | 2018-08-07 15:28:36,885 main WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream 2018-08-07 15:28:36,890 main WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream   <log4j:Event logger="FML" timestamp="1533670116898" level="WARN" thread="main">     <log4j:Message><![CDATA[The coremod org.minimallycorrect.libloader.LibLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft]]></log4j:Message>   </log4j:Event>
11:28:36 | monitor | Process Monitor | error | expected <
15:28:36 | FML | main | warn | The coremod LibLoader (org.minimallycorrect.libloader.LibLoader) is not signed!
15:28:37 | LibLoader | ForkJoinPool.commonPool-worker-4 | info | Downloading library me.nallar.whocalled.WhoCalled-1.1 from https://jcenter.bintray.com/me/nallar/whocalled/WhoCalled/1.1/WhoCalled-1.1.jar. Expected hash: 6d4275e1b41ba7ce297ccb00db0afda0e5add3e07aea80220550d11a90d9a1fe01340d3f44c7d9fe67f463c96a0a6df233a28df882515bb05834868cdcdbc04f
15:28:37 | LibLoader | ForkJoinPool.commonPool-worker-3 | info | Downloading library org.javassist.javassist-3.22.0-CR1 from https://jcenter.bintray.com/org/javassist/javassist/3.22.0-CR1/javassist-3.22.0-CR1.jar. Expected hash: 1a955bad6b2755153f5abb8ee808b4ac002dc26f8d9c391ebba5d6743d5dd06efc2a1dcb70e5eac0396696f7583ea89f6b5d8c05f971f54f2d56a12a2bb50e82
15:28:37 | LibLoader | ForkJoinPool.commonPool-worker-1 | info | Downloading library com.eclipsesource.minimal-json.minimal-json-0.9.4 from https://jcenter.bintray.com/com/eclipsesource/minimal-json/minimal-json/0.9.4/minimal-json-0.9.4.jar. Expected hash: e9bbb53aa9c4b8275866a71e9bd83b0d7f64ac2d9417b52159c5b304807e73fef37f0c2eec03c00c6edf8b7c29ea20bf0bc5d30c644ad5ed033a3963296fa086
15:28:37 | LibLoader | main | info | Downloading library com.github.javaparser.javaparser-core-3.2.4 from https://jcenter.bintray.com/com/github/javaparser/javaparser-core/3.2.4/javaparser-core-3.2.4.jar. Expected hash: e9ecfe1bd5b9e0532d88093ba565e1420a694b10353243e1c9ba0a32c2aa5a743442df532deb5deeb6d8ab1c3c541e440cc57f1d64b86263e4b1207ed6c12163
15:28:40 | LibLoader | main | info | Downloading library org.json.json-20090211 from https://jcenter.bintray.com/org/json/json/20090211/json-20090211.jar. Expected hash: ea18db6a9b2db4753bbabfde3ebf2159c0bb71dc8ac5f8a7b6ace9666b0b82a04927952db7c9285ace05301bd2cee289d8ba022a4229550de6ba0099659a37d7
15:28:40 | LibLoader | main | info | Found libs: [com.eclipsesource.minimal-json.minimal-json-0.9.4 org.javassist.javassist-3.22.0-CR1 org.minimallycorrect.modpatcher.ModPatcher-1.12-SNAPSHOT org.minimallycorrect.mixin.Mixin-1.0-SNAPSHOT com.github.javaparser.javaparser-core-3.2.4 org.json.json-20090211 me.nallar.whocalled.WhoCalled-1.1 me.nallar.JavaPatcher-1.8 org.minimallycorrect.javatransformer.JavaTransformer-1.8-SNAPSHOT]
15:28:40 | LibLoader | main | info | Current LaunchClassLoader URLs: [file:/C:/Users/hunte/Documents/Curse/Minecraft/Install/libraries/net/minecraftforge/forge/1.12.2-14.23.4.2705/forge-1.12.2-14.23.4.2705.jar file:/C:/Users/hunte/Documents/Curse/Minecraft/Install/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar file:/C:/Users/hunte/Documents/Curse/Minecraft/Install/libraries/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar file:/C:/Users/hunte/Documents/Curse/Minecraft/Install/libraries/jline/jline/2.13/jline-2.13.jar file:/C:/Users/hunte/Documents/Curse/Minecraft/Install/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar file:/C:/Users/hunte/Documents/Curse/Minecraft/Install/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar file:/C:/Users/hunte/Documents/Curse/Minecraft/Install/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar file:/C:/Users/hunte/Documents/Curse/Minecraft/Install/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar file:/C:/Users/hunte/Documents/Curse/Minecraft/Install/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar file:/C:/Users/hunte/Documents/Curse/Minecraft/Install/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar file:/C:/Users/hunte/Documents/Curse/Minecraft/Install/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar file:/C:/Users/hunte/Documents/Curse/Minecraft/Install/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar file:/C:/Users/hunte/Documents/Curse/Minecraft/Install/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar file:/C:/Users/hunte/Documents/Curse/Minecraft/Install/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar file:/C:/Users/hunte/Documents/Curse/Minecraft/Install/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar file:/C:/Users/hunte/Documents/Curse/Minecraft/Install/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar file:/C:/Users/hunte/Documents/Curse/Minecraft/Install/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar file:/C:/Users/hunte/Documents/Curse/Minecraft/Install/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar file:/C:/Users/hunte/Documents/Curse/Minecraft/Install/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar file:/C:/Users/hunte/Documents/Curse/Minecraft/Install/libraries/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar file:/C:/Users/hunte/Documents/Curse/Minecraft/Install/libraries/com/mojang/patchy/1.1/patchy-1.1.jar file:/C:/Users/hunte/Documents/Curse/Minecraft/Install/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar file:/C:/Users/hunte/Documents/Curse/Minecraft/Install/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar file:/C:/Users/hunte/Documents/Curse/Minecraft/Install/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar file:/C:/Users/hunte/Documents/Curse/Minecraft/Install/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar file:/C:/Users/hunte/Documents/Curse/Minecraft/Install/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar file:/C:/Users/hunte/Documents/Curse/Minecraft/Install/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar file:/C:/Users/hunte/Documents/Curse/Minecraft/Install/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar file:/C:/Users/hunte/Documents/Curse/Minecraft/Install/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar file:/C:/Users/hunte/Documents/Curse/Minecraft/Install/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar file:/C:/Users/hunte/Documents/Curse/Minecraft/Install/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar file:/C:/Users/hunte/Documents/Curse/Minecraft/Install/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar file:/C:/Users/hunte/Documents/Curse/Minecraft/Install/libraries/com/google/guava/guava/21.0/guava-21.0.jar file:/C:/Users/hunte/Documents/Curse/Minecraft/Install/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar file:/C:/Users/hunte/Documents/Curse/Minecraft/Install/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar file:/C:/Users/hunte/Documents/Curse/Minecraft/Install/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar file:/C:/Users/hunte/Documents/Curse/Minecraft/Install/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar file:/C:/Users/hunte/Documents/Curse/Minecraft/Install/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar file:/C:/Users/hunte/Documents/Curse/Minecraft/Install/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar file:/C:/Users/hunte/Documents/Curse/Minecraft/Install/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar file:/C:/Users/hunte/Documents/Curse/Minecraft/Install/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar file:/C:/Users/hunte/Documents/Curse/Minecraft/Install/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar file:/C:/Users/hunte/Documents/Curse/Minecraft/Install/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar file:/C:/Users/hunte/Documents/Curse/Minecraft/Install/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar file:/C:/Users/hunte/Documents/Curse/Minecraft/Install/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar file:/C:/Users/hunte/Documents/Curse/Minecraft/Install/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar file:/C:/Users/hunte/Documents/Curse/Minecraft/Install/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar file:/C:/Users/hunte/Documents/Curse/Minecraft/Install/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar file:/C:/Users/hunte/Documents/Curse/Minecraft/Install/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar file:/C:/Users/hunte/Documents/Curse/Minecraft/Install/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar file:/C:/Users/hunte/Documents/Curse/Minecraft/Install/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar file:/C:/Users/hunte/Documents/Curse/Minecraft/Install/versions/1.12.2/1.12.2.jar file:/C:/Users/hunte/Documents/Curse/Minecraft/Instances/FoolCraft%203%20(1)/mods/%23%20LibLoader.jar]
15:28:40 | FML | main | warn | Found FMLCorePluginContainsFMLMod marker in astralsorcery-1.12.2-1.9.3.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
15:28:40 | FML | main | warn | The coremod hellfirepvp.astralsorcery.core.AstralCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
15:28:40 | FML | main | info | [AstralCore] Initialized.
15:28:40 | FML | main | warn | Found FMLCorePluginContainsFMLMod marker in bedpatch-2.2-1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
15:28:40 | FML | main | warn | Found FMLCorePluginContainsFMLMod marker in BetterFoliage-MC1.12-2.1.10.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
15:28:40 | FML | main | warn | The coremod mods.betterfoliage.loader.BetterFoliageLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
15:28:40 | FML | main | warn | The coremod BetterFoliageLoader (mods.betterfoliage.loader.BetterFoliageLoader) is not signed!
15:28:40 | FML | main | info | Loading tweaker codechicken.asm.internal.Tweaker from ChickenASM-1.12-1.0.2.7.jar
15:28:40 | FML | main | warn | Found FMLCorePluginContainsFMLMod marker in CTM-MC1.12.2-0.3.1.16.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
15:28:40 | FML | main | warn | The coremod team.chisel.ctm.client.asm.CTMCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
15:28:40 | FML | main | warn | The coremod CTMCorePlugin (team.chisel.ctm.client.asm.CTMCorePlugin) is not signed!
15:28:40 | FML | main | warn | Found FMLCorePluginContainsFMLMod marker in EnderCore-1.12.2-0.5.35.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
15:28:40 | FML | main | warn | Found FMLCorePluginContainsFMLMod marker in foamfix-0.9.9.1-1.12.2-anarchy.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
15:28:40 | FML | main | warn | The coremod pl.asie.foamfix.coremod.FoamFixCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
15:28:40 | FML | main | warn | Found FMLCorePluginContainsFMLMod marker in Forgelin-1.7.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
15:28:40 | FML | main | warn | The coremod net.shadowfacts.forgelin.preloader.ForgelinPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
15:28:40 | FML | main | warn | The coremod ForgelinPlugin (net.shadowfacts.forgelin.preloader.ForgelinPlugin) is not signed!
15:28:40 | FML | main | warn | Found FMLCorePluginContainsFMLMod marker in InventoryTweaks-1.63.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
15:28:40 | FML | main | warn | The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
15:28:40 | FML | main | warn | The coremod ivorius.ivtoolkit.IvToolkitLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
15:28:40 | FML | main | warn | The coremod IvToolkit (ivorius.ivtoolkit.IvToolkitLoadingPlugin) is not signed!
15:28:40 | FML | main | info | Loading tweaker org.spongepowered.asm.launch.MixinTweaker from malisiscore-1.12.2-6.4.0.jar
15:28:40 | FML | main | warn | The coremod ObfuscatePlugin (com.mrcrayfish.obfuscate.asm.ObfuscatePlugin) is not signed!
15:28:40 | FML | main | warn | Found FMLCorePluginContainsFMLMod marker in OpenComputers-MC1.12.2-1.7.2.67.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
15:28:40 | FML | main | warn | The coremod li.cil.oc.common.launch.TransformerLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
15:28:40 | FML | main | warn | The coremod TransformerLoader (li.cil.oc.common.launch.TransformerLoader) is not signed!
15:28:40 | FML | main | warn | Found FMLCorePluginContainsFMLMod marker in OpenModsLib-1.12.2-0.11.5.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
15:28:40 | FML | main | warn | The coremod openmods.core.OpenModsCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
15:28:40 | FML | main | warn | The coremod RBLoadingPlugin (pw.prok.realbench.asm.RBLoadingPlugin) is not signed!
15:28:40 | FML | main | warn | Found FMLCorePluginContainsFMLMod marker in ResourceLoader-MC1.12.1-1.5.3.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
15:28:40 | FML | main | warn | The coremod lumien.resourceloader.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
15:28:40 | FML | main | warn | Found FMLCorePluginContainsFMLMod marker in TickProfiler-1.12-0.0.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
15:28:40 | FML | main | warn | The coremod org.minimallycorrect.tickprofiler.minecraft.CoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
15:28:40 | FML | main | warn | The coremod CoreMod (org.minimallycorrect.tickprofiler.minecraft.CoreMod) is not signed!
15:28:40 | FML | main | warn | The coremod blusunrize.immersiveengineering.common.asm.IELoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
15:28:40 | LaunchWrapper | main | info | Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
15:28:40 | LaunchWrapper | main | info | Loading tweak class name codechicken.asm.internal.Tweaker
15:28:40 | LaunchWrapper | main | info | Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
15:28:40 | mixin | main | info | SpongePowered MIXIN Subsystem Version=0.7.4 Source=file:/C:/Users/hunte/Documents/Curse/Minecraft/Instances/FoolCraft%203%20(1)/mods/malisiscore-1.12.2-6.4.0.jar Service=LaunchWrapper Env=CLIENT
15:28:40 | FML | main | warn | The coremod net.malisis.core.asm.MalisisCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
15:28:40 | FML | main | warn | The coremod MalisisCorePlugin (net.malisis.core.asm.MalisisCorePlugin) is not signed!
15:28:41 | mixin | main | info | Compatibility level set to JAVA_8
15:28:41 | LaunchWrapper | main | info | Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
15:28:41 | LaunchWrapper | main | info | Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
15:28:41 | LaunchWrapper | main | info | Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
15:28:41 | LaunchWrapper | main | info | Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
15:28:41 | TickProfiler | main | info | TickProfiler v1.12-0.0.4 coremod injectData called, loading patches
15:28:41 | ModPatcher | main | info | ModPatcher running under classloader net.minecraft.launchwrapper.LaunchClassLoader
15:28:41 | JavaPatcher | main | info | Added patch minecraft: Patcher.ClassPatchDescriptor(name=net.minecraft.world.World, patches=[Patcher.PatchDescriptor(methods=func_72939_s()V, patch=clone), Patcher.PatchDescriptor(methods=func_72939_s()V, patch=insertCodeBefore), Patcher.PatchDescriptor(methods=updateEntities_withProfiling(), patch=replaceMethodCall), Patcher.PatchDescriptor(methods=updateEntities_withProfiling(), patch=replaceMethodCall), Patcher.PatchDescriptor(methods=updateEntities_withProfiling(), patch=replaceMethodCall)])
15:28:41 | JavaPatcher | main | info | Added patch minecraft: Patcher.ClassPatchDescriptor(name=net.minecraft.network.play.server.SPacketCustomPayload, patches=[Patcher.PatchDescriptor(methods=, patch=addMethod)])
15:28:41 | JavaPatcher | main | info | Added patch minecraft: Patcher.ClassPatchDescriptor(name=net.minecraft.network.NettyPacketEncoder, patches=[Patcher.PatchDescriptor(methods=encode(Lio/netty/channel/ChannelHandlerContext;Lnet/minecraft/network/Packet;Lio/netty/buffer/ByteBuf;)V, patch=replaceMethodCall)])
15:28:41 | LaunchWrapper | main | info | Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
15:28:42 | FML | main | fatal | Patcher expecting non-empty class data file for net.minecraft.crash.CrashReport$1, but received empty.
15:28:42 | LaunchWrapper | main | error | Unable to launch java.lang.RuntimeException: java.lang.RuntimeException: Patcher expecting non-empty class data file for net.minecraft.crash.CrashReport$1, but received empty, your vanilla jar may be corrupt. 	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:166) 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) Caused by: java.lang.RuntimeException: Patcher expecting non-empty class data file for net.minecraft.crash.CrashReport$1, but received empty, your vanilla jar may be corrupt. 	at net.minecraftforge.fml.common.patcher.ClassPatchManager.applyPatch(ClassPatchManager.java:113) 	at net.minecraftforge.fml.common.patcher.ClassPatchManager.getPatchedResource(ClassPatchManager.java:76) 	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.getFieldType(FMLDeobfuscatingRemapper.java:219) 	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.parseField(FMLDeobfuscatingRemapper.java:192) 	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.setup(FMLDeobfuscatingRemapper.java:161) 	at net.minecraftforge.fml.common.asm.FMLSanityChecker.injectData(FMLSanityChecker.java:187) 	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:161) 	... 2 more
11:28:42 | game |   | error | Exception in thread "main"   <log4j:Event logger="STDERR" timestamp="1533670122486" level="INFO" thread="main">     <log4j:Message><![CDATA[[java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException]]></log4j:Message>   </log4j:Event>
11:28:42 | monitor | Process Monitor | error | expected <
15:28:42 | STDERR | main | info | [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
15:28:42 | STDERR | main | info | [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
15:28:42 | STDERR | main | info | [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:107)
15:28:42 | STDERR | main | info | [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:971)
15:28:42 | STDERR | main | info | [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
15:28:42 | STDERR | main | info | [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
15:28:42 | launcher | main | info | Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=256m; support was removed in 8.0
11:28:42 | monitor | Process Monitor | fatal | Process crashed with exit code 1

**Comment by HunterMeredith** [comment]
https://pastebin.com/e5sCRA5s

**Comment by HunterMeredith** [comment]
I will try updating my NVidia drivers and see if it helps

**Comment by HunterMeredith** [comment]
found a fix. The way I fixed it was I changed the launch method in twitch's settings to jar, launched it once, and changed it back to native
