### ISSUE TITLE
upgrade led to unplayable game

### ISSUE THREAD

**Issue by ddoyle2** [scalda/Foolcraft_3#263]
## Issue Description
I have just upgraded from 1.3.1 (I think) to 1.4.5.  Since doing that, this evening, I cannot play for more than 10 minutes.  When I try, I find that things stop working (chests don't open, arrows don't fire, broken things don't drop) and it becomes unplayable.  If I try to stop the game, everything freezes.  There are no crashes to post, the game just freezes forever, until I force the application to stop and restart.

## Reproduce Steps

I have no idea how to reproduce this.  Best guess is to upgrade from 1.3.1 (or maybe something near this) to the current release.  See if wackiness ensues.

## Additional Information

I have tried restarting the game, restarting twitch, rebooting my computer (windows 10).  Nothing has changed.  I am running a Biomes o'plenty version of the game.  No changes to any mod.

**Comment by nzminecraftDOTcom** [comment]
Are you running a pre-existing/played world?
Try running a fresh world. Chances are there's a conflict with the mods on 1.4.5 to do with how you've built things in 1.3.1

**Comment by ddoyle2** [comment]
The upgrade from 1.3.1 to 1.4.5 does involve a pre-existing world.  Creating a new world would make upgrading irrelevant, wouldn't it?

**Comment by nzminecraftDOTcom** [comment]
Hence why I have suggested, you try to load a new world to see if the problem happens there.

**Comment by ddoyle2** [comment]
Ah, got it.  Sorry, I misunderstood.

I tried playing a new world for about half an hour and didn't have any problem.  Though I feel like I was able to play for about that long in my actual world before the problems started to happen.

In case it matters, I also had problems with my world in that I set it up as biomes o'plenty, but something got corrupted and I had a very large square of BOP, but outside of that it became vanilla biomes.  I went in and had to switch it back to BOP after it somehow got set to default.

Outside of that, is there any way to narrow down what the problem could be?

**Comment by ddoyle2** [comment]
I was able to downgrade to 1.3.1 and get myself back to my base.  When there, I found a few problems.
- My servos became 'invalid cover' from 'Thermo Dynamics'.  I was able to break the ducts and replace them with new servos and they worked fine.
- My mob masher didn't work.  It worked once I broke it and replaced it
- The wireless RF transmitter seems to no longer be powering my enderio machines, except for the painting machine for some reason.  I haven't found a way to fix this.

In looking these up, I did notice that this issue: https://github.com/scalda/Foolcraft_3/issues/185 does match the symptoms I'm having.

**Comment by scalda** [comment]
update to Beat 1.5 and test, Please report back and close the issue if it's solved. i will close in 7 days if not responded to or not closed before hand

**Comment by ddoyle2** [comment]
I'll try updating it in the next couple of days.

**Comment by scalda** [comment]
ok thanks please let me know how it goes

**Comment by ddoyle2** [comment]
See the major problem at: https://github.com/scalda/Foolcraft_3/issues/270 .  I'll use this bug to test the other issues once I can get past that first one there.

**Comment by ddoyle2** [comment]
Just a reminder, https://github.com/scalda/Foolcraft_3/issues/270 isn't closed.  I've stopped playing Beta 1.5 because it is too buggy

**Comment by scalda** [comment]
@DDoyle022 have you updated to 1.5.2 and checked this issues?

**Comment by generrosity** [comment]
Yikes - downgrading a world across forge versions likely wont be doing good things to the stability. From your notes on the other report, youve gotten corruptions, block rotations, and possibly missing your world-generator-type. That is definitely a "restore to backup" moment - I believe Curse does backups when upgrading if you aren't already yourself?

**Comment by ddoyle2** [comment]
1.5.1 fixed this issue
