### ISSUE TITLE
Mod Rejection/Mismatch for V1.4.5

### ISSUE THREAD

**Issue by Ultimasummer** [scalda/Foolcraft_3#265]
## Issue Description
Cannot connect to server due to "Server Mod rejections: TooManyBackups : Requires version 1.0.3 but mod is not found on client"

https://imgur.com/a/KbpJkjq

Have tried using Client and Server 1.4.5 AND Client and Server 1.3.1 - Reupload... Experienced same issue on both

## Reproduce Steps
Unsure how to reproduce issue.

**Comment by scalda** [comment]
The server you are trying to connect to has extra mods so yiu need to
contact the server owner to find out as that mod is not in foolcraft

**Comment by Ultimasummer** [comment]
Thank you Scalda, I will do.

**Comment by Ultimasummer** [comment]
Having spoken to a few people, have resolved the issue. It was a mod called TooManyTarvii causing the issue. Once the mod was disabled, issue was resolved.
