### ISSUE TITLE
Would like to see Thaumcraft updated as it has more research implemented. As well 

### ISSUE THREAD

**Issue by MaatPlays** [scalda/Foolcraft_3#267]
- [o ] I would like to propose an additional mod.
- [o ] I would like to propose a config change.
- [o ] I would like to propose a custom recipe.
- [x ] I would like to propose another change.

<!-- FEATURE INFORMATION - Please explain what you want changed/added and why.

**Comment by scalda** [comment]
Beta 1.5 is awaiting approval via curse

**Comment by MaatPlays** [comment]
Alright.

**Comment by scalda** [comment]
update to Beat 1.5 as it's now available
