### ISSUE TITLE
Stuck in bed

### ISSUE THREAD

**Issue by MaatPlays** [scalda/Foolcraft_3#268]
* Current Pack Version:  Release 1.4.5
- [x ] I am running FoolCraft via Curse/Twitch Launcher
- [ ] I can reproduce this issue consistently
     - [ ] In single player
     - [x] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
Am getting stuck in bed after sleeping, not sure why considering we have the mod that keeps that out. If you want proof: 

## Reproduce Steps All I did was sleep after logging in for the first time in awhile and ended up getting stuck in bed.  If you want proof, - [ ] I would like to propose an additional mod.
- [ ] I would like to propose a config change.
- [ ] I would like to propose a custom recipe.
- [ ] I would like to propose another change.

## Additional Information My Screenshot key was not working so I used Lightshot to take a screenshot if that is alright.
http://prntscr.com/khepo9

Thanks,,
Maat

**Comment by scalda** [comment]
This is a bug in MC itself just run the command /ftb kickme and you will
get disconnected. Its something todo with changing dimensions. The mod bed
patch is in the pack and should help reduce these issues

**Comment by MaatPlays** [comment]
Did so & thank you!

**Comment by scalda** [comment]
no problem i am closing the issue
