### ISSUE TITLE
Disable Wireless Crafting Terminal chunkloading.

### ISSUE THREAD

**Issue by MrNinja93** [scalda/Foolcraft_3#269]
## FEATURE REQUEST
- [ ] I would like to propose an additional mod.
- [x ] I would like to propose a config change.
- [ ] I would like to propose a custom recipe.
- [ ] I would like to propose another change.

Because you guys are trying to force players to chunkload using just weirding gadget you may want to disable Wireless Crafting Terminal making AE controllers chunkloaders. The config file for the mod itself doesn't appear to work but you can completely disable it's ability to assign chunkload tickets through ``forgeChunkLoading.cfg`` you just need to add the following to the overrides section (bottom of the file)

```
wct {
    I:maximumChunksPerTicket=0
    I:maximumTicketCount=0
}
```

**Comment by scalda** [comment]
Hi we left the ae loading in for the fact that it should always be loaded to allow the main network to function as because when stuff goes across borders into the system or from ender chest we want to make sure that the ae system stays loaded to accept items and such.

but thanks for the suggestion
