### ISSUE TITLE
Client crashes when opening inventory

### ISSUE THREAD

**Issue by Oakmontowls** [scalda/Foolcraft_3#271]
## Issue Description
When typing ca into JEI the client immediately crashes and continues to crash whenever an inventory is opened

## Reproduce Steps
Type ca into JEI

## Additional Information

https://pastebin.com/Bqj49hrQ

**Comment by scalda** [comment]
You need to go into the config folder/jei and delete all files except the
blacklist one and relaunch and you will be fine

**Comment by Oakmontowls** [comment]
That does temporarily fix it but typing ca into jei again has the same problem.

**Comment by scalda** [comment]
Ok thanks i will have to blacklist them in jei config and report to the mod authors

**Comment by scalda** [comment]
already reported https://github.com/Mineshopper/carpentersblocks/issues/418
