### ISSUE TITLE
Extreme FPS Issues

### ISSUE THREAD

**Issue by Kensuga** [scalda/Foolcraft_3#274]
## Issue Description
Whenever I load into the game, be it Single player or Multiplayer, I cannot get more than 5 frames per second with extreme stuttering.

## Reproduce Steps
Run the game.
Load into a world/ Join a server

## Additional Information
Game is un-playable at an average of 3-5 FPS, with extreme stuttering.
I have allocated 8gb of ram to the game

Running on:
I7-7700k
AMD R9 380
16gb DDR4 Corsair Ram (2x 8gb)

Only happens when running Foolcraft. I have tried other modpacks with no frame issues, as well as base minecraft, also with no issues. I have also tried re-installing and updating foolcraft multiple times with no avail. Issue started approximately 2 weeks ago.

**Comment by nzminecraftDOTcom** [comment]
Confirm that your graphics drivers are up to date, if they aren't try updating them.

**Comment by Mrbysco** [comment]
Java version?

**Comment by Kensuga** [comment]
I am running the lastest drivers for my graphics card, and Java vers 8 update 181

**Comment by nzminecraftDOTcom** [comment]
CPU / Video card isn't thermally throttling?

**Comment by Kensuga** [comment]
While Foolcraft is open, task manager shows its using a 77% of RAM, when in-game my GPU goes up to 100% usage and the CPU goes up to 60-90%, and the ram goes up to 90%

**Comment by scalda** [comment]
if this is fps then this is to do with your computer, not the pack. sorry but i need to close this to free up the issues page
