### ISSUE TITLE
Mod requests.

### ISSUE THREAD

**Issue by Mythilily** [scalda/Foolcraft_3#276]
## FEATURE REQUEST
- [x] I would like to propose an additional mod(s).
- [ ] I would like to propose a config change.
- [ ] I would like to propose a custom recipe.
- [ ] I would like to propose another change.

## FEATURE INFORMATION
Mod additions to Thaumcraft, RFtools, Thermal Expansion
But also some new mods. It feels they are missing in the pack because they offer unique gameplay, can make some things more exciting (and easier to deal with) and with a possibility to reduce lag.
## MOD INFORMATION
**Addons**
[Thaumic Tinkerer](https://minecraft.curseforge.com/projects/thaumic-tinkerer) - Endgame Thaumcraft (right now in alpha)
[ET Lunar](https://minecraft.curseforge.com/projects/et-lunar-environmental-tech-addon)
RFtools [control](https://minecraft.curseforge.com/projects/rftools-control), [dimensions](https://minecraft.curseforge.com/projects/rftools-dimensions), power (not sure why these aren't in the pack since RFtools already is - dimensions might need tweaking because it can be op with default settings)
[Redstone Arsenal](https://minecraft.curseforge.com/projects/redstone-arsenal)
[Blood Arsenal](https://minecraft.curseforge.com/projects/blood-arsenal)
Something that has been suggested already:
[Extra Cells 2](https://minecraft.curseforge.com/projects/extracells2) (More on this one below)
**New mods**
[Draconic Evolution](https://minecraft.curseforge.com/projects/draconic-evolution) - Wireless energy (crystals), energy storage, utility, endgame content (endboss)
[Nuclearcraft](https://minecraft.curseforge.com/projects/nuclearcraft-mod)or [Extreme Reactors](https://minecraft.curseforge.com/projects/extreme-reactors) (mid to late power generation)
[Mekanism](https://minecraft.curseforge.com/projects/mekanism-generators) (ore processing, utility)
[Not Enough Wands](https://minecraft.curseforge.com/projects/not-enough-wands) - unique utility wands
[Woot ](https://minecraft.curseforge.com/projects/woot?)- Lagg free mobfarms.

Regarding EC2
What I find kind of strange is that both AE2 and RS are in this pack. What's the use of this? What are people supposed to use - since they are both similar in storing items. Only AE2 is missing some features without EC2 compared to RS.

**Comment by Mrbysco** [comment]
Reason they're both in is so people can decide what they want to use. Some people hate having to keep channels in mind when creating a AE2 system.

**Comment by Mrbysco** [comment]
Unless Thaumic Tinkerer releases a beta version it won't even be able to be in the pack. As Curse/Twitch does not allow you to install alpha mods

**Comment by Revvilo** [comment]
I personally second the idea of Woot. Used it back in the day when it was basic and now quite like the look of the new design. Would be interested to hear what others think.
No strong opinions on the others - although, fresh stuff is always cool 😉

**Comment by jc2xs** [comment]
I'll second woot just because of the lag issues when you have about 30 different players chunkloading bases.

As a comment about the OPs post about AE2 and RS.  I agree on giving people a choice even though AE2 is by far superior there are some players that just hate the channel system.  BTW: some little known fact about AE2, first it costs less in materials to make the same amount of storage space.  2nd the AE2 disk hold a lot more than RS disks of the same size (especially if you make use of partitioning disks).  Lastly when you start a craft in AE2 it actually removes the items need for the craft and moves them into the crafting CPU's memory.  That means you can't screw up a craft by removing items from the main inventory.  Something I've done on RS multiple times.

**Comment by Mythilily** [comment]
I like AE2 since it's more balanced (you have channels and 63 item limit per drive) and at the same time better optimized (when having larger storage systems). The main reason why I suggested EC2 is because of the need of larger storage when for example storing items from a quarry or mining laser and has _no option_ to store fluids.

**Comment by scalda** [comment]
So none of those mods will be added they were all discussed when the pack was first built and they were all nonos

thanks thou
