### ISSUE TITLE
Invalid Heap Size

### ISSUE THREAD

**Issue by Ballberry92** [scalda/Foolcraft_3#278]
Hi, just tried to launch the modpack after getting some help to get it running in the first place.. after getting the expections message from Extra Utilites 2. Some of the people I play with are managing to get the modpack to launch again but I however am getting the constant message of "Invalid Heap Size"

My pc has 8gb of ram for now, which has been letting the game play fine with no problems. I was advised to change the JVM argument to -Xmx6G (previously set at -Xmx7162m) but on both I still got the heap error.

I'm at a loss on what todo?

**Comment by scalda** [comment]
see here https://github.com/scalda/Foolcraft_3/issues/277 for an answer this is not a pack issue it is a minecraft issue mojang has broke something in the twitch launcher. i will update the pack to 1.5.1 as soon as i can
