### ISSUE TITLE
Manually updating server to 1.5

### ISSUE THREAD

**Issue by z4zzles** [scalda/Foolcraft_3#279]
My friends and i are playing 1.45 atm both client and server side.
I was wondering since there is no ready-made server pack if i can update te server myself.
The server is running on a computer at my place so i have full access.
What steps would i need to take in order to ensure a proper update to the server without compromising its stability etc..?

Thanks in advance.

Zazzles.

**Comment by nzminecraftDOTcom** [comment]
For starters. The server needs all the same mods as the client minus a few that are client only and screw things around. (1.4.5 and 1.3.1 had quite a few of these i deleted)

**Comment by z4zzles** [comment]
> For starters. The server needs all the same mods as the client minus a few that are client only and screw things around. (1.4.5 and 1.3.1 had quite a few of these i deleted)

It does sound like a good start to make sure the mod versions correspond.
But i'm sure there's more to it then just overwriting the mod folder.

**Comment by nzminecraftDOTcom** [comment]
Yes. Making sure the mods are comparable with each other

**Comment by Mythilily** [comment]
I wasn't able to start a 1.5 server without removing furniture-5.4.1-1.12.2 (it crashes when this mod is enabled). After that it worked fine.

**Comment by nzminecraftDOTcom** [comment]
There will be a conflict with it or the furniture mod requires an add-on mod that isn't in the pack to be on a server environment.

**Comment by z4zzles** [comment]
@MythixDino what steps did you take to update manually? Did you only overwrite the modfolder or did you delete/change other files?

**Comment by jc2xs** [comment]
I ran into the issue (server crashed when a player logged in) with furniture mod when I tried to manually update the server this morning as well.  What was the fix or will you be releasing a 1.5 version of the server files?

**Comment by Mythilily** [comment]
@z4zzles Since there isn't a server pack you have kind of to use the client files. Just copy them to the server and with a bit of knowledge you really can't mess this up - make backups if needed.
@jc2xs The only way right now is to remove the mod like I did.

**Comment by scalda** [comment]
this is the reason there is no server files for 1.5
