### ISSUE TITLE
Ender IO Fluid Tank has no GUI 

### ISSUE THREAD

**Issue by Flekrad** [scalda/Foolcraft_3#28]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
After crafting and placing down the Ender IO Fluid Tank it has no GUI when clicking on it 
I can put in / remove a bucket of liquid 
GUI shows up in my single player game , but not in multiplayer 

## Additional Information
After picking it up , tooltip shows tank as configured , placing down again still no GUI
Putting it into crafting grid to remove said "configuration" didnt help

**Comment by scalda** [comment]
I can not replicate this issue on a multiplayer server and i have tested it on 6. Any mor information would be great

**Comment by Flekrad** [comment]
Unsure what extra information you need ??
So when u right click on the tank you can see its GUI ?

**Comment by Tempus-Dominus** [comment]
This is not only happening in foolcraft.  I have recently encountered this in FTB-Revelations on multiplayer.

As Flekrad stated, right-clicking to open the gui on a fluid tank does not work in multiplayer
