### ISSUE TITLE
Crash in Thaumcraft Vacuos ThaumicJEI item integration 

### ISSUE THREAD

**Issue by bholmes451** [scalda/Foolcraft_3#281]
## Issue Description
Opening page 2 of the Vacuos item information screen I receive a crash. in reading the crash report it states it had a problem rendering an item.  I do not know the item since it is in a set of items.

## Reproduce Steps
1. Open JEI search
2. Search string: @Thaum Vacu
3. Click the third item "Vacuos"
4. Click the "Aspect from Itemstack" tab
5. Click the "Next Page" button
NOTE: Pages 3,4,5,6 do not crash

## Additional Information
https://pastebin.com/i7LS6UHS

**Comment by bholmes451** [comment]
I just had the same thing happen for page 4 of Machina.  This time I validated single player and it does not crash in single player.
https://pastebin.com/HCsFA048

**Comment by scalda** [comment]
please wait 1.5.1 i am working on it but other things have taken up my time alot. see here for some story https://www.gofundme.com/the-carastudio
