### ISSUE TITLE
equivalent energistics not working right

### ISSUE THREAD

**Issue by Pultex** [scalda/Foolcraft_3#282]
## Issue Description
If you place a equivalent energistics storage drive into the bay by itself it just dumps it out on the floor and upon braking the drive will duplicate the equivalent energistics storage drive.

## Reproduce Steps
place AE drive down
insert equivalent energistics storage drive
exit gui
brake drive with pick or other tool
get two equivalent energistics storage drive and AE drive

## Additional Information

Well it seem equivalent energistics just does not work with the new version of AE.
I asked the creator of equivalent energistics and he said it works best with appliedenergistics2-rv5.
Not sure we can downgrade it to work right.

**Comment by scalda** [comment]
this is fixed in 1.5.1 from my testing today
