### ISSUE TITLE
Astral Sorcery observatory server desync

### ISSUE THREAD

**Issue by Pultex** [scalda/Foolcraft_3#284]
## Issue Description
Astral Sorcery observatory causes player interaction with all inventories to slowly fail 

## Reproduce Steps
build Astral Sorcery observatory
use the observatory
try to place items, break items, or interact with world

## Additional Information
The author of the mod has stated they know about it but will not be fixed till version 10.
If it could be removed or warned to player about the bug to prevent problems with other bug reports.

**Comment by scalda** [comment]
awaiting mod update to fix this
