### ISSUE TITLE
HI  

### ISSUE THREAD

**Issue by Jegeek** [scalda/Foolcraft_3#285]
## Additional Information

i had a ender io conduct with a immersive engineering fluid pipe connected ad it made it crash all the time so i removed the mod ender io to have the possibility to remove those fluid pipe from immersive that connected and it seems good now but everyone needs to be carefull when pipe from both mods are connected

**Comment by nzminecraftDOTcom** [comment]
What pack version were you using.

**Comment by Pultex** [comment]
yeah if you use a tank in between it will stop it

**Comment by scalda** [comment]
this is fixed in the latest version 1.5.1 will be released today
