### ISSUE TITLE
Click&Drag?+Main Menu

### ISSUE THREAD

**Issue by TagsonOG** [scalda/Foolcraft_3#29]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description: First is the Item moving in inventory, i dont know if it was intentional but i dont see any issues on iskall his videos so i am reporting it. When i want to move items in my iventory to some other inventory or at all inside inventory, then i have to click and drag and then it usually doesnt work too so it goes back to the inventory slot it was in and right clicking doesnt work that well too.
(as a sidenote, i sometimes cant use the main menu after exiting a world too)

**Comment by scalda** [comment]
Sorry i cannot replicate this issue, Can you provide more information?

**Comment by TagsonOG** [comment]
1st Thanks for the kinda fast response (really appreciated), 2nd I don't really know what happened, it was just there from the installation and it was the most bugging thing ever, but (I am sorry for bugging with this) I decided to copy my saves and reinstall the modpack which then fixed it for me, but like the click and drag was weird then right click didnt always half the stack and even didnt pick up the items and on top of that i had to use alt instead of shift to quickly transfer the items in a stack... all in all it was being weird with the inventory stuff. The 3rd thing that is was the main menu buttons not working what somehow now work after reinstalling the modpack. (Just a suggestion if someone is having any weird repeating problems, that they should try to reinstall the modpack) Really thank you again and sorry if this is kind of spam, somehow some stuff i get to fix by myself after reporting the issue.
