### ISSUE TITLE
Latest Update causes problems with Refined Storage, Lag and JEI Freezes

### ISSUE THREAD

**Issue by Basilicum** [scalda/Foolcraft_3#290]
Upon Updating the game and converting my world (with backup), I come to my base with about 3FPS, although I consistently run 100fps on a regular base. I look around, and find my Solderers gone, completely vanished. As I try to craft new ones, JEI doesn't show them and when I looked through JEI, the game started to Tank even more, until it just froze. Unfortunately it didn't actually crash. It just sat there doing nothing until I had to forcefully close it. Whenever I opened it and tried again, even reloading a backup to reconvert, it had the same issues. A new world comes with the same issues. 

I was wondering if others had a similar problem, or if this problem is being fixed.

**Comment by scalda** [comment]
Refined storage has removed the solderers from the mod so that explains why
they are gone. As for the other issues I'm not sure as I converted 8
servers today and all was well with checking bases and such. But it could
be something.

**Comment by Basilicum** [comment]
I see, its sad to hear that Solderers were removed. I just opened up another new world after a restart of the PC, incase it had anything to do with it. And the new world seems to be fine. But looking through the Refined Storage stuff that has been updated...its so sad. 

Anywho. Unfortunately my actual world is still tanking and constantly freezing. I can only imagine that perhaps all the autocrafting recipes and such cause problems now? However that wouldn't explain the problem with JEI causing Freezes. 

I'd really rather avoid having to make a new world, I just spend like 60 hours last week and had a blast. Restarting would really sting. 

I hope something can be found. But thanks for the swift answer!

**Comment by scalda** [comment]
Laggoogles is in the pack along with tick profiler so yiu can use them to
help you narrow down the issue.

Also have you done any modifications to the pack at all?

**Comment by Basilicum** [comment]
I just completely tore down all the Crafters that were once connected to the now, gone, Solderers. And it seems to be fixed. No more lag or freezes.

And no I haven't done any modifications.

I'll play a while longer and see if everything is still gonna be alright.

**Comment by scalda** [comment]
ok thanks for the update. please let me know how it goes

**Comment by infogulch** [comment]
Also had an issue with RS after updating from 1.4.5 to 1.5.1. Whenever the RS network's chunk was loaded the server timed out (single tick took 60.0 seconds). Loading the world into MCEdit and deleting the RS controller of the network fixed it. I imagine it had something to do with ongoing autocrafting across updates.

**Comment by scalda** [comment]
so this issue is sorted so i will close it
