### ISSUE TITLE
Game crashes caused by possibly Reborn Storage

### ISSUE THREAD

**Issue by RedCocoon** [scalda/Foolcraft_3#294]
## Issue Description
It isn't a full crash as VanillaFix still keeps me in game. 
Problem started when I placed a Crafting Storage in-game.
The inventory got wiped and top right corner have multiple pop-ups notifying about the crash.

## Additional Information
I do not marked the "- [ ] I can reproduce this issue consistently" since I don't have time to try again.
Please let me know if there is anyway to get a backup (I did not have any manual backup) if possible.
Thanks for the modpack. Hope I filled this correctly.
Crash Report here:
https://pastebin.com/RWzvT3fv

**Comment by RedCocoon** [comment]
Update: Turns out when I open the world again my inventory came back. I do not see anything odd or out of place as of now.

**Comment by scalda** [comment]
I assume this is all good since you haven't posted anything since
