### ISSUE TITLE
Game freeze when rejoining after recovering from crash

### ISSUE THREAD

**Issue by Revvilo** [scalda/Foolcraft_3#295]
## Modpack Information
* Current Pack Version: 1.5.1
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [x] In single player
     - [x] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [x] I am crashing and can provide my crash report(s)
- [x] I have not altered the modpack

## Issue Description
When I'm crashed by the Carpenters Blocks pressure plate and am placed back at the main menu, trying to rejoin the server gets up to Logging In - and just sits there... doing absolutely nothing. Game responds perfectly fine until you click `Cancel` which then freezes the game.
The same thing happens when trying to join a singleplayer world, post-crash.
**_It does not matter if you crash on a SP or MP world - both hang upon rejoin of SP or MP_**

This is what is printed when trying to join the server again;
```
[15:28:03] [Netty Client IO #1/INFO] [FML]: Attempting connection with missing mods [betteradvancements, betterfoliage, controlling, ctgui, ctm, custommainmenu, defaultoptions, jeiintegration, jeresources, moreoverlays, mousetweaks, norecipebook, resourceloader, thaumicjei, toastcontrol, wailaharvestability, reauth] at SERVER
[15:28:03] [Session-Validator/INFO] [ReAuth]: Session validation successful
[15:28:24] [main/INFO] [minecraft/GuiConnecting]: Connecting to 192.168.1.8, 25565
[15:28:25] [Netty Client IO #2/INFO] [FML]: Server protocol version 2
[15:28:25] [Netty Client IO #2/INFO] [FML]: Attempting connection with missing mods [betteradvancements, betterfoliage, controlling, ctgui, ctm, custommainmenu, defaultoptions, jeiintegration, jeresources, moreoverlays, mousetweaks, norecipebook, resourceloader, thaumicjei, toastcontrol, wailaharvestability, reauth] at SERVER
```
And upon joining a SP world, a heap of (probably normal) init stuff is printed before the game once again hangs. This time, though, on a blank dirt screen.

## Reproduction Steps
- Get a Carpenter's Block
- Hit `u` on it
- When Vanilla Fix tells you about the crash, return to the main menu
- Log back in to a world or server
- *crickets chirping*

## Additional Information
* [Crash Report](https://paste.dimdev.org/oremitaled.mccrash)

**Comment by Revvilo** [comment]
https://github.com/DimensionalDevelopment/VanillaFix/issues/116

**Comment by ZombieHDGaming** [comment]
Realistically, I don't think this has anything to do with VanillaFix. I've tested this with only CarpentersBlocks, VanillaFix, and JEI, and this kind of issue still happens. CarpentersBlocks is still very heavy alpha and is clearly having major issues with rendering as you can tell. There's not much we can do since we are not the one causing the issue. The game still runs fine and works fine after a crash, it's CarpentersBlocks that is causing an issue and is preventing you from joining the server again.

**Comment by nzminecraftDOTcom** [comment]
Vanillafix is the cause of the freeze, it stops the game crashing when it should have closed down and been restarted. I removed Vanillafix to stop this issue, if it's going to crash and become unplayable then I might as well just have the game stop completely.

**Comment by Revvilo** [comment]
#### Edit: I seem to have located it - see my comment on the VF issue.
Unfortunately @ZombieHDGaming I think I was a little too focused on the Carpenters Blocks issue in the OP, it has nothing to do with Carpenters Blocks, it was simply a way to reliably cause a crash. So I gave out a bit of a wrong message there, that's why I referenced the issue created by @nzminecraftDOTcom 
on the Vanillafix repo, intending to continue this issue over there. Sorry for the confusion.

I've being making my own pack recently, which does not contain Carpenters Blocks, and it happens exactly the same with any crash that happens. So as nzminecraft has said, I do believe it is a Vanillafix issue.

**Comment by ZombieHDGaming** [comment]
As stated on the VF issue, I will be pushing a new build this weekend with the fixes for this and many other things. I will leave a message with a link to download that new version when I post it, until scalda can push a new pack version.

**Comment by scalda** [comment]
carpenters blocks has no been removed from the pack as off 1.5.2 as i was tired waiting for the mod author to fix the current issues
