### ISSUE TITLE
Game Crash potential cause Tiny Progressions

### ISSUE THREAD

**Issue by lolipopopoop** [scalda/Foolcraft_3#296]
## Issue Description
The game crashes when I hit an enderman or tiny enderman (from enderzoo) with a Wub Hammer and I think it teleported right when I hit it

## Reproduce Steps
Hit enderman with wub hammer (doesn't happen all the time)
 

## Additional Information
https://paste.dimdev.org/jejoqamiju.mccrash
https://imgur.com/GDX28Sk

**Comment by Chik3r** [comment]
Well, according to the error the wub hammer thinks it's destroying a block, but maybe an argument is null (NullPointerException). So when it hits an enderman (like you said), it thinks it's destroying a block and crashes.

I think this is more of a mod issue than a modpack issue, So my recommendation is to report it to the mod author

**Comment by lolipopopoop** [comment]
Thanks you
