### ISSUE TITLE
Please fix the cutting tool!

### ISSUE THREAD

**Issue by Twotusktommy** [scalda/Foolcraft_3#298]
## FEATURE REQUEST
- [ ] I would like to propose an additional mod.
- [ ] I would like to propose a config change.
- [ ] I would like to propose a custom recipe.
- [x] I would like to propose another change.

<!-- Since the removal of the solderer in refined storage the cutting tool was implemented. I am currently auto crafting reborn storage storage disks and it is requiring more than 10000 cutting tools for one of the 16mill disks. this is a lot of iron and quartz just for the tool that is used to replace the solderers not even the storage disks themselves. Please make the cutting tool like the Pam's items or the philosophers stone. i.e. no durability.  Also, it seems to be causing a lot of lag due to the crafting and inserting of all the cutting tools.  Thank you for listening. 

~Tommy
>

**Comment by Twotusktommy** [comment]
Since the removal of the solderer in refined storage the cutting tool was implemented. I am currently auto crafting reborn storage storage disks and it is requiring more than 10000 cutting tools for one of the 16mill disks. this is a lot of iron and quartz just for the tool that is used to replace the solderers not even the storage disks themselves. Please make the cutting tool like the Pam's items or the philosophers stone. i.e. no durability.  Also, it seems to be causing a lot of lag due to the crafting and inserting of all the cutting tools.  Thank you for listening. 

~Tommy

**Comment by Mrbysco** [comment]
This isnt really an issue that foolcraft can fix. You should report it to Refined Storage.

**Comment by Twotusktommy** [comment]
Technically you are correct. However, the item bounds can be adjusted for just this mod pack. The durability of the single item can be adjusted in the pack. Scalda and his team have already adjusted a number of items to work specifically in a certain way for this pack. 

Also, to note, it is a discussion that is open already with Raoulvdberge over on the refined storage forum.

**Comment by scalda** [comment]
this is due to RS not reusing the same tool as the nbt/metadata will change after each tool use so I bet you have a ton of partially used cutting tools in your system.

Also, there is no way of making the tools indestructible sorry RS doesn't have that option
