### ISSUE TITLE
Unnecessary mods present in Server download

### ISSUE THREAD

**Issue by nzminecraftDOTcom** [scalda/Foolcraft_3#299]
## FEATURE REQUEST
- [ ] I would like to propose an additional mod.
- [ ] I would like to propose a config change.
- [ ] I would like to propose a custom recipe.
- [x ] I would like to propose another change.

## FEATURE INFORMATION
Removal of the following mods from the server download for 1.5.1 (Or can be done manually to save memory on server hosting the modpack)
Betteradvancements
BetterFoliage
Controlling
ctGUI
CTM
CustomMainMenu
Defaultoptions
JEIIntegration
JEresources
Moreoverlays
Mousetweaks
Norecipebook
Resourceloader
ThaumicJEI
Toastcontrol
Wailaharvestability
Reauth

There may be more, but this is the list I've found that floods my console whenever I start up the server.
As seen here in a server log https://i.imgur.com/V8RnpvV.png

That and this layout is broken: Need to add --> after the "Please explain what you want changed/added and why" bit of text.

**Comment by nzminecraftDOTcom** [comment]
These mods are present in the 1.5.2 package as well.

**Comment by generrosity** [comment]
Out of curiosity, have you measured the benefit other than logs? Startup speed, Megs of ram difference, tick impact?

**Comment by nzminecraftDOTcom** [comment]
No testing, but I'm sure it uses less memory and processing power if they aren't there, however the console warns of instability while starting, so removing them if they're not even used sounds like a plan to me.

**Comment by scalda** [comment]
Forge disables the mods and doesn't load them due to them being client-side only I don't see a downside to this. 

unless there is a reason to remove them I won't as it will add an extra stage and time for me to sort files and such.

(if only you could place client only files in a subfolder in the mods folder, something i have always wanted)
