### ISSUE TITLE
Angel Ring not permitting flight

### ISSUE THREAD

**Issue by benhavo** [scalda/Foolcraft_3#30]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
The angel ring does not allow flight. I have sufficient GP and no other flight/jetpack items in my inventory. The effect is much like that of other packs when insufficient GP is present - i.e. a small hiccup is noticeable when you attempt to fly. This does not affect the fall damage mitigation.

**Comment by benhavo** [comment]
This resolves when I remove dragon armor pieces.

**Comment by scalda** [comment]
This is probably to do with the fact that the dragon armour allows flight but that function is disabled in the pack so there may be a conflict where the armour knows it shouldn't be flying yet the ring is trying to. thanks for reporting this to us.
