### ISSUE TITLE
Equivalent Energistics crashes and bugginess

### ISSUE THREAD

**Issue by Revvilo** [scalda/Foolcraft_3#300]
## Modpack Information
* Current Pack Version: 1.5.1
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [x] In single player
     - [x] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [x] I am crashing and can provide my crash report(s)
- [x] I have not altered the modpack

## Issue Description
Originally I made a Tier 8 EMC storage cell and popped it into my main ME System's drive, it didn't seem to work so I moved it around in the drive and it crashed the server we were playing on.
I had to delete the item from the drive via an NBT Editor as the server crashed on the first tick.

I've gone back and tested it with a raw install of FC3 and everything to do with the EMC Storage cells seems to be broken - see reproduce.

Of course any insight anyone might have on this would also be appreciated, as I'd love to use this EMC thing, but don't want it bricking my world. 😉

#### For the misc errors
- Place an ME drive
- Put an EMC storage cell inside that drive
- Vanillafix will immediately warn you about errors upon placing the cell in
- Removing the cell will cause it to become a ghost item and cause another error
  - Placing the cell in your inventory then picking it back up will make it vanish
#### For the server crash
- Place an ME drive
- Put an EMC storage cell inside the drive
- Place a (Creative) Energy cell next to the drive
- Wait
- (Internal) Server should crash within a few seconds, presumably when the drive does it's startup routine

## Additional Information
* [Error that occurs upon PLACING an EMC cell in the ME Drive](https://paste.dimdev.org/eridelitux.mccrash)
* [Error that occurs upon REMOVING an EMC cell from the ME Drive](https://paste.dimdev.org/ofafanogim.mccrash) (Probably not very helpful)
* [Server Crash](https://paste.dimdev.org/tirukudedo.mccrash)

**Comment by scalda** [comment]
this is due to EE not being compatible with this current version of AE2

**Comment by Revvilo** [comment]
Ah... that's disappointing. Makes sense tho.

**Comment by scalda** [comment]
I am from version 1.5.3 removing recipes for the drive cells as they are the things causing the issues. so as long as no one has them and places them into the drive then all will be fine. as that is where all the crashes are coming from i am awaiting AE2 to release a beta of RV6 then addons will update and fix issues
