### ISSUE TITLE
AA Coffee Maker bug

### ISSUE THREAD

**Issue by LAW-11** [scalda/Foolcraft_3#302]
## ISSUE DESCRIPTION
Hello and thank you for FC3. I am currently unable to pull out any input items (empty cups/ingredients) once placed in the Coffee Maker (CM) after updating to 1.5.1 without breaking the CM. Further, the entire bucket gets consumed when using milk, and using Pam's Harvestcraft milk is not compatible with the CM and cannot be placed in a slot as a workaround. Only mod that I disabled was Better Foliage as it interferes with farming for aquamarine. I searched the net and took a look at the config file to see if there was a simple fix, but no joy. I also built a new CM and did several restarts, but got the same results. Any help with this issue will be much appreciated as I need my 2.5 min speed 3 cups of Joe. Thank you for your time and support.

## REPRODUCE STEPS
Build CM --> Place cups and ingredients (ie sugar) in appropriate slots and then try to remove them. Then try brewing a potion with a bucket of milk, bucket should disappear upon completion of the brew.

## Additional Information
I have not posted to the Actually Additions github at this time as I don't know where lies the issue. thank you again and great pack, this is my first modded MC game.

**Comment by Revvilo** [comment]
I've tested this with the latest AA on its own, in a fresh instance, and it still happens the same. So it's definitely on Actually Additions end.
Hopefully that helps out :)

**Comment by LAW-11** [comment]
Ok, thanks. I will head over to the AA github and create an issue. Should I receive any helpful feedback, I'll post it here so others may benefit. I appreciate the feedback, please enjoy your day.

**Comment by scalda** [comment]
https://github.com/Ellpeck/ActuallyAdditions/issues/1174

Mod issue
