### ISSUE TITLE
Industrial Foregoing Fluid Dictionary Converter - fluid selection arrow images missing

### ISSUE THREAD

**Issue by IntrACate** [scalda/Foolcraft_3#303]
## Issue Description

The fluid selectors (arrows above and below the selection boxes) are invisible.  They are clickable but do not appear in the Fluid Dictionary Converter GUI.

## Reproduce Steps

After crafting and placing down the Fluid Dictionary Converter from Industrial Foregoing, I right clicked the block (with empty hand) to open the GUI.  For both the Input and Output fluids, I have a red X in the selection boxes.  If I click the empty space above or below the boxes with the X's, I am able to select the desired fluid conversions.  Watching YouTube videos with the Fluid Dictionary Converter, it shows that there should be up arrows above the selection boxes and down arrows below them.

Otherwise, this functions as it should.

## Additional Information
FYI using Sphax texture pack
https://imgur.com/94vDoEo

**Comment by Revvilo** [comment]
Out of curiosity, have you tried without Sphax?
Because I'm pretty sure that's caused by the GUI texture in your Sphax patch not including those arrows.
Maybe the Industrial Foregoing addon/patch is behind a version or so.

**Comment by scalda** [comment]
This is a texture issue, they show up fine with no texture packs loaded
