### ISSUE TITLE
Additional ProjectE Condenser Recipe

### ISSUE THREAD

**Issue by nzminecraftDOTcom** [scalda/Foolcraft_3#304]
## FEATURE REQUEST
- [ ] I would like to propose an additional mod.
- [ ] I would like to propose a config change.
- [ x] I would like to propose a custom recipe.
- [ ] I would like to propose another change.

## FEATURE INFORMATION
Add an additional recipe for the condenser temporarily while the Equivalent Energistics mod is the cause of so many server crashes and removing it is the only answer to prevent that. 
See this report for more information: https://github.com/scalda/Foolcraft_3/issues/300
Just something to replace the T8 EMC storage cell required to craft the condenser is all that is really needed.

**Comment by scalda** [comment]
looking into it

**Comment by scalda** [comment]
I am from version 1.5.3 removing recipes for the drive cells as they are the things causing the issues. so as long as no one has them and places them into the drive then all will be fine. as that is where all the crashes are coming from i am awaiting AE2 to release a beta of RV6 then addons will update and fix issues
