### ISSUE TITLE
[AE2 Stuff] Wireless Crafting Terminal does not work.  Items cannot be removed from network

### ISSUE THREAD

**Issue by Inksday** [scalda/Foolcraft_3#306]
## Issue Description
When trying to use the wireless crafting terminal in AE2, I cannot remove items, I tried on multiple servers/single player worlds. I have supplied the crash report.

## Reproduce Steps
Create an AE2 network and use a wireless crafting terminal and try to remove items.

## Additional Information

https://paste.dimdev.org/tazepipazu.mccrash

**Comment by nzminecraftDOTcom** [comment]
What modifications did you make to the pack?

**Comment by Dalienx** [comment]
friend of mine had the same issue yesterday, he had to place down a security terminal and set it up

**Comment by Inksday** [comment]
I just have the windowed fullscreen mod added.   And I have a security terminal already. I can use the AE2 wireless terminal just fine, its the wireless crafting terminal that doesn't work.  The one you can put the infinity booster into.  It occurred on a server I play on.  Before I posted here I also loaded a new single player world, and set up a small network and tested and had the same issue.

**Comment by nzminecraftDOTcom** [comment]
I have the same issue. It will let me use the auto craft bit where it fills the slots for you however nothing can be pulled in and pulled out

**Comment by p455w0rd** [comment]
update wireless crafting terminal to latest RV6 version: https://minecraft.curseforge.com/projects/wireless-crafting-terminal/files/2612298 (you're using 3.9.67, you need 3.10.80)
also, the 3.9 in the version indicates AE2 RV5, 3.10 indicates RV6

on CurseForge I have also added the proper AE2 RV version for WCT:
![](https://puu.sh/Bvrsk/ebe3e23e94.gif)

**Comment by scalda** [comment]
Well that's really strange as I look this morning before posting the issue and there was no update there so not sure what happened I will update and retest thank you for the reply

**Comment by p455w0rd** [comment]
can u pls update this issue

**Comment by scalda** [comment]
Already have in FoolCraft 1.5.3/1.5.4

**Comment by p455w0rd** [comment]
thank you :)
