### ISSUE TITLE
Extra Utilities/Foundry Conflict?

### ISSUE THREAD

**Issue by H0pestart3r** [scalda/Foolcraft_3#308]
## Issue Description
I've been playing Foolcraft for a while now, with a singleplayer world that has cheats enabled. I started the world around 1.4.5, then the pack updated, and I moved up to 1.5.2, which caused the deletion of one of the blocks from my current world. Something from foundry which affected Extra Utilities I believe, a technical block relating to BurnTime when I first loaded up the world in the new update of 1.5.2. After some time of fixing up the storage, I was going to do something else in the world when the upper right corner showed a potential problem that involved Foundry and Extra Utilities 2. Something about moving the Foundry alloy maker while I was fixing up my storage, which didn't show up until later.

## Additional Information
https://pastebin.com/NGUz5Jdx
https://imgur.com/wKZka4a
By the way, am considering reporting this concern to authors of Extra Utilities 2 and Ignition: Foundry in their respective githubs as well if there is some config conflict or something with the mods.

**Comment by scalda** [comment]
i believe this is to do with the fact foundry knows there use to be a generator there so it is trying to draw power from it but sadly that block/burn time no longer exist due to ExU2 removing that function sorry
