### ISSUE TITLE
Please, give Infinite Wireless Transmitter for RefStorage back

### ISSUE THREAD

**Issue by Lizard-Of-Oz** [scalda/Foolcraft_3#309]
## FEATURE REQUEST
- [ ] I would like to propose an additional mod.
- [ ] I would like to propose a config change.
- [ ] I would like to propose a custom recipe.
- [x] I would like to propose another change.

## FEATURE INFORMATION
I think all of the RefStorage users would really like to get Refined Storage Addons rollbacked to the version with the Infinite Wireless Transmitter.
In current version without one, RefStorage is just uncompetitive to the AE2 ME System, even if RS is better in general.
And as author said, he's "not interested in feedback about this removal", so, it's up to FoolCraft to make it back.

**Comment by nzminecraftDOTcom** [comment]
What you are saying, sounds as if the mod creator removed it and you want it back in fc3, if so that's not going to be possible unless there is an older mod version used. Rs is very heavy on servers anyway and usually disabled for reasons that scream lag

**Comment by Lizard-Of-Oz** [comment]
Rolling back to the older version of RS Addons is extactly what I'm suggesting.

**Comment by scalda** [comment]
I'm sorry but if the mod author has removed it there must have been a reason why, they may not have stated why but sadly that's the way it is and I won't be rolling back a mod just because an author removed something, there must be a reason why even if we aren't privy to it.

sorry

**Comment by Lizard-Of-Oz** [comment]
Can I suggest [Universal Remote](https://minecraft.curseforge.com/projects/universal-remote) mod then?

**Comment by scalda** [comment]
i will look into it thanks for the suggestion
