### ISSUE TITLE
Mods Suggestion

### ISSUE THREAD

**Issue by useenzhekoay** [scalda/Foolcraft_3#31]
## SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Mod suggestion for automation creation that using items' NBT data.
In pack v1.0.0, there are few similar mods doing similar things but there are different.
OpenComputers - If not mistaken, OpenComputers also can read and playing through items' NBT data to archive automation but required to understand Lua programming before using.
XNet - Simple mods that can allow highly configurable automation creation but not powerful as suggested mods as it can really reading NBT data to create automation.

## Reproduce Steps
Add Integrated Dynamics ([Link to Curse](https://minecraft.curseforge.com/projects/integrated-dynamics)) and Integrated Tunnels ([Link to Curse](https://minecraft.curseforge.com/projects/integrated-tunnels))

## Additional Information
Mods suggested are just try to save time on tedious progression such as Astral's crystal growing.

**Comment by scalda** [comment]
Sorry but won't be adding integrated dynamics/tunnels as like you have said opencomputers and Xnet can already do the same thing
