### ISSUE TITLE
Server Crash?

### ISSUE THREAD

**Issue by alextunbridge67** [scalda/Foolcraft_3#312]
## Issue Description
Everytime I join the server it crashes.

## Reproduce Steps

Server is running, I join server.

## Additional Information

https://pastebin.com/uC9aptXN

**Comment by nzminecraftDOTcom** [comment]
Looks like when you join, you possibly load a whole lot of items that are sitting on the ground, or animals etc and the server can not handle it and it crashes (As says the crash reason - a whole tick taking a minute)

**Comment by alextunbridge67** [comment]
> Looks like when you join, you possibly load a whole lot of items that are sitting on the ground, or animals etc and the server can not handle it and it crashes (As says the crash reason - a whole tick taking a minute)

Increased the maximum tick time and had someone else join. They found about 500 carrots sitting at my base. Picked them up and the issue is resolved. Weird. Didn't think 500 entities would cause so much trouble.

**Comment by nzminecraftDOTcom** [comment]
That would probably be 500 stacks then as they group up

**Comment by generrosity** [comment]
It mounts up. "/profile e" would confirm how much impact and how many it was too. I think recently there is a mod added to agressively delete stacks of entities, but even that wouldn't be fast enough without maxticktime.

Dont forget to hit the "commend and close" if its all sorted now.
