### ISSUE TITLE
Mod Suggestion: ME Capability Adapter

### ISSUE THREAD

**Issue by Yadokingu** [scalda/Foolcraft_3#32]
Since Compact machines and Applied Energistics 2 are in this pack, it would be great if the ME Capability Adapter mod could be added. It allows to route ME channels through compact machine walls, like you can usually do with conduits and redstone. It makes the compact machines a lot more usefull, since you can easily add them to the network, which means people will use them more, which will reduce some lag.

The mod can be found here: https://minecraft.curseforge.com/projects/capability-adapter

**Comment by scalda** [comment]
Awaiting iskalls approvel

**Comment by Yadokingu** [comment]
Man, Iskall's approval is harder to get than my father's.

**Comment by scalda** [comment]
oh i forgot about this he said no regarding it. sorry
