### ISSUE TITLE
Vanilla Chests Won't Open

### ISSUE THREAD

**Issue by ArrowsTheHunter** [scalda/Foolcraft_3#35]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I can not open vanilla chests/double chests, crafted or generated.

## Reproduce Steps
I've created new worlds and attempted to craft and open chests, I've also downloaded the modpack again and got the same result.

**Comment by TagsonOG** [comment]
1st, Yes I am a "random" but, 2nd are you using optifine? if yes try taking that off because people have experienced problems with chests there 👍

**Comment by TagsonOG** [comment]
I just remember that people have had problems with optifine and modded using chests and well vanilla too (i have experienced it so i searched the problem and well found that problem on some forums)

**Comment by ArrowsTheHunter** [comment]
Updating optifine to HD U D3 worked.
