### ISSUE TITLE
Blue screen then crash, may be to do with morph mod

### ISSUE THREAD

**Issue by TheDominantMeme** [scalda/Foolcraft_3#36]
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [ ] I can reproduce this issue consistently
     - [ ] In single player
     - [ ] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [x] I am crashing and can provide my crash report(s)

## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

**Comment by Mrbysco** [comment]
Please fill in the rest of the section. 
We need to be able to reproduce the issue in order to fix it.
