### ISSUE TITLE
Elevator from RFTools vs FTBUtils Leads to crash 

### ISSUE THREAD

**Issue by ajdjyt** [scalda/Foolcraft_3#39]
## Modpack Information
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [x] In single player
     - [ ] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [x] I am crashing and can provide my crash report(s)
- [ ] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
i have crashed twice when using the elevator fron rftools in a "claimed and chunkloaded" area using FTButils in my base. 

## Reproduce Steps
use an elevator from rftools in a chunkloaded and claimed area using FTButils

## Additional Information
i have added optifine

[crash-2018-05-26_11.19.29-server.txt](https://github.com/scalda/Foolcraft_3/files/2041372/crash-2018-05-26_11.19.29-server.txt) Crash no 2
[crash-2018-05-24_23.33.53-server.txt](https://github.com/scalda/Foolcraft_3/files/2041373/crash-2018-05-24_23.33.53-server.txt) Crash no 1

**Comment by kpeckett** [comment]
Does disabling OptiFine stop the crash?
Which version of OptiFine are you using?

**Comment by ajdjyt** [comment]
OptiFine 1.12.2 HD U D3

**Comment by scalda** [comment]
No updates to this so will be closing the issue, plus as it's an elevator from rftools please report to rftools github
