### ISSUE TITLE
Recipe Alloy smelter

### ISSUE THREAD

**Issue by TheDutchMC04** [scalda/Foolcraft_3#4]
Recipe requires Energized Bimetal Gear, which requires Energetic Alloy Nugget, which requires Energetic Alloy, which is made in an alloy smelter.

**Comment by cheekytree** [comment]
dutch in this version there are 2 types you have to make the basic one first hope this helps

**Comment by aelfwyne** [comment]
I know this is "as designed" but it's quite a game blocker. The basic alloy smelter won't smelt the energetic alloy - it seems to take fewer recipes. How are we supposed to get started on this chain?
