### ISSUE TITLE
Experience dupe bug

### ISSUE THREAD

**Issue by Necro9227** [scalda/Foolcraft_3#40]
## Modpack Information
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [x] In single player
     - [ ] In multiplayer
- [ ] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
Similar to issue #24  the Ender IO's experience rod and actually additions solidified experience.

## Reproduce Steps
can be achieved by Either by right clicking or Shift-Right click the Ender IO Experience Rod onto a fluid tank to gain or remove XP levels so that the experience bar graphic extends / glitches  to the right of the screen. Right click an Actually Additions solidified Experience to gain XP,

if done correctly one XP orb will boost XP gain significantly, the more levels in the glitched state the higher the gain.  e.g Having 75 levels in a gliched state resulted in reaching 99 levels with one orb.

## Additional Information
old bug experienced before with not enough wands, Not sure if you can do anything about it though.

**Comment by scalda** [comment]
thanks for this i have disabled the violating offenders. sadly it's just a bad mod interaction
