### ISSUE TITLE
[Fixed it myself] Buckets no longer work

### ISSUE THREAD

**Issue by aoldude123** [scalda/Foolcraft_3#41]
## Modpack Information
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [ ] I can reproduce this issue consistently
     - [ ] In single player
     - [ ] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
After experimenting with Thaumcraft, the quest for Hedge Alchemy had me create a bucket of lava with the crucible. Now whenever i try to use a bucket it wont update, if i place a down a bucket of lava it places the block but I keep the lava in the bucket and same goes for any other liquid. And if I try to pick up a liquid with an empty bucket it wont update but the liquid is removed. 

## Reproduce Steps
Access Hedge Alchemy,
Create a bucket of lava for the 2nd stage
See

## Additional Information
 
[Fix] Just delete the player data then update with a new liquid that isnt water or lava

**Comment by generrosity** [comment]
If its fixed, do hit the "close issue" button 👍
