### ISSUE TITLE
Cloud pet flight cancels with shift

### ISSUE THREAD

**Issue by Elysara** [scalda/Foolcraft_3#42]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

When flying with the cloud pet pressing shift cancels flight instead of flying down like is normal on any other pack inventory played. Another player on the server I'm playing on confirmed the same issue as well.

Fly into the air with a cloud pet and then press shift and flight will be cancelled

**Comment by melbellrocks** [comment]
Also having this issue, but it's not FoolCraft 3 related.  It's a bug in the latest version of Inventory Pets as reported [https://github.com/capnkirok/Inventory-Pets/issues/224]here.

I have also replied to the bug in that thread with this information.

**Comment by scalda** [comment]
looks like this is being fixed once fixed it will be updated in the pack, thanks for the issue
