### ISSUE TITLE
Refined Storage Network Transmitter and Receiver are missing

### ISSUE THREAD

**Issue by melbellrocks** [scalda/Foolcraft_3#44]
## Modpack Information
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [x] In single player
     - [x] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
Refined Storage Network Transmitter and Network Receiver are not showing up in JEI and cannot be crafted.

## Reproduce Steps
I created a single player world with only Refined Storage and JEI and am able to see and craft both the Network Transmitter and Receiver.  But cannot in the FoolCraft 3 in singleplayer or multiplayer.

**Comment by Mrbysco** [comment]
They were disabled as they could create massive lag iirc.

**Comment by melbellrocks** [comment]
I understand why they would need to do this for their size server, but we are only a few people.  Maybe I'm diving in over my head, but would it break anything if I just commented out the two lines where they are disabled?  I found it in the scripts, but I have never done anything like and I don't want to mess anything up.

**Comment by Mrbysco** [comment]
It wouldn't crash but if you were to report lag or crashes that mention them they wouldn't be supported.

**Comment by melbellrocks** [comment]
couldn't figure it out anyway.  the script change we made didn't enable them and I didn't want to break anything so I am just running cables all over the place :)  thx for the info!
