### ISSUE TITLE
Nether Crash

### ISSUE THREAD

**Issue by Cod3Man2018** [scalda/Foolcraft_3#46]
## Modpack Information
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [x] In single player
     - [ ] In multiplayer
- [ ] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description

When I enter the Nether, Game crashes. Created a new game with cheats just to load the nether portal and it does the same. 
I had optifine and sphax resource pack but since the crash, I removed it and loaded the new world, Game loads to the overworld but as soon as I enter the Nether, it crashes. I dedicate over 10GB of Ram.

**Comment by scalda** [comment]
Crash Log?

**Comment by BluDraygn** [comment]
Same Issue as above, 6GB ram dedicated to MC
Crash Log 
[crash-2018-05-31_00.50.46-client.txt](https://github.com/scalda/Foolcraft_3/files/2056885/crash-2018-05-31_00.50.46-client.txt)
Turned off Thaumcraft shaders as well as moved far far away and tried entering the nether there (in case it was an issue related to that particular portal locale) no change.

**Comment by BluDraygn** [comment]
Appears to be related to issue #68 
I updated to v1.1.1 and the problem with crashing is gone.

**Comment by Mrbysco** [comment]
Issue should be gone as of V1.1.1. If not feel free to reopen this issue
