### ISSUE TITLE
Energy Condenser Crafting bug

### ISSUE THREAD

**Issue by dejanpetrov20** [scalda/Foolcraft_3#47]
Energy Condenser recipe was broken...

When i put all items on pedestals its says no recipe funded.

Here is the picture.
https://imgur.com/a/JPga7LI

**Comment by scalda** [comment]
Which recipe did you use? as there are 4?

**Comment by dejanpetrov20** [comment]
first one you see on picture

**Comment by Crucial1** [comment]
any update on this as i'm having the same issue, trying with the dice of fate and common tartaric gem on a server, but tested the recipe in single player and none of recipes seem to be working
