### ISSUE TITLE
Induction smelter unable to craft hardened glass 

### ISSUE THREAD

**Issue by MrK3nt** [scalda/Foolcraft_3#48]
## Modpack Information
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [ ] In single player
     - [x] In multiplayer
- [ ] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
When trying to make hardened glass for the "Glowstone elevation unit" it was not possible in the induction smelter. all ingot dusts can be input but it is not possible to insert fused quartz in the 2nd slot.
(not sure if this is a cause but the induction smelter gui looks different then the one shown in NEI)

## Reproduce Steps
unable to put fused quartz in induction smelter as part of crafting recipe for hardened glass.

**Comment by aolsen96** [comment]
Hardened glass is made by putting 4 pulverized obsidian and 1 pulverized lead in the induction smelter

**Comment by MrK3nt** [comment]
I guess a picture would be better. This is from nei. States you can use Invar and fused quartz to make hardened Invar glass. The recipe for the glowstone elevation unit does not say it accepts regular hardened glass.
Regardless the recipe for the picture i posted is not possible.  

![hardglass](https://user-images.githubusercontent.com/39658301/40589732-69ead220-61b8-11e8-8fd7-d5e0732e594f.jpg)

**Comment by jeviuss** [comment]
also having this problem!

**Comment by MrK3nt** [comment]
Also hardened glass via the method list above is not listed as an option in NEI in the recipe. Tried it anyways and does not work as well.

**Comment by scalda** [comment]
hardened glass production works fine in pack version 1.3 
![image](https://user-images.githubusercontent.com/1837979/41156331-5cc6f690-6b19-11e8-8723-2a95ddb188f3.png)

**Comment by MrK3nt** [comment]
The issue was not hardened glass production. It's was the recipe for the other types that involve other metals.
like "Invar hardened glass". I guess the title alone might be misleading with about reading the description.

Issue was listed in description that "Glowstome elevation unit" is not craftable"
Hardened glass is craftable but is not an option to make the Glowstome elevation unit.

**Comment by scalda** [comment]
all the metal glasses work for me i just tested it, including the invar one you stated above

![image](https://user-images.githubusercontent.com/1837979/41158525-2dc15e00-6b21-11e8-98da-1e2bb05d0570.png)
