### ISSUE TITLE
disappearing textures

### ISSUE THREAD

**Issue by Temutschin** [scalda/Foolcraft_3#49]
## Modpack Information
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [x] In single player
     - [ ] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

I recently downloaded Foolcraft 3 at first having problems with game crashes so i used fixes to use the latest version of Java. after that the crashes were almost gone but the main issue is me loosing textures, mainly mob textures and vanilla chest textures disappear after some time. The blocks/mobs are there and do damage /can be used but after some time they loose their texture till i restart the game 

https://imgur.com/a/Jfjz9tA

**Comment by Temutschin** [comment]
with the 1.1.0 foolcraft update the time till the textures start to disappear seems to shorten. hope its just some settings on my pc but they should be ok

**Comment by scalda** [comment]
this would be a client-side issue, my answer would be to just reinstall the pack in case there are textures missing
