### ISSUE TITLE
Unstable ingot uncraftable

### ISSUE THREAD

**Issue by Mundbjerg8** [scalda/Foolcraft_3#51]
## Modpack Information
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [x] In single player
     - [ ] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
I can't craft unstable ingots. I AM using a vanilla crafting table. I suppose it's because vanilla crafting tables can keep their inventory in FC3

## Reproduce Steps
Craft an unstable ingot in vanilla crafting table. 

## Additional Information
https://imgur.com/gallery/YgWxWfZ

**Comment by Mundbjerg8** [comment]
But I mean, it is supposed to work in a vanilla crafting table. Not a very good fix, if it means I can't get unstable ingots in early game.. Would rather have it fixed for real in the pack.

**Comment by scalda** [comment]
this has been reported multiple times but please try with the new 1.3 version of the pack that is coming out today
