### ISSUE TITLE
Large Chance cubes at y=256 crashes world and corrupts pack

### ISSUE THREAD

**Issue by ajdjyt** [scalda/Foolcraft_3#52]
## Modpack Information
- [X] I am running the latest version of FoolCraft
- [X] I am running FoolCraft via Curse/Twitch Launcher
- [ ] I can reproduce this issue consistently (have not tried to reproduce yet)
     - [ ] In single player
     - [ ] In multiplayer
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [ ] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
i was in a world on peaceful mode breaking large chance cubes which when i opened one at y=256 or maybe 255. my game crashed and has not loaded since i have tried loading the pack again trice to no luck :(

## Reproduce Steps
try opening large chance cubes at y=256

## Additional Information
i have added optifine
[crash-2018-05-26_14.25.12-client.txt](https://github.com/scalda/Foolcraft_3/files/2042721/crash-2018-05-26_14.25.12-client.txt)

**Comment by scalda** [comment]
this is because you are opening them at that height and most cubes try to generate stuff above them and so they can't in turn causing a crash
