### ISSUE TITLE
COFH Soulbound and EnderIO Soulbound don't work

### ISSUE THREAD

**Issue by melbellrocks** [scalda/Foolcraft_3#55]
## Modpack Information
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [x] In single player
     - [x] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
I have items with both the Soulbound III (from COFH) and Soulbound (from EnderIO) on them, and they do not stay in my inventory upon death.

## Reproduce Steps
Soulbind some stuff and die.

**Comment by scalda** [comment]
Thes have been resolved in the 1.1.1 version of the pack, please see the changelogs
