### ISSUE TITLE
Downgrade thaumcraft

### ISSUE THREAD

**Issue by strikerrocker** [scalda/Foolcraft_3#57]
Asof update 1.1.0 to fc thaumcraft was updated to beta 15. And thaumcract beta isnt stable at all and causes many crashes. Here is one of it from iskallian discord : https://pastebin.com/zUBzHGZ0 thus i request you immediately downgrade thaumcraft to beta13 as it stable version of thaumcraft as of time of making this issue. Thanks for reading.

**Comment by strikerrocker** [comment]
Just realized i didnt use the template its due to the fact that i created the issue on mobile it didnt show choices for template. Sry again.

**Comment by strikerrocker** [comment]
#58

**Comment by xxlilylolzxx** [comment]
How do i downgrade thaumcraft?
