### ISSUE TITLE
Update 1.1.0 causes crash after 5-10 mins apparently due to thaumcraft particles (crash report attached)

### ISSUE THREAD

**Issue by Lightning-Box** [scalda/Foolcraft_3#58]
[crash-2018-05-28_19.02.03-client.txt](https://github.com/scalda/Foolcraft_3/files/2045883/crash-2018-05-28_19.02.03-client.txt)

## Modpack Information
- [yes] I am running the latest version of FoolCraft
- [Twitch but using Java not native] I am running FoolCraft via Curse/Twitch Launcher
- [yes] I can reproduce this issue consistently
     - [only here] In single player
     - [dont play fc3 here ] In multiplayer
- [1] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [see attached] I am crashing and can provide my crash report(s)
- [nope not touched it I'm crap at this stuff :)] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

fc3 launches as normal loads everything I get into my single player world play normally and within 5-10 minutes my client crashes and I get the same error report every time see attached
## Issue Description

 I don't know I just launched fc3 1.1.0 using the Java launcher via twitch played normally and it crashed randomly I cant seem to get a specific action to trigger it (sorry I cant help here)
## Reproduce Steps

 https://pastebin.com/zUBzHGZ0

**Comment by scalda** [comment]
1.1.1 has been pushed to curse that will have the downgraded version of thaumcraft sorry for the issues

**Comment by Lightning-Box** [comment]
Thx man ;)
