### ISSUE TITLE
Server instantly crashes on startup after updating to 1.1.0

### ISSUE THREAD

**Issue by SpeedySpy52** [scalda/Foolcraft_3#59]
## Modpack Information
- [x] I am running the latest version of FoolCraft
- [ ] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [ ] In single player
     - [x] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [x] I am crashing and can provide my crash report(s)
- [x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
See title. The server loads up all the way, and then it crashes either immediately once a player tries to connect.

## Reproduce Steps
Update a 1.0.0 server to 1.1.0 (by replacing the mods, config, and scripts folders) and launch it.

## Additional Information
https://pastebin.com/nYp5KK04

**Comment by Mrbysco** [comment]
The log states it saved a crash logs. Could you put that one on pastebin and link it?

**Comment by SpeedySpy52** [comment]
https://pastebin.com/2KVuYzNw

**Comment by Mrbysco** [comment]
1.1.0 has been removed from Curse/Curseforge and 1.1.1 has been released to fix some of the issues 1.1.0 caused.

I would say wait before updating a server until official server files release.

**Comment by SpeedySpy52** [comment]
Alright, thanks for the help
