### ISSUE TITLE
Foolcraft 3 not working

### ISSUE THREAD

**Issue by xxlilylolzxx** [scalda/Foolcraft_3#63]
so idk how to fix this. someone help me please. 
<img width="1038" alt="screen shot 2018-05-28 at 5 22 57 pm" src="https://user-images.githubusercontent.com/39716925/40634447-86d7bbde-62a1-11e8-8bc8-d2ab21c197fa.png">

**Comment by scopiplays** [comment]
the server is still on 1.0, but the client was updated to 1.1.  Both Client and Server require the same version of the pack.

**Comment by xxlilylolzxx** [comment]
how do i do that?

**Comment by Mrbysco** [comment]
For now you need to downgrade to 1.0

**Comment by scalda** [comment]
your server hasn't updated as i haven't uploaded the server files
