### ISSUE TITLE
Error on line 96 in 00-recipes.zs

### ISSUE THREAD

**Issue by Electrofried** [scalda/Foolcraft_3#65]
## Modpack Information
- [x ] I am running the latest version of FoolCraft
- [x ] I am running FoolCraft via Curse/Twitch Launcher
- [x ] I can reproduce this issue consistently
     - [x ] In single player
     - [x ] In multiplayer
- [x ] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [x ] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description

00-recipes.zs contains a bug on line 96 

recipes.addShapeless(<astralsorcery:itemcraftingcomponent>, [<minecraft:ender_pearl>, <minecraft:diamond>);

should be:

recipes.addShapeless(<astralsorcery:itemcraftingcomponent>, [<minecraft:ender_pearl>, <minecraft:diamond>]);

## Reproduce Steps

load pack, see craft tweaker error log

**Comment by scalda** [comment]
Thanks for this, this would explain why a lot of peoples scripts aren't working, I must have missed this and the syntax command didn't even pick it up.

Thanks for letting me know

**Comment by Electrofried** [comment]
This is why I use atom with zenscript formatting enabled when writing scripts. It really helps to keep track of syntax highlighting. :)
