### ISSUE TITLE
iChisel deletes stacks of items and replaces with a single item

### ISSUE THREAD

**Issue by rosso4001** [scalda/Foolcraft_3#66]
## Modpack Information
- [y ] I am running the latest version of FoolCraft
- [ y] I am running FoolCraft via Curse/Twitch Launcher
- [y] I can reproduce this issue consistently
     - [y ] In single player
     - [ ] In multiplayer
- [y ] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [y ] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
When I use the iChisel (Chisel Mod) on stacks of cobblestone and shift-click the chisel all option. It deletes the whole stack and leaves only 1 item per stack chiselled.
(Also works with glass.)

## Reproduce Steps
Craft an iChisel
Collect several stacks of cobblestone.
Hold shift and chisel all stacks.
Stacks of items will be deleted and will be replaced with a single item.

## Additional Information
https://imgur.com/j0U3NEK (Before)
https://imgur.com/nzd6FtL (After)

**Comment by scalda** [comment]
the ichisel recipe is disabled in the pack so either your scripts aren't working or you have modified the pack to which the scripts aren't working please confirm the above?

**Comment by rosso4001** [comment]
I haven't touched any configurations with the pack or modified the pack at all.

**Comment by Elysara** [comment]
Scalda, will ichisel be enabled in foolcraft? as someone who uses the chisel mod a lot it's really tedious not having the ichisel

**Comment by kpeckett** [comment]
I believe it is disabled due to bugs like this one - if it worked with minimal bugs, I don't doubt it would be enabled

**Comment by Elysara** [comment]
I would imagine that would be an easy fix if that's the only real problem, monsterpack pack had the same issue initially as well but was quickly fixed
