### ISSUE TITLE
Crashes when logging in in Nether

### ISSUE THREAD

**Issue by TrueSandwich** [scalda/Foolcraft_3#69]
## Modpack Information
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [x] In single player
     - [ ] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [x] I am crashing and can provide my crash report(s)
- [x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
I am in the nether and I crash every time I load up the world. When I set the render distance to 2, It loads the world around me perfectly, but if I turn up the render distance, I crash. This leads me to believe that it is a block somewhere in the nether around me that is causing the crash.

## Reproduce Steps
I am unsure of how this issue could be reproduced in a world besides mine.

## Additional Information
Crash report - https://pastebin.com/k8CQ6dFR

**Comment by Mrbysco** [comment]
Version 1.1.1 has been out for 6 hours. You should update

**Comment by TrueSandwich** [comment]
That seems to have fixed it, Thank you
