### ISSUE TITLE
Change Applied Energistics

### ISSUE THREAD

**Issue by TrueSandwich** [scalda/Foolcraft_3#70]
## FEATURE REQUEST
- [x] I would like to propose an additional mod.
- [ ] I would like to propose a config change.
- [ ] I would like to propose a custom recipe.
- [ ] I would like to propose another change.

## FEATURE INFORMATION
I think Applied Energistics 2 should be replaced with Applied Llamagistics because it has more content than Applied Energistics 2, Has the Addon mod Applied Fluidics to allow for fluid storage, and I believe it is more stable than Applied Energistics 2 because Applied Energistics 2 is made by the community which can lead to it being less stable, Applied Llamagistics is made by one person.

## MOD INFORMATION
Applied Llamagistics - https://minecraft.curseforge.com/projects/applied-llamagistics

**Comment by TrueSandwich** [comment]
Ok, thought I'd try though

**Comment by scalda** [comment]
This would be to world breaking this late into the pack being out but thanks for the suggestion thou
