### ISSUE TITLE
Good Ol' Currency Mod Manual Crash

### ISSUE THREAD

**Issue by Protius7331** [scalda/Foolcraft_3#71]
## Modpack Information
- [ ] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [ ] I can reproduce this issue consistently
     - [ ] In single player
     - [x] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [x] I am crashing and can provide my crash report(s)
- [x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
When using the "Currency for Blockheads" manual for the currency mod, I consistently crash while trying to read the book, seems to after a specific length of time not based on the page I'm on.

## Reproduce Steps
Craft or spawn the "Currency for Blockheads" book from the "Good Ol' Currency Mod" and open it. Flip to random pages and it will eventually crash the client. 
*Note: Have had this issue in MP only, have not tried SP yet.

## Additional Information

I am not running the latest version of the pack, still on 1.0.0, as the server I play on hasn't updated.
The crash is similar in feeling to the Immersive Engineering manual crash that occurred in the past.
I will also be reporting on the mod Github if it isn't already there.
https://pastebin.com/Zverm8Ka
https://pastebin.com/hYtN7AdM

**Comment by scalda** [comment]
I have reported it to the mod devs thanks for the issue
