### ISSUE TITLE
Soulbound not working 

### ISSUE THREAD

**Issue by Flekrad** [scalda/Foolcraft_3#73]
## Modpack Information
- [ ] I am running the latest version of FoolCraft
- [x ] I am running FoolCraft via Curse/Twitch Launcher
- [ ] I can reproduce this issue consistently
     - [ ] In single player
     - [ x] In multiplayer
- [ x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
Died in The END 
Had no items in inventory after respawning (except for death list) 
Armour and various Items had Soulbound III 
![2018-05-30_19 06 49](https://user-images.githubusercontent.com/29991384/40712402-cde922a0-643c-11e8-8d34-3810ba27c4ae.png)

## Additional Information
These enchants were removed from Looted Items via AA Disenchanter  and then applied to items 
(This was NOT the Soulbound enchant created by the EnderIO Enchanter) 
Client and Server  version 1.0
Found this link to an issue previously mentioned 
https://github.com/scalda/Foolcraft_3/issues/7

**Comment by scalda** [comment]
sould bound enchant from CofhCore has been disabled in the pack as it was causing issues with the ender io one

**Comment by Flekrad** [comment]
Cheers for response
