### ISSUE TITLE
Angel ring uncraftable

### ISSUE THREAD

**Issue by ThomasJDavid** [scalda/Foolcraft_3#74]
## Modpack Information
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [x] In single player
     - [ ] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [x] I am crashing and can provide my crash report(s)
- [x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

The crafting core displays "No recipe found" in the user interface when the flux infused jetplate is on top of the core and all eight of the items have been placed on the 8 pedestals which are all in range. I've tried some other recipes with the crafting core and as far as i can tell it's only the angel ring that has this issue.

Place the crafting core and give it power
place all eight pedestals within three blocks
place jetplate on core and other items on pedestals and give core RF power
open core UI and it says "no recipe found"

**Comment by ExZha1337** [comment]
Can confirm, i have the same issue.

**Comment by billyty08** [comment]
Same here I even drained all the energy from the jetpack to make it exactly as recipe

**Comment by moshan1997** [comment]
Confirm same problem

**Comment by moshan1997** [comment]
Should be nbt problem

**Comment by Elysara** [comment]
it does work on 1.0.0 version of the pack fyi, just crafted one and the server i'm on is still on that version.

![2018-06-02_19 10 10](https://user-images.githubusercontent.com/36612716/40881606-0d669daa-6699-11e8-84c4-422b325b84c1.png)

**Comment by moshan1997** [comment]
I think the recipe in 1.0 got a empty golden and curse so It dont have much nbt to handle

**Comment by oacaptain** [comment]
Same thing here on version 1.2.0 the latest!! not craftable and tried the same thing emptying the energy from the jet-pack, still the same!!

**Comment by scalda** [comment]
1.3 all extended crafting recipes are working well atleast from my testing when i fixed them all, so please update when the new version is out and post if you still have issues thanks again scalda

**Comment by oacaptain** [comment]
![2018-06-08_22 16 55](https://user-images.githubusercontent.com/34013573/41176672-fda4f314-6b69-11e8-9ee5-04dd718a9b4c.png)
![2018-06-08_22 18 05](https://user-images.githubusercontent.com/34013573/41176673-fdcbfe00-6b69-11e8-9113-63e627af3cdd.png)

Sorry Scalda what am I doing wrong here, just updated to 1.3.0, and still can't craft it!!

**Comment by swardhagen** [comment]
Same issue here, I'm in 1.3.0 and my example looks just like the one above. I have power, the pedestals register, the items are exactly the ones specified. I have triple checked.

**Comment by swardhagen** [comment]
Tried it in a 1.3.0 creative world as well, am I forgetting something?

![2018-06-11_02 45 04](https://user-images.githubusercontent.com/33746229/41208244-8e4f7994-6d21-11e8-8761-1653d46ae0d3.png)
![2018-06-11_02 44 58](https://user-images.githubusercontent.com/33746229/41208245-8e690d78-6d21-11e8-976f-42f2dfddf779.png)

**Comment by swardhagen** [comment]
And in 1.3.1 the recipe is changed to also include a decorative pufferfish statue and a decorative ghast statue? It works in creative with those but it got a looot harder to make in survival.
