### ISSUE TITLE
Additional redstone options

### ISSUE THREAD

**Issue by MysticFrog** [scalda/Foolcraft_3#75]
## FEATURE REQUEST
- [x] I would like to propose an additional mod.
- [ ] I would like to propose a config change.
- [ ] I would like to propose a custom recipe.
- [ ] I would like to propose another change.

## MOD INFORMATION

_**Redstone upgrade update**_

Redstone paste
https://www.curseforge.com/minecraft/mc-mods/redstone-paste
Torch Lever
https://www.curseforge.com/minecraft/mc-mods/torch-lever
Automated Redstone
https://www.curseforge.com/minecraft/mc-mods/automated-redstone

Or perhaps Iskall85 can convince Bumbo to have a play with the addition of this mod
Mumbo's Redstone Additions
https://www.curseforge.com/minecraft/mc-mods/mumbos-redstone-additions

**Comment by Twan23** [comment]
I think it's a great idea

**Comment by scalda** [comment]
They are all great ideas and would fit in a smaller less techy based pack, as most of that stuff if not all can be done via various mods and such. but thanks for the great suggestions
