### ISSUE TITLE
Unable to craft flux infused jetplate due to not being able to craft energy cells above basic

### ISSUE THREAD

**Issue by Kerellian** [scalda/Foolcraft_3#76]
## Modpack Information
- [x ] I am running the latest version of FoolCraft
- [ x] I am running FoolCraft via Curse/Twitch Launcher
- [x ] I can reproduce this issue consistently
     - [ x] In single player
     - [x ] In multiplayer
- [x ] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
I am not able to craft Energy cells above basic. I can see them in JEI but when i click on them no recipe comes up. I tried crafting them with known recipes but I have been unable to. I have not found any info on changed recipes for this. This is preventing me from making the Resonant Flux Pack (Armored) for the Flux Infused Jetplate. This is happening both on single Player and on a multiplayer server. 

## Additional Information
![2018-05-31_07 40 20](https://user-images.githubusercontent.com/18649933/40792511-f62954c0-64ae-11e8-8f9d-a155e754388c.png)
![2018-05-31_07 40 31](https://user-images.githubusercontent.com/18649933/40792517-f9c431a4-64ae-11e8-8293-a2f774fd244c.png)

**Comment by Mrbysco** [comment]
Thermal Expansion/foundation machines are upgraded by placing them and then right-clicking with upgrade kits. 

That's why there is no recipes. It's in-world interaction.

**Comment by Kerellian** [comment]
When did this change? When i looked up anything to do with thermal i always got linked to the recipes .
But thank you for letting me know closing the issue
