### ISSUE TITLE
Botania items only craft into one product instead of a given number

### ISSUE THREAD

**Issue by SpeedySpy52** [scalda/Foolcraft_3#77]
## Modpack Information
- [x] I am running the latest version of FoolCraft
- [ ] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [ ] In single player
     - [x] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
See below

## Reproduce Steps
Attempt to craft a botania item such as a Block of Mana Diamond or Tall Mystical Flower into Mana Diamonds/Petals/Whatever. It will only give one Mana Diamond/Petal instead of the expected number, which were 9 and 4.
This issue seemingly cannot be reproduced in Singleplayer but is consistent on my server.

**Comment by Mrbysco** [comment]
I've crafted blocks into individual ingots many times with a Refined Storage system and never experienced this issue

**Comment by SpeedySpy52** [comment]
[![Screenshot from Gyazo](https://gyazo.com/a088ef148ce7c8fac6fdf7dab9ed06d5/raw)](https://gyazo.com/a088ef148ce7c8fac6fdf7dab9ed06d5)

Here's a gif of me demonstrating the problem. A friend who also has a RS system is having the exact same issue. It doesn't apply with all items, as I was able to make gold nuggets just fine.

**Comment by Mrbysco** [comment]
Must be you. As I've just tried it on the server I play on and was unable to reproduce the issue.
Have you tried puting a clean version of Foolcraft 3 on the server?

**Comment by SpeedySpy52** [comment]
We just updated our server to 1.2.0 and that seems to have fixed the issue. Problem solved I guess!
