### ISSUE TITLE
Textures Switching and breaking

### ISSUE THREAD

**Issue by TrueSandwich** [scalda/Foolcraft_3#78]
## Modpack Information
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [ ] I can reproduce this issue consistently
     - [ ] In single player
     - [ ] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
The Textures of a number of blocks my world are "broken" so to say. They have the textures of other blocks on them. If I break and replace the blocks then they will still have the wrong textures. Even if I Save and Quit and then Start the world back up, The textures are still broken.

## Reproduce Steps
I am unsure of how to reproduce this issue.

## Additional Information
Blocks with Texture issues - https://imgur.com/a/XaihZ2C

**Comment by Axieum** [comment]
You're not alone with this issue. Our server recently faced this yesterday and now the server continuously is out of memory and crashing, essentially got to restore a backup but the mod that is in control of backups in this pack creates backups regardless of whether anything changed in the world, so we've got hours of backups where players weren't even online. If I recall correctly, AromaCore1337 had a very smart backup system.

As a side note, our server has ran many packs in the past, and it appears that the HermitCraft and FoolCraft packs have always resulted in some form of world corruption - hopefully this is just a coincidence though with a conflicting mod and not configuration changes.

**Comment by scalda** [comment]
the server has nothing to do with textures all that is dealt with client-side so my answer to the problem is to reinstall the pack as there may have been a corrupted download from curse causing it.
