### ISSUE TITLE
still not all hoes working in farming station

### ISSUE THREAD

**Issue by jkhsjdhjs** [scalda/Foolcraft_3#79]
## Modpack Information
- [x] I am running the latest version of FoolCraft
- [ ] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [x] In single player
     - [x] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
Release 1.1.0 states that the issue with some hoes not being usable in the farming station has been fixed. I tested the hoe compatibility with every item that has "hoe" in its name and is a hoe.
The Red Matter Hoe (projecte:item.pe_rm_hoe) is now supported in 1.1.0, the other hoes that weren't supported in 1.0.0 still aren't:
```
projecte:item.pe_dm_hoe
thaumcraft:thaumium_hoe
thaumcraft:void_hoe
thaumcraft:elemental_hoe
cactusmod:cactus_hoe
tp:wub_hoe
```

## Reproduce Steps
Start a game, place a farming station and equip it with a capacitor. Then try to place one of the hoes listed above in it.

**Comment by kpeckett** [comment]
Is this still an issue in v1.1.1?

**Comment by Mrbysco** [comment]
I'm the one who added the hoe's to the EnderIO config for compatability. I have no clue what's happening as I've added them correctly

**Comment by Mrbysco** [comment]
Looked into it. Found the issue.

**Comment by jkhsjdhjs** [comment]
@kpeckett
On curse it says 1.1.1, but in the main menu 1.1.0. I guess it's the same.

@Mrbysco 
Nice, thank you!

**Comment by Mrbysco** [comment]
1.2.0 released which should fix the issue
