### ISSUE TITLE
Pam's Harvestcraft Market Spawn Egg bug

### ISSUE THREAD

**Issue by iriszs** [scalda/Foolcraft_3#8]
When you buy the spawn chicken egg in the pam's harvestcraft market, you get a regular 'spawn' egg. You can't do anything with it. I didn't check for other eggs since I ran out of emeralds

![2018-04-18_00 35 46](https://user-images.githubusercontent.com/28862461/38902359-7cd530e2-42a0-11e8-996d-5a3ea38fa1a5.png)

**Comment by KendirkRS** [comment]
Yeah i believe this is the something to do with the way minecraft does spawn eggs with an entity tag rather than individual eggs on a server i used to be with we just ended up making custom recipes with items to do with what spawn egg you wanted and the egg you get from the market
