### ISSUE TITLE
Different reasons for server and client crashes

### ISSUE THREAD

**Issue by momito777** [scalda/Foolcraft_3#80]
## Modpack Information
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [ ] In single player
     - [x] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
Issue 1:
Wither skeletons from powered spawners drop insane amounts of EXP.

Issue 2:
Killing a Crimson portal (note it is the actual portal that I am talking about) and morphing into it will cause the players that are rendering you to have their game crash.

Issue 3:
VeinMiner is still causing the server to crash because of crazy amounts of exp that it drops. Although very rare, it still happens. The server goes in the same error state as issue 4.

Issue 4:
Server randomly goes into an error state and doesn't respond. It doesn't crash, therefore doesn't generate a crash log so i'm not sure what is crashing the server.

"> [21:56:51] [Netty Epoll Server IO #14/ERROR] [FML]: NetworkDispatcher exception
io.netty.handler.timeout.ReadTimeoutException: null"

## Reproduce Steps
Issue 1:
Setup a powered spawner with wither skeletons in it and spawn them. Kill the wither skeletons with a killer joe, equiped with a ender sword, enchanted with sharpness 5, mending, looting 3, and vorpal 3.

Issue 2:
Kill a Crimson portal and morph into it with other people looking at you.

Issue 3:
Mine ores that drop EXP with VeinMiner, the glitch happens very rarely, but i have had people claim that they crashed my server because of that glitch, even in version 1.1.1 of Foolcraft 3.

Issue 4:
Reason unknown...
"> [21:56:51] [Netty Epoll Server IO #14/ERROR] [FML]: NetworkDispatcher exception
io.netty.handler.timeout.ReadTimeoutException: null"

## Additional Information
The only thing I have changed in the server files are the configs. I made sure that immersive engineering villagers and villager houses are not spawning since they are known to cause crashes. I also removed VeinMiner since the crashes I had and the server seems to be crashing less often. I set worlgen to BIOMESOP in order to get the proper level generation.

**Comment by Mrbysco** [comment]
Immersive Engineering villagers / houses shouldn't crash servers. I know of multiple servers that have them enabled and they never crashed because of it

**Comment by Mrbysco** [comment]
Response to issue 2: This is a known bug and can't be fixed because Morph's blacklist does not work currently.

Never experienced issue 3 or 4

**Comment by theBluebaerry** [comment]
Response to issue 2: Is the player morphing wearing a hat? We have found on our server that your issue happens when the portal player is wearing a hat, but everything is fine and dandy so long as they do not wear one.

**Comment by Mrbysco** [comment]
Then we've narrowed that down to the hats interaction.
Sadly there's no way to fix it without morph updating or thaumcraft fixing it.

**Comment by scalda** [comment]
closed due to bad mod interaction that mod devs are still working on
