### ISSUE TITLE
Emeralds stolen from Market

### ISSUE THREAD

**Issue by AshenPheonix** [scalda/Foolcraft_3#81]
## Modpack Information
- [ x ] I am running the latest version of FoolCraft
- [ x ] I am running FoolCraft via Curse/Twitch Launcher
- [ x ] I can reproduce this issue consistently
     - [x ] In single player
     - [ ] In multiplayer
- [x ] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [x ] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
Things Stolen

## Reproduce Steps
1) Go to a Pam's Market
2) Place more than 1 emerald in the "money" slot
3) buy stuff until you have a full inventory
4) leave, leaving one or more emeralds inside the slot
5) realize emeralds aren't on ground and are no longer in the market

**Comment by TrueSandwich** [comment]
I have had this issue in other packs so I believe it is an issue with the mod, not the pack itself.

**Comment by scalda** [comment]
yes the market is very broken in pams it has been reported to the mod author thanks for the issue
