### ISSUE TITLE
AE2 inscriber doesn't accept silicon from refined storage

### ISSUE THREAD

**Issue by jkhsjdhjs** [scalda/Foolcraft_3#83]
## Modpack Information
- [x] I am running the latest version of FoolCraft
- [ ] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [x] In single player
     - [x] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
The Inscriber from Applied Energistics 2 as well as the Advanced Inscriber from AE2 Stuff don't accept the silicon provided by Refined Storage. They only accept EnderIO's silicon.

## Reproduce Steps
Build an Inscriber and try to place silicon from refined storage in it.

**Comment by scalda** [comment]
Ok thanks for this i will sort this out for 1.4 version of the pack

**Comment by jkhsjdhjs** [comment]
This hasn't been fixed yet...

**Comment by scalda** [comment]
sorry meant to post fixed in 1.5.1 next pack version

**Comment by jkhsjdhjs** [comment]
Ah, okay!

**Comment by scalda** [comment]
Sadly i cannot find a way to get this to work sorry
