### ISSUE TITLE
Instant veinmine with philosopher's stone

### ISSUE THREAD

**Issue by leetstuff** [scalda/Foolcraft_3#85]
## Modpack Information
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [x] In single player
     - [ ] In multiplayer
- [ ] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
I'm not quite sure if it's an issue or feature, but it's very OP. You can instant veinmine using the philosopher's stone on any block it can alter (vanilla leaves and logs, dirt, sand, cobble, stone, etc)

## Reproduce Steps
Hold the vein mine key and right click on a block that the Philosopher's Stone can alter and it will vein mine instantly.

**Comment by scalda** [comment]
Yes i am aware of this and if you look in the veinmine config file the chest transporter and the philosophers stone are added yet does not work. this needs reporting to the mod dev looks like it didn't in the initial testing of the pack
