### ISSUE TITLE
Astral Sorcery Starmetal Ore unable to aquire

### ISSUE THREAD

**Issue by greatmonkey** [scalda/Foolcraft_3#86]
## Modpack Information
- [x ] I am running the latest version of FoolCraft
- [ x] I am running FoolCraft via Curse/Twitch Launcher
- [ x] I can reproduce this issue consistently
     - [x ] In single player
     - [ ] In multiplayer
- [ x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
Starmetal Ore is made thought transmutation of Iron Ore and from what I can see, is the only way to obtain it.  I have link a crystal that was found in a temple to some ore and left it running over night but it never did change over.  I also used a lens and left that running again but still no change.

## Reproduce Steps
Place Iron ore next to a floating crystal and link it to the crystal.

## Additional Information
n/a

**Comment by generrosity** [comment]
At a guess a linking issue - took me ages to line things up my first time (that's what she said)

**Comment by greatmonkey** [comment]
I just loaded up a test world and found a crystal that was not under ground and it worked w/o any issues.  The one I did it with first was underground in a desert.

**Comment by generrosity** [comment]
Don't forget to hit "close issue" if sorted 😄
