### ISSUE TITLE
Server does not spawn mod ores (ie copper, aluminum, etc.) but singleplayer does.

### ISSUE THREAD

**Issue by abc12312348** [scalda/Foolcraft_3#87]
## Modpack Information
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [ ] I can reproduce this issue consistently
     - [ ] In single player
     - [x] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

**Comment by kpeckett** [comment]
Please fill out the rest of the issue template. (Also, are you launching the forge JAR or the vanilla Minecraft JAR?)

**Comment by scalda** [comment]
Closing as no response from the original author after @kpeckett response. if you still have the issue then please repost with the iusse template filled out correctly
