### ISSUE TITLE
You can't craft the Flux-Infused JetPlate

### ISSUE THREAD

**Issue by tomerkenis** [scalda/Foolcraft_3#88]
## Modpack Information
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [ ] In single player
     - [ ] In multiplayer
- [ ] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

You can't craft the angel ring because it requires the Flux-Infused JetPlate, which require the best flux pack, and for that you need all of the Energy Cells, but only the lead one it enabled

**Comment by scalda** [comment]
You clearly did search the current issues as there is already a issue
reading the angel ring so this is invalid

**Comment by tomerkenis** [comment]
this is not like what the other's reported, they reported that there is a bug with the Combination crafting,
but i am reporting that one of the ingredients is uncraftable

**Comment by scalda** [comment]
That issue has already been spoke about In A issue here.

**Comment by Elysara** [comment]
Haven't tried it on the latest since the server i'm on is still on 1.0.0, but on 1.0.0 crafting the flux-infused jetplate does work for me.

**Comment by moshan1997** [comment]
You,use a upgrade kit on energy cell in lastest version to upgrade them.DO YOU EVEN,THERMAL BRO

**Comment by scalda** [comment]
what @moshan1997 said
