### ISSUE TITLE
Issues with Energy Condenser Crafting

### ISSUE THREAD

**Issue by TheonlyTazz** [scalda/Foolcraft_3#89]
## Modpack Information
- [ ] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [ ] In single player
     - [x] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
Crafting the Energy Condenser isnt possible with the Gaiadice of Faith as the recipe needs an "unbound" one. 
whenever you kill the gaia guardian, it will be soulbound to your playerUUID, i dont know if this can be implemented or not?
`<botania:dice>.withTag({soulbindUUID: "PLAYERUUID"}`
alternatively you could use the gaia ingot instead (or the pinkinator aswell, although thats a "rare" drop from the gaia boss)

the Bloodmagic recipe has an unknown Bloodmagic orb (just <bloodmagic:blood_orb>) whereas all blood orb are either:
`<bloodmagic:blood_orb>.withTag({orb: "bloodmagic:weak"})`
upto:
`<bloodmagic:blood_orb>.withTag({orb: "bloodmagic:archmage"})`

and the shulkerbox, you gotta be careful that it you dont put it down beforehand bcause that will change the NBT data on the shulkerbox, making it unuseable in the crafting recipe
`<ironchest:iron_shulker_box_purple:2>.withTag({BlockEntityTag: {facing: 1 as byte, ShulkerBoxSize: 108}})`

**Comment by kpeckett** [comment]
I believe the blood orb has no NBT in the recipe so that any blood orb will work. Unfortunately this results in a missing item texture and name in JEI.

**Comment by TheonlyTazz** [comment]
That, I didn't test... But I will later today, nevertheless wouldn't it be better to gate the bloodied to like atleast the master bloodorb (I think that's tier IV)

**Comment by scalda** [comment]
These have been fixed in 1.3.0 as extended crafting needed to be updated for it to work correctly again

**Comment by scalda** [comment]
This should be fixed in the 1.3 version of the pack all the recipes work for me when i tested. so please report an issue if it persists in 1.3
