### ISSUE TITLE
(Literal) Power Creep mod

### ISSUE THREAD

**Issue by BrisingrAerowing** [scalda/Foolcraft_3#90]
## FEATURE REQUEST
- [x] I would like to propose an additional mod.
- [ ] I would like to propose a config change.
- [ ] I would like to propose a custom recipe.
- [ ] I would like to propose another change.

## MOD INFORMATION
[(Literal) Power Creep](https://minecraft.curseforge.com/projects/power-creep) - Adds a generator that produces power when creepers explode. Only outputs to the south, so automating it is a logistical challenge (those are the best kind, right?).

I personally think this would fit right in with the theme of FoolCraft.

**Comment by scalda** [comment]
Sorry but there is so many power gen mods that adding another one would just make no sense, but thanks for the suggestion
