### ISSUE TITLE
Server wont start

### ISSUE THREAD

**Issue by Gazton** [scalda/Foolcraft_3#91]
## Modpack Information
- [x] I am running the latest version of FoolCraft
- [x ] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [ ] In single player
     - [x] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [x] I am crashing and can provide my crash report(s)
- [x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description

Servercrash at start. We played like 20h already on it and then it crashed.

## Additional Information
https://pastebin.com/vteKDM7c

**Comment by Mrbysco** [comment]
Did you by any chance use multiparts?

**Comment by Gazton** [comment]
I have not installed any extra, but multipart (the mod when u can saw blocks into pieces) is there if thats what u ment?

**Comment by Mrbysco** [comment]
The mod is in the pack yes. What I ment to say was are you using the mod on the server (Have people used the saw to saw bits in pieces)?

**Comment by Gazton** [comment]
Yes and no. Just before it happend a friend crafted a stereo that seems to have bit and pieces in it.

**Comment by scalda** [comment]
Has this issue been resolved if so please close it or it will be closed on the 11/06/2018
