### ISSUE TITLE
Extreme reactor 

### ISSUE THREAD

**Issue by moshan1997** [scalda/Foolcraft_3#92]
Can you please add this mod cause energy generation is hard to get high RF/t in this pack

**Comment by Mrbysco** [comment]
Try Enviromental Tech. That mod's powergen is OP

**Comment by moshan1997** [comment]
ok

**Comment by scalda** [comment]
yeah extreme reactors won't be added as there are enough power gen mods in the pack and also Iskallium reactors will be making a come back
