### ISSUE TITLE
Foolcraft 3 crashing before start menu!

### ISSUE THREAD

**Issue by bd79** [scalda/Foolcraft_3#94]
## Modpack Information
- [ x] I am running the latest version of FoolCraft
- [x ] I am running FoolCraft via Curse/Twitch Launcher
- [ x] I can reproduce this issue consistently
     - [x ] In single player
     - [ ] In multiplayer
- [x ] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ x] I am crashing and can provide my crash report(s)
- [ x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]
## Issue Description
The problem is that when i try to start the game it starts and then waits until it comes to initialization of codechickenlib at the second step- After that it crashes imideatley.

I use windows 10 with 10 gigabytes allocated.

## Reproduce Steps
Start the pack normally and then just wait.

## Additional Information
Crash report: https://pastebin.com/UxV0RFtk

**Comment by Mrbysco** [comment]
Have you tried reinstalling the pack?

**Comment by bd79** [comment]
Yes i have

**Comment by moshan1997** [comment]
Its seems is the chicken core which cause you to crush😕

**Comment by bd79** [comment]
Yes, that i kinda already figurer out... But do you have a temporary or even a temporary solution?

**Comment by Mrbysco** [comment]
Is your modpack's folder in a cloud storage like onedrive or on your harddisk/ssd

**Comment by bd79** [comment]
When I go into the startup properties in launcher it says it is but I have Uninstalled it and use registry hack to remove icon, and when I tried to change path it changes it back

**Comment by bd79** [comment]
I fixed it!
I just went clicked on the white arrow up in the right corner in twitch launcher. and then i clicked settings, Minecraft, and then down to minecraft instalation and clicked change. the next thing i did was to go to "C:\Users\*USER*\Documents" and then created a folder named minecraft curse and then chose the install location to that folder.
