### ISSUE TITLE
Add EMC to Energy Condenser (MK2) and Transmutation Table

### ISSUE THREAD

**Issue by Yadokingu** [scalda/Foolcraft_3#95]
## FEATURE REQUEST
- [ ] I would like to propose an additional mod.
- [ ] I would like to propose a config change.
- [ ] I would like to propose a custom recipe.
- [X] I would like to propose another change.

## FEATURE INFORMATION

Adding EMC to the Energy Condenser (MK2) and Transmutation Table would reduce a lot of annoying crafting. I get gating Project E heavily initially, but once you have the energy condencers, making more shouldn't be as time consuming.

**Comment by scalda** [comment]
This is intended like this so people on servers can't just make one and then suddenly share it out to all other players on the server, so this won't be happening sorry

**Comment by Yadokingu** [comment]
Can't people just share a transmutation table and then make stuff with Equivalent Energistics, especially since with waystones you could always pop by somebodies base real quick?
If people want to share their progress, they are going to.
But I get that you won't change it. Thanks for the reply anyway. :)
