### ISSUE TITLE
Change elevator block range

### ISSUE THREAD

**Issue by Yadokingu** [scalda/Foolcraft_3#96]
## FEATURE REQUEST
- [ ] I would like to propose an additional mod.
- [X] I would like to propose a config change.
- [ ] I would like to propose a custom recipe.
- [ ] I would like to propose another change.

## FEATURE INFORMATION
Everybody likes zippping down to bedrock from their base without having to make 5 stops due to the 20 block distance limit of the elevator block. 
In Foolcraft the limit does make even less sense than usual, since you could just plop down a Waystone and teleport there directly anyway.

**Comment by scalda** [comment]
Change this for the 1.4 version of the pack thanks for the suggestion
