### ISSUE TITLE
MiniMoos only spawning water fluid moos in overworld

### ISSUE THREAD

**Issue by Twan23** [scalda/Foolcraft_3#97]
It's in the title

**Comment by kpeckett** [comment]
1. Next time, fill the form out rather than deleting it
2. I believe this was intentional. You can feed a mini moo a liquid and there's a chance it might transform into producing that liquid. (As there's no Tinkers', liquid metals come from Foundry, I believe)

**Comment by Twan23** [comment]
1. there was no form
2. okay, I didn't know that

**Comment by Mrbysco** [comment]
Yes there was a form.
When you press "New issue" you'll see this screen:
![afbeelding](https://user-images.githubusercontent.com/9308260/40923274-b0c0d282-6814-11e8-8871-8e833f7ad165.png)

after clicking the appropriate topic you get a form to fill in:
![afbeelding](https://user-images.githubusercontent.com/9308260/40923300-c5bf7792-6814-11e8-8a28-c62b11d2d05d.png)
