### ISSUE TITLE
The Ultimate Ingot not craftable

### ISSUE THREAD

**Issue by Twan23** [scalda/Foolcraft_3#98]
## Modpack Information
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [x] In single player
     - [ ] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [x] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
The ultimate ingot is not craftable, I put in the correct recipe, but the Crafting Core reports it's not correct.

## Reproduce Steps
Put the correct recipe on the pedestals, and watch it not working

**Comment by kpeckett** [comment]
Which version of Foolcraft 3 are you running? It should be listed on the Twitch launcher.

**Comment by Twan23** [comment]
i'm running 1.1.1

**Comment by Twan23** [comment]
![2018-06-04_11 59 24](https://user-images.githubusercontent.com/32294181/40911321-d20990da-67ee-11e8-8dc7-5f6a3a6c1ff9.png)

**Comment by TheonlyTazz** [comment]
Are u sure u have all 40ingots? Or have RF on it?

**Comment by Twan23** [comment]
Yes, I'm sure of that

**Comment by justinedwards** [comment]
I believe there is a problem with extendedcrafting that is causing this. I cannot craft an energy condenser and others cannot craft an angel ring.

**Comment by scalda** [comment]
This should be fixed in the 1.3 version of the pack all the recipes work for me when i tested. so please repost an issue if it persists in 1.3
