### ISSUE TITLE
mini moo config change

### ISSUE THREAD

**Issue by flamingram** [scalda/Foolcraft_3#99]
## FEATURE REQUEST
- [ ] I would like to propose an additional mod.
- [x ] I would like to propose a config change.
- [ ] I would like to propose a custom recipe.
- [ ] I would like to propose another change.

## MOD INFORMATION
i would like the chance to get sacred and angel moos and forsaken moos to spawn at the lowest chance for it to appear in the respective Dimentions they are allowed to spawn in ex sacred in over world 
https://minecraft.curseforge.com/projects/mini-moos

**Comment by scalda** [comment]
this is due to a few issues we were having during testing where those cows would crash the server when affected by potion effects hopefully the next version of the mod will fix this and i can then re-enable them, but until then they will stay disabled.

thanks for the suggestion though
